Repository YetiForceCompany/YetiForceCRM, pull requests merged in 2018-08, with the labels that each got.

#7379 \App\Config tests
  tests/App/Config.php
Labels: finished

#7401 Fixed #7015
  layouts/basic/modules/Vtiger/Detail/Widget/FastEdit.tpl
Labels: finished

#7405 Fixed preview the last import records
  layouts/basic/modules/Import/ImportPreview.tpl
  layouts/basic/modules/Import/Import_Finish_Buttons.tpl
  modules/Import/views/List.php
Labels: finished

#7409 Fixed import records when cache is enabled
  modules/Import/actions/Data.php
  modules/Import/models/Module.php
Labels: finished

#7411 Corrected mobile header bugs
  layouts/basic/modules/Vtiger/BodyHeader.tpl
  public_html/layouts/basic/styles/layout/_Header.scss
Labels: finished

#7413 Clean composer fix
  app/Installer/Composer.php
Labels: finished

#7416 Composer clean fix - show number of cleaned files
  app/Installer/Composer.php
Labels: finished

#7417 Improved parse filename from URL
  app/Fields/File.php
Labels: finished

#7419 Fixed last merge conflict resolution
  tests/Entity/C_RecordActions.php
Labels: finished

#7418 yarnclean
  .yarnclean
Labels: finished

#7425 yarnclean
  .yarnclean
Labels: finished

#7424 Update composer clean list
  app/Installer/Composer.php
Labels: finished

#7432 Changed calendar buttons place, added add button to time control and …
  layouts/basic/modules/Calendar/CalendarView.tpl
  layouts/basic/modules/Calendar/CalendarViewPreProcess.tpl
  layouts/basic/modules/OSSTimeControl/CalendarView.tpl
  layouts/basic/modules/OSSTimeControl/CalendarViewPreProcess.tpl
  layouts/basic/modules/Reservations/CalendarView.tpl
  layouts/basic/modules/Reservations/CalendarViewPreProcess.tpl
  public_html/layouts/basic/modules/Calendar/resources/CalendarView.js
  public_html/layouts/basic/modules/OSSTimeControl/resources/Calendar.js
  public_html/layouts/basic/modules/Reservations/resources/Calendar.js
  public_html/layouts/basic/styles/components/_Utilities.scss
Labels: finished

#7442 Fixed polish chars in language files
  languages/pl_pl/ActivityRegister.json
  languages/pl_pl/FInvoice.json
  languages/pl_pl/Home.json
  languages/pl_pl/IncidentRegister.json
  languages/pl_pl/Settings/Inventory.json
  languages/pl_pl/_Base.json
Labels: finished

#7443 custom template file path bugfix: stop iteration if found
  include/runtime/Viewer.php
Labels: finished

#7464 Fix SystemWarnings
  app/SystemWarnings/Security/Dependencies.php
Labels: finished

#7380 Added \App\Custom\NumberToWords tests
  tests/App/Custom_NumberToWords.php
Labels: finished

#7436 \App\Layout tests
  tests/App/Layout.php
Labels: VerificationRequired, finished

#7485 Is dynamic method
  modules/Vtiger/models/Block.php
Labels: finished

#7494 Fix notices in: Menu, RelatedListcontents
  layouts/basic/modules/Vtiger/RelatedListContents.tpl
  layouts/basic/modules/Vtiger/menu/HomeIcon.tpl
  modules/Vtiger/models/Menu.php
Labels: finished

#7507 Fixed notices ButtonLink.tpl
  layouts/basic/modules/Vtiger/ButtonLink.tpl
Labels: finished

#7514 Fixed remove records from "HideBlocks"
  modules/Settings/HideBlocks/actions/Delete.php
  modules/Settings/HideBlocks/actions/DeleteAjax.php
  modules/Settings/HideBlocks/models/Record.php
Labels: finished

#7545 Notice fix: Vtiger/SummaryWidgetsContent.tpl
  layouts/basic/modules/Vtiger/SummaryWidgetsContent.tpl
Labels: VerificationRequired, finished

#7544 Fixed notices: Vtiger/RelatedList.tpl, views/RecordsList.php
  layouts/basic/modules/Vtiger/RelatedList.tpl
  modules/Vtiger/views/RecordsList.php
Labels: finished

#7567 Fixed notice in field edit
  layouts/basic/modules/Settings/LayoutEditor/EditField.tpl
Labels: finished

#7565 Added panel with variables to signature
  layouts/basic/modules/Settings/Mail/Config.tpl
  modules/Settings/Mail/views/Config.php
  public_html/layouts/basic/modules/Settings/Mail/resources/Config.js
Labels: finished

#7570 Fixed notice in HelpInfo modal
  layouts/basic/modules/Settings/LayoutEditor/HelpInfo.tpl
  layouts/basic/modules/Settings/LayoutEditor/Modals/HelpInfoFooter.tpl
  modules/Settings/LayoutEditor/views/HelpInfo.php
Labels: finished

#7569 Fixed #7450 - Improved links to configuration mailbox
  modules/OSSMail/models/Module.php
Labels: finished

#7536 buttons outside form bugfix
  layouts/basic/modules/Vtiger/dashboards/ChartFilter.tpl
Labels: finished

#7549 Fixed role edit notice
  layouts/basic/modules/Settings/Roles/EditView.tpl
Labels: finished

#7574 Fixed notices in PickListDependency Settings module
  layouts/basic/modules/Settings/Vtiger/ListViewHeader.tpl
Labels: finished

#7527 Password_Modal
  layouts/basic/modules/Users/Modals/PasswordModalFooter.tpl
  layouts/basic/modules/Users/PasswordModal.tpl
  modules/Users/views/PasswordModal.php
Labels: finished

#7578 Fixed #7469
  layouts/basic/modules/Vtiger/EditViewInventory.tpl
Labels: finished

#7576 Fixed notices in PickListDependency Settings module v2
  layouts/basic/modules/Settings/PickListDependency/DependencyGraph.tpl
Labels: finished

#7585 Fixed notice in Menu settings tpl
  layouts/basic/modules/Settings/Menu/Index.tpl
Labels: finished

#7611 Added minor fixes in record ransfer
  include/CRMEntity.php
  modules/Vtiger/models/Relation.php
Labels: finished

#7581 Fixed notice in HideBlocks
  layouts/basic/modules/Settings/HideBlocks/EditView.tpl
Labels: finished

#7622 Fixed copying country field value
  public_html/layouts/basic/modules/Vtiger/resources/Edit.js
Labels: finished

#7523 Fixed date format configuration bug
  public_html/layouts/resources/Fields.js
Labels: finished

#7535 Updated colorpicker
  layouts/basic/modules/CustomView/EditView.tpl
  layouts/basic/modules/Settings/Calendar/UserColors.tpl
  layouts/basic/modules/Settings/Colors/Index.tpl
  public_html/layouts/basic/modules/CustomView/resources/CustomView.js
  public_html/layouts/basic/modules/Settings/Colors/resources/Index.js
Labels: finished

#7539 Undefined index: ID in LocksItem.tpl
  layouts/basic/modules/Settings/Users/LocksItem.tpl
Labels: finished

#7550 Fixed notice in automatic records allocation
  layouts/basic/modules/Settings/Vtiger/ListViewHeader.tpl
Labels: finished

#7579 Fixed notice in TreesManager
  layouts/basic/modules/Settings/TreesManager/ListViewHeader.tpl
Labels: finished

#7629 Fix for issue 7618 - problem with ZIP
  app/Zip.php
  modules/Vtiger/models/PDF.php
Labels: finished

#7608 import empty fields bugfix, default values are set up in one place (not many as it was before)
  modules/Import/actions/Data.php
Labels: finished

#7634 Improved display of the time of the last launch of the cron
  modules/Settings/CronTasks/models/Module.php
Labels: finished

#7592 Adding uitype twitter to the list of supported fields
  modules/Settings/LayoutEditor/models/Module.php
  modules/Vtiger/uitypes/Twitter.php
Labels: finished

#7633 AdvanceFilterCondition.tpl notices fixes
  layouts/basic/modules/Settings/Vtiger/AdvanceFilterCondition.tpl
Labels: finished

#7638 Small fix
  modules/Calendar/models/Export.php
Labels: finished

#7637 Fixed notices in hideblocks settings module
  layouts/basic/modules/Vtiger/AdvanceFilter.tpl
  modules/Settings/HideBlocks/models/Record.php
Labels: finished

#7582 Fixed notice in FieldMapping
  modules/Settings/Leads/models/Mapping.php
Labels: finished

#7643 Fix for search_params
  modules/Calendar/models/Export.php
  modules/Calendar/views/InRelation.php
  modules/OSSTimeControl/views/InRelation.php
  modules/OpenStreetMap/actions/GetMarkers.php
  modules/PriceBooks/views/Detail.php
  modules/SMSNotifier/actions/MassSaveAjax.php
  modules/Settings/Vtiger/views/Pagination.php
  modules/Users/views/List.php
  modules/Users/views/PasswordModal.php
  modules/Vtiger/actions/Mail.php
  modules/Vtiger/actions/Mass.php
  modules/Vtiger/actions/Pagination.php
  modules/Vtiger/actions/RelationAjax.php
  modules/Vtiger/actions/TransferOwnership.php
  modules/Vtiger/dashboards/MiniList.php
  modules/Vtiger/models/ChartFilter.php
  modules/Vtiger/views/Detail.php
  modules/Vtiger/views/IndexAjax.php
  modules/Vtiger/views/List.php
  modules/Vtiger/views/ListAjax.php
  modules/Vtiger/views/Pagination.php
  modules/Vtiger/views/RecordsList.php
  modules/Vtiger/views/RelatedList.php
  modules/Vtiger/views/SendMailModal.php
Labels: finished

#7646 Fixed notices
  modules/Settings/HideBlocks/views/Conditions.php
Labels: finished

#7653 Dont print html error page to console when in cli mode
  vtlib/Vtiger/Functions.php
Labels: VerificationRequired, enhancement, finished

#7657 Group admin notice
  layouts/basic/modules/Settings/Groups/EditView.tpl
Labels: finished

#7660 Removed '2' param from getArray uses
  modules/CustomView/models/Record.php
  modules/OpenStreetMap/models/Coordinate.php
  modules/Vtiger/models/RelationListView.php
Labels: finished

#7661 Fixed PLACE_HOLDER notice
  layouts/basic/modules/Users/Edit/Field/Picklist.tpl
Labels: finished

#7675 adequate invoice payment type picklist translations
  languages/pl_pl/FCorectingInvoice.json
  languages/pl_pl/FInvoiceProforma.json
Labels: Not Finished

#7674 Fixed notices in picklists management
  layouts/basic/modules/Vtiger/Modals/Footer.tpl
  modules/PickList/DependentPickListUtils.php
Labels: finished

#7672 Fixed E_NOTICE: Array to string conversion
  modules/Settings/Picklist/models/Module.php
Labels: finished

#7671 Fixed notice in FieldExpressions.tpl
  layouts/basic/modules/Vtiger/FieldExpressions.tpl
Labels: finished

#7665 Fixed notice RelatedListLeftSide.tpl, Detail.php
  layouts/basic/modules/Vtiger/RelatedListLeftSide.tpl
  modules/Vtiger/views/Detail.php
Labels: finished

#7677 Change of the return variable type
  modules/Settings/Leads/models/Mapping.php
  modules/Vtiger/models/Module.php
Labels: finished

#7663 Fixed notice in settings users model
  modules/Settings/Users/models/Module.php
Labels: finished

#7590 Social media twitter tables in the database
  install/install_schema/scheme.sql
Labels: finished

#7662 Removed unused code
  layouts/basic/modules/Settings/Vtiger/ListViewHeader.tpl
Labels: finished

#7389 \App\Field tests
  tests/App/Field.php
Labels: finished

#7434 getComponentClassName: search for files inside predefined dirs too
  include/Loader.php
Labels: finished

#7680 Disabled Central Bank of Russia currency update tests
  tests/Settings/CurrencyUpdate.php
Labels: finished

#7597 Fix for SharedOwner undefined variable $NOT_DISPLAY_LIST
  layouts/basic/modules/Vtiger/Edit/Field/SharedOwner.tpl
Labels: AmendmentsRequired

#7335 \App\Purifier initial tests
  tests/App/Purifier.php
Labels: finished

#7686 Fix notice: MappedFields/actions/SaveAjax.php
  modules/Settings/MappedFields/actions/SaveAjax.php
Labels: finished

#7692 Fixed notice: views/RelatedList.php
  modules/Vtiger/views/RelatedList.php
Labels: finished

#7690 TextParser
  tests/App/TextParser.php
Labels: finished

#7696 FCorectingInvoice_Edit_Js actualisation due to Vtiger_Edit_Js changes
  public_html/layouts/basic/modules/FCorectingInvoice/resources/Edit.js
Labels: finished

#7697 import module minor bugfix - do not import empty fields
  modules/Import/actions/Data.php
Labels: finished

#7702 Fixed notices in MappedFields settings module
  modules/Settings/MappedFields/models/Field.php
  modules/Settings/MappedFields/models/Module.php
Labels: finished

#7699 Fixed notice in Users Settings module model
  modules/Settings/Users/models/Module.php
Labels: finished

#7720 Fix js error: Vtiger_Inventory_Js is not defined
  public_html/layouts/basic/modules/Vtiger/resources/Edit.js
Labels: finished

#7723 Fixed typo
  languages/pl_pl/Settings/Users.json
Labels: finished

#7721 Fixed notices in ConfReport settings module
  layouts/basic/modules/Settings/ConfReport/Index.tpl
Labels: finished

#7719 Fixed notice in OSSPasswords settings module
  modules/Settings/OSSPasswords/views/ConfigurePass.php
Labels: finished

#7718 Fixed Multifilter
  layouts/basic/modules/Vtiger/dashboards/MultifilterContents.tpl
  modules/Vtiger/models/Multifilter.php
Labels: finished

#7713 Fixed notice in PublicHoliday settings module
  layouts/basic/modules/Settings/PublicHoliday/Configuration.tpl
Labels: finished

#7712 Fixed notice in inventory settings module modal
  layouts/basic/modules/Settings/Inventory/Modal.tpl
Labels: finished

#7709 TextParser tests coverage improvement
  tests/App/TextParser.php
Labels: finished

#7703 Fixed notice in tax settings
  layouts/basic/modules/Settings/Inventory/Index.tpl
Labels: finished

#7729 Fixed notice: RelatedListLeftSide.tpl in Documents, Contacts, OSSPasswords
  layouts/basic/modules/Contacts/RelatedListLeftSide.tpl
  layouts/basic/modules/Documents/RelatedListLeftSide.tpl
  layouts/basic/modules/OSSPasswords/RelatedListLeftSide.tpl
Labels: finished

#7722 Fixed notice in package import
  vtlib/Vtiger/PackageImport.php
Labels: finished

#7725 Fixed notices in DAV settings
  layouts/basic/modules/Settings/Dav/Keys.tpl
  modules/Settings/Dav/models/Module.php
Labels: AmendmentsRequired

#7731 Improved TextParser tests coverage
  tests/App/TextParser.php
Labels: finished

#7736 Fixed notices in SMSNotifier settings module
  modules/Settings/SMSNotifier/models/Module.php
  modules/Settings/SMSNotifier/views/Edit.php
Labels: finished

#7735 Fixed notices in WebserviceUsers
  layouts/basic/modules/Vtiger/Edit/Field/Reference.tpl
  modules/Settings/WebserviceUsers/models/Record.php
  modules/Settings/WebserviceUsers/views/Edit.php
Labels: finished

#7734 Fixed notices in HelpDesk module
  layouts/basic/modules/Vtiger/DetailViewProductsServicesContents.tpl
Labels: finished

#7745 Clean unused code
  modules/Vtiger/models/Multifilter.php
Labels: finished

#7746 change array name $socialAccounts to $twitterAccount in Vtiger_Social…
  modules/Vtiger/models/SocialMedia.php
Labels: AmendmentsRequired

#7741 Fix models/Privileges.php
  modules/Users/models/Privileges.php
Labels: finished

#7748 Fixed notice in workflows settings module
  layouts/basic/modules/Settings/Workflows/ListViewHeader.tpl
Labels: finished

#7747 Try to fix SensioLabs bug by use unused variable before try block
  app/AddressFinder/OpenCageGeocoder.php
Labels: VerificationRequired

#7749 Change GoogleGeocode to use protected $url
  app/AddressFinder/GoogleGeocode.php
Labels: finished

#7752 Use unused variable in ConfReport
  app/Utils/ConfReport.php
Labels: finished

#7754 Check if cron is active
  languages/pl_pl/Settings/SocialMedia.json
  layouts/basic/modules/Settings/SocialMedia/Index.tpl
Labels: finished

#7753 Fix unused variable and functions in Settings_ConfReport_Module_Model
  modules/Settings/ConfReport/models/Module.php
Labels: finished

#7756 Hot fix for Date and Boolean field on lists
  layouts/basic/modules/Vtiger/List/Field/Boolean.tpl
  layouts/basic/modules/Vtiger/List/Field/Date.tpl
Labels: finished

#7766 Removed reference to old bootstrap.css file
  layouts/basic/modules/Leads/ConvertLeadError.tpl
  layouts/basic/modules/Vtiger/DatabaseException.tpl
  layouts/basic/modules/Vtiger/IllegalValue.tpl
  layouts/basic/modules/Vtiger/NoPermissionsForRecord.tpl
  layouts/basic/modules/Vtiger/OperationNotPermitted.tpl
  layouts/basic/modules/Vtiger/browsercompatibility/Browser_compatibility.html
  public_html/layouts/basic/modules/Vtiger/browsercompatibility/Browser_compatibility.html
Labels: Not Finished

#7774 Fixed notice: Settings/Mail/Autologin.tpl, Settings/OSSMailScanner/Index.tpl
  layouts/basic/modules/Settings/Mail/Autologin.tpl
  layouts/basic/modules/Settings/OSSMailScanner/Index.tpl
Labels: finished

#7772 Add fix to include ButtonLink.tpl from Widget/Basic.tpl
  layouts/basic/modules/Vtiger/Detail/Widget/Basic.tpl
Labels: finished

#7776 Add fix to include buttonLink.tpl in Vtiger/Comment.tpl
  layouts/basic/modules/Vtiger/Comment.tpl
Labels: AmendmentsRequired

#7763 Fixed notices in workflow settings module
  layouts/basic/modules/Settings/Workflows/AdvanceFilterCondition.tpl
  layouts/basic/modules/Settings/Workflows/FieldExpressions.tpl
  layouts/basic/modules/Settings/Workflows/Step1.tpl
  modules/Settings/Workflows/actions/Save.php
  modules/Settings/Workflows/models/Record.php
  modules/Settings/Workflows/models/TaskRecord.php
Labels: finished

#7762 Fix undefined index of array in OSSPasswords/RelatedListContents.tpl
  layouts/basic/modules/OSSPasswords/RelatedListContents.tpl
Labels: finished

#7758 Fix undefined INVENTORY_MODULE in RelatedListContents.tpl
  layouts/basic/modules/Vtiger/RelatedListContents.tpl
Labels: finished

#7765 Fixed notices: Mail/ListViewContents.tpl, Mail/ListViewContents.tpl, ConfigEditorDetail.tpl, SwitchUsersItem.tpl
  layouts/basic/modules/Settings/Mail/ListViewContents.tpl
  layouts/basic/modules/Settings/Mail/ListViewHeader.tpl
  layouts/basic/modules/Settings/Users/SwitchUsersItem.tpl
  layouts/basic/modules/Settings/Vtiger/ConfigEditorDetail.tpl
Labels: finished

#7782 Fix undefined events by date in Calendar/QuickCreateEvents.tpl
  layouts/basic/modules/Calendar/QuickCreateEvents.tpl
Labels: finished

#7788 Add fix to comments widget in Vtiger_Detail_View
  modules/Vtiger/views/Detail.php
Labels: finished

#7777 Fixed E_NOTICE in KnowledgeBase module
  layouts/basic/modules/KnowledgeBase/PageView.tpl
Labels: finished

#7786 Fixed link in Github authorization settings modal
  languages/de_de/Settings/Github.json
  languages/en_us/Settings/Github.json
  languages/es_es/Settings/Github.json
  languages/fr_fr/Settings/Github.json
  languages/it_it/Settings/Github.json
  languages/pl_pl/Settings/Github.json
  languages/pt_br/Settings/Github.json
  languages/ro_ro/Settings/Github.json
  languages/ru_ru/Settings/Github.json
  languages/tr_tr/Settings/Github.json
  layouts/basic/modules/Settings/Github/Github.tpl
Labels: finished

#7785 Add fix for undefined variable in Vtiger/Edit/InventoryItem.tpl
  layouts/basic/modules/Vtiger/Edit/InventoryItem.tpl
Labels: finished

#7790 Delete undefined name $ASSIGNED_USER_ID in OSSTimeControl/RightPanel.tpl and standardize some code
  layouts/basic/modules/OSSTimeControl/RightPanel.tpl
Labels: finished

#7787 Improved error messages view
  include/main/WebUI.php
  layouts/basic/modules/Vtiger/IllegalValue.tpl
  layouts/basic/modules/Vtiger/NoPermissionsForRecord.tpl
  layouts/basic/modules/Vtiger/OperationNotPermitted.tpl
Labels: finished

#7792 Add checking ITEM_VALUE before include field tpl in Inventory.tpl
  layouts/basic/modules/FCorectingInvoice/Edit/Inventory.tpl
  layouts/basic/modules/Vtiger/Edit/Inventory.tpl
Labels: finished

#7805 Fixed import mail to crm in roundcube header
  modules/OSSMailScanner/scanneractions/CreatedEmail.php
Labels: finished

#7803 Fixed notice in mailbox badge (CRM header)
  layouts/basic/modules/Vtiger/BodyHeader.tpl
Labels: finished

#7801 Fixed bug - Add widget with filter
  layouts/basic/modules/Settings/WidgetsManagement/Configuration.tpl
Labels: finished

#7798 Fixed notices: Vtiger/AdvanceFilterCondition.tpl, uitypes/MultiReferenceValue.php, views/EditAjax.php
  layouts/basic/modules/Vtiger/AdvanceFilterCondition.tpl
  modules/CustomView/views/EditAjax.php
  modules/Vtiger/uitypes/MultiReferenceValue.php
Labels: finished

#7807 Added buttons styles for new mail uitype
  public_html/layouts/basic/styles/components/_Buttons.scss
  public_html/layouts/basic/styles/libraries/_Bootstrap.scss
Labels: finished

#7793 Fix module single name in InventoryTaxes.tpl
  layouts/basic/modules/Vtiger/InventoryTaxes.tpl
Labels: finished

#7808 Fixed notices in OSSMail mail bar
  layouts/basic/modules/OSSMail/MailActionBar.tpl
Labels: finished

#7809 Fix PriceBooks/Edit/Field/Boolean.tpl and Vtiger_Field_Model
  layouts/basic/modules/PriceBooks/Edit/Field/Boolean.tpl
  modules/Vtiger/models/Field.php
Labels: finished

#7761 Fixed notices: PDF/ListViewHeader.tpl, SupportProcesses/Index.tpl
  layouts/basic/modules/Settings/PDF/ListViewHeader.tpl
  layouts/basic/modules/Settings/SupportProcesses/Index.tpl
Labels: finished

#7810 SONAR
  sonar-project.properties
Labels: in progress

#7813 Fix Campaigns/RelatedList.tpl
  layouts/basic/modules/Campaigns/RelatedList.tpl
Labels: finished

#7817 Fix undefined index frequency in Notification_NotificationConfig_View
  modules/Notification/views/NotificationConfig.php
Labels: finished

#7815 Fix undefined coordinate in OpenStreetMap_Coordinate_Model
  modules/OpenStreetMap/models/Coordinate.php
Labels: finished

#7816 Add null variables to load AdvanceFilter.tpl in AdvanceSearch.tpl
  layouts/basic/modules/Vtiger/AdvanceSearch.tpl
Labels: finished

#7821 added git fetch --unshallow to travis before script
  .travis.yml
Labels: finished

#7823 Fixed passing invalid arguments to implode in Settings_Calendar_Module_Model
  modules/Settings/Calendar/models/Module.php
Labels: finished

#7822 Fix undefined SOURCE_MODULE in MappedFields/ListViewHeader.tpl
  layouts/basic/modules/Settings/MappedFields/ListViewHeader.tpl
Labels: finished

#7820 Added few fix to users lists
  app/QueryField/DatetimeField.php
  modules/Users/views/List.php
Labels: finished

#7827 TextParser test fix
  tests/App/TextParser.php
Labels: finished

#7843 Fixed FInvoiceProforma.json translation file
  languages/de_de/FInvoiceProforma.json
Labels: finished

#7847 Fixed #7828
  modules/Settings/Workflows/models/Record.php
Labels: finished

#7852 Fixed notice in Workflows/Step1.tpl
  layouts/basic/modules/Settings/Workflows/Step1.tpl
Labels: finished

#7855 Improved loading predefined widgets in button
  layouts/basic/modules/Vtiger/dashboards/DashBoardButtons.tpl
  layouts/basic/modules/Vtiger/dashboards/DashBoardWidgetsList.tpl
  modules/Vtiger/views/BasicAjax.php
  public_html/layouts/basic/modules/Vtiger/resources/DashBoard.js
Labels: finished

#7861 Fixed #7858
  layouts/basic/modules/Vtiger/BodyHeader.tpl
  modules/Vtiger/views/BasicAjax.php
Labels: finished

#7878 Sensiolabs: Object parameters should be type hinted
  modules/Vtiger/helpers/Util.php
Labels: finished

#7879 Fix convertToUserTimeZone
  include/fields/DateTimeField.php
Labels: finished

#7883 Fixed notice to Workflows/EditTask.tpl
  layouts/basic/modules/Settings/Workflows/EditTask.tpl
  modules/Settings/Workflows/views/EditTask.php
Labels: finished

#7885 Fixed notice to VTEmailTask.tpl
  layouts/basic/modules/Settings/Workflows/Tasks/VTEmailTask.tpl
  modules/Settings/Workflows/actions/TaskAjax.php
  modules/com_vtiger_workflow/VTTaskManager.php
Labels: finished

#7889 Fix scrutinizer: "type Formatted (..) is incompatible with the return type of the parent method"
  include/fields/CurrencyField.php
Labels: finished

#7891 Fixed notice to VTUpdateFieldsTask.tpl
  layouts/basic/modules/Settings/Workflows/Tasks/VTUpdateFieldsTask.tpl
Labels: finished
