Repository YetiForceCompany/YetiForceCRM, pull requests merged in 2018-07, with the labels that each got.

#7112 Fixed menu user information on mobile, cleaned code
  layouts/basic/modules/Vtiger/BodyLeft.tpl
Labels: finished

#7118 Corrected view the general Info content to mobile
  layouts/basic/modules/Vtiger/Detail/Widget/GeneralInfoContent.tpl
Labels: finished

#7129 Added translation
  languages/en_us/_Base.json
Labels: finished

#7131 search tree bug fix
  public_html/layouts/basic/modules/Vtiger/resources/Edit.js
Labels: finished

#7132 list view export all bugfix
  public_html/layouts/basic/modules/Vtiger/resources/List.js
Labels: finished

#7140 Mass delete ideas bugfix
  public_html/layouts/basic/modules/Vtiger/resources/List.js
Labels: finished

#7135 Corrected menu event on ios
  public_html/layouts/resources/app.js
Labels: finished

#7134 Added translation
  languages/de_de/_Base.json
  languages/es_es/_Base.json
  languages/fr_fr/_Base.json
  languages/it_it/_Base.json
  languages/pt_br/_Base.json
  languages/ro_ro/_Base.json
  languages/ru_ru/_Base.json
  languages/tr_tr/_Base.json
Labels: finished

#7144 Changed request method to post
  public_html/layouts/resources/Fields.js
Labels: finished

#7089 Corrected view in quick create to the mobile - module reservation
  layouts/basic/modules/Reservations/QuickCreate.tpl
Labels: finished

#7096 Fixed validation in massedit
  public_html/layouts/basic/modules/Vtiger/resources/List.js
Labels: finished

#7116 Removed unneeded option from select
  layouts/basic/modules/Vtiger/dashboards/ChartFilter.tpl
  modules/Vtiger/views/ChartFilter.php
Labels: finished

#7126 use kzykhys/php-csv-parser for csv file import
  modules/Import/readers/CSVReader.php
Labels: finished

#7115 Fixed greater than zero validation
  public_html/layouts/resources/validator/FieldValidator.js
Labels: finished

#7162 lib_roundcube version bump 0.0.48
  config/version.php
Labels: finished

#7169 Language setlocale constant 0 bugfix
  app/Language.php
Labels: finished

#7170 osstimecontrol calendar add event appearance fixed
  public_html/layouts/basic/modules/OSSTimeControl/resources/Calendar.js
Labels: finished

#7176 nbsp currency separator bugfix
  layouts/basic/modules/Users/Edit/Field/Picklist.tpl
Labels: finished

#7177 Fixed grater than zero validator
  public_html/layouts/resources/validator/FieldValidator.js
Labels: finished

#7182 Fixed datatables styles
  modules/PermissionInspector/views/UserListModal.php
  public_html/layouts/basic/styles/layout/_Modal.scss
  public_html/layouts/basic/styles/libraries/_Libraries.scss
Labels: finished

#7183 Configuration logs layout fix
  layouts/basic/modules/Settings/ConfReport/Index.tpl
  public_html/layouts/basic/modules/Settings/ConfReport/resources/Index.js
Labels: finished

#7186 phpspreadsheet updated
  composer.json
Labels: finished

#7189 save session with password reset before js configuration is resolved
  modules/Users/models/Record.php
Labels: VerificationRequired

#7197 Improved validation in import from ZIP
  app/Fields/File.php
  app/Zip.php
  layouts/basic/modules/Import/Import_Step2.tpl
  modules/Import/readers/ZipReader.php
Labels: finished

#7201 #7157
  public_html/layouts/basic/modules/Vtiger/resources/Header.js
Labels: finished

#7202 Improved permissions after save
  modules/Calendar/actions/Save.php
  modules/Vtiger/actions/Save.php
  modules/Vtiger/models/Record.php
  vtlib/Vtiger/Functions.php
Labels: finished

#7203 Improved searching in comments
  layouts/basic/modules/Vtiger/Comment.tpl
  public_html/layouts/basic/modules/Vtiger/resources/Detail.js
Labels: finished

#7206 removed not null column types from orders inventory database scheme
  install/install_schema/scheme.sql
Labels: finished

#7213 TextParser improvement
  app/TextParser.php
  modules/Notification/cron/Notifications.php
Labels: finished

#7214 Notification settings save improvement
  public_html/layouts/basic/modules/Notification/resources/NotificationConfig.js
Labels: finished

#7232 Fix issue
  layouts/basic/modules/Settings/MappedFields/Step2.tpl
Labels: finished

#7233 Fix for codeCoverage
  tests/Entity/Authy2FA.php
Labels: finished

#7236 Translation
  languages/pl_pl/Users.json
Labels: finished

#7235 Improved Colors settings module tests, added ConfReport settings modu…
  tests/Settings/Colors.php
  tests/Settings/ConfReport.php
Labels: VerificationRequired, finished

#7240 chartfilter multiple filters bugfix
  layouts/basic/modules/Vtiger/dashboards/ChartFilter.tpl
Labels: finished

#7243 chartfilter groups in custom search field
  layouts/basic/modules/Vtiger/List/Field/Owner.tpl
  layouts/basic/modules/Vtiger/dashboards/ChartFilterHeader.tpl
Labels: finished

#7245 bar chart threshold for hidding datalabels
  public_html/layouts/basic/modules/Vtiger/resources/dashboards/Widget.js
Labels: finished

#7246 spread operator removed
  public_html/layouts/basic/modules/Vtiger/resources/Detail.js
Labels: finished

#7247 duplicate event attachment removal for related lists in detail view
  public_html/layouts/basic/modules/Vtiger/resources/RelatedList.js
Labels: finished

#7253 Fixed currency settings module tests related problems in database ini…
  tests/Init/3_Install.php
Labels: finished

#7254 multi category tree export import
  modules/Import/actions/Data.php
  modules/Vtiger/models/Export.php
Labels: finished

#7262 Improved permissions to buttons in a dashboard
  modules/Users/models/Privileges.php
Labels: finished

#7263 Added minor fix in import rekords
  public_html/layouts/basic/modules/Import/resources/Import.js
Labels: Not Finished, finished

#7268 Fixed the order of saving products in advanced block
  modules/Vtiger/models/Record.php
Labels: finished

#7271 Fixed Session error when Session::Init() called multiple times
  app/Session.php
  user_privileges/advancedPermission.php
  user_privileges/watchdogModule.php
Labels: finished

#7269 Small fixes
  tests/Entity/A_User.php
  tests/Entity/C_RecordActions.php
  tests/Entity/E_TestModule.php
  tests/Init/B_Install.php
Labels: finished

#7274 Fixed #7258
  modules/Settings/LayoutEditor/actions/Field.php
Labels: finished

#7275 Fixed remove key in dav
  modules/Settings/Dav/models/Module.php
Labels: finished

#7273 Improved QueryGenerator
  app/QueryField/BaseField.php
  app/QueryGenerator.php
Labels: finished

#7281 Removed require_once for deleted file: LanguageHandler.php
  modules/Vtiger/helpers/Util.php
Labels: finished

#7295 Fixed translations
  languages/pl_pl/ModComments.json
  languages/pl_pl/SRecurringOrders.json
  languages/pl_pl/_Base.json
Labels: finished

#7293 Added translations
  languages/de_de/Settings/PBX.json
  languages/en_us/Settings/PBX.json
  languages/fr_fr/Settings/PBX.json
  languages/it_it/Settings/PBX.json
  languages/pl_pl/Settings/PBX.json
  languages/pt_br/Settings/PBX.json
  languages/ro_ro/Settings/PBX.json
  languages/ru_ru/Settings/PBX.json
  languages/tr_tr/Settings/PBX.json
Labels: finished

#7296 Improved pdf export modal
  layouts/basic/modules/Vtiger/ExportPDF.tpl
Labels: finished

#7298 plus one day normalization for milestones and projects
  modules/Project/models/Gantt.php
Labels: finished

#7309 add chart from filter modal form full responsiveness
  layouts/basic/modules/Vtiger/dashboards/ChartFilter.tpl
Labels: finished

#7313 calendar addButton click event missing bugfix
  public_html/layouts/basic/modules/Calendar/resources/CalendarView.js
Labels: finished

#7318 Fixed #7307
  modules/Vtiger/handlers/Workflow.php
Labels: finished

#7317 Disabled autocomplete in date/time inputs
  layouts/basic/modules/Calendar/Edit/Field/Time.tpl
  layouts/basic/modules/Events/Edit/Field/Time.tpl
  layouts/basic/modules/Vtiger/Edit/Field/DateTimeField.tpl
  layouts/basic/modules/Vtiger/Edit/Field/Time.tpl
  layouts/basic/modules/Vtiger/List/Field/Date.tpl
  layouts/basic/modules/Vtiger/List/Field/Time.tpl
Labels: finished

#7320 Skype field fix
  app/QueryField/SkypeField.php
Labels: finished

#7314 Tests for \App\TextParser
  tests/App/TextParser.php
Labels: Not Finished

#7323 TextParser
  tests/App/TextParser.php
Labels: Not Finished

#7329 resize widget content on gridstack resize event
  public_html/layouts/basic/modules/Vtiger/resources/dashboards/Widget.js
Labels: finished

#7332 Edit record - date format improvement
  layouts/basic/modules/Vtiger/EditViewBlocks.tpl
Labels: finished

#7334 Chat modal fix
  layouts/basic/modules/Vtiger/BodyHeader.tpl
  public_html/layouts/basic/styles/layout/_Header.scss
Labels: finished

#7340 Changed gridstack functions names, added w3c corrections
  layouts/basic/modules/Vtiger/dashboards/DashBoardContents.tpl
  public_html/layouts/basic/modules/Vtiger/resources/DashBoard.js
Labels: finished

#7342 bugfix: removed cascading for record list in tree view setup because in fact it never worked
  public_html/layouts/resources/libraries/jstree.checkbox.js
Labels: finished

#7343 Fix code
  public_html/layouts/basic/modules/Calendar/resources/CalendarView.js
Labels: finished

#7344 Set progressIndicator in product edit
  public_html/layouts/basic/modules/Products/resources/Edit.js
Labels: finished

#7354 Fixed modal events in iframe
  public_html/layouts/resources/app.js
Labels: finished

#7356 Corrected dashboard buttons RWD and added all functionality on mobile
  layouts/basic/modules/Vtiger/dashboards/DashBoardButtons.tpl
  layouts/basic/modules/Vtiger/dashboards/DashBoardHeader.tpl
  public_html/layouts/basic/styles/components/_Utilities.scss
Labels: finished

#7364 \App\Language tests
  tests/App/Language.php
Labels: finished

#7377 yarnclean
  .yarnclean
Labels: finished

#7376 Composer cleaning script
  app/Installer/Composer.php
Labels: finished

#7341 EmailParser tests
  tests/App/EmailParser.php
  tests/Entity/C_RecordActions.php
Labels: finished

#7388 Change page title for edit, create, detail
  modules/Contacts/views/Edit.php
  modules/Vtiger/views/Detail.php
Labels: finished

#7387 Remove static
  tests/Entity/C_RecordActions.php
Labels: finished

#7382 #7359
  modules/com_vtiger_workflow/VTTaskManager.php
Labels: finished

#7381 #7367
  layouts/basic/modules/Vtiger/RelatedListButtons.tpl
  public_html/layouts/basic/modules/Vtiger/resources/Detail.js
  public_html/layouts/basic/styles/layout/_Nav.scss
Labels: finished

#7390 Fixed #7384
  languages/en_us/Settings/Search.json
  languages/en_us/Settings/Workflows.json
  languages/it_it/Settings/Search.json
  languages/it_it/Settings/Workflows.json
  languages/pt_br/Settings/Workflows.json
  languages/tr_tr/Settings/Search.json
  languages/tr_tr/Settings/Workflows.json
Labels: finished

#7393 correcting invoice scheme update
  install/install_schema/scheme.sql
Labels: finished

#7378 \App\Layout\Icon tests
  tests/App/Layout_Icon.php
Labels: finished

#7383 \App\Debuger tests
  tests/App/Debuger.php
Labels: finished

#7395 yarnclean - src
  .yarnclean
Labels: finished
