Repository YetiForceCompany/YetiForceCRM, pull requests merged in 2018-11, with the labels that each got.

#8469 Fixed redirect to listview from widget "Overdue Activities"
  public_html/layouts/basic/modules/Vtiger/resources/dashboards/Widget.js
Labels: finished

#8495 Fixed typos
  app/Encryption.php
Labels: finished

#8484 Added color convert library to control its version
  package.json
Labels: finished

#8487 Refactored widget position function
  modules/Vtiger/models/Widget.php
Labels: finished

#8493 Disabled session last activity increment on chat calls
  modules/Chat/actions/Room.php
Labels: AmendmentsRequired

#8508 Corrected group and corrected view chat
  languages/pl_pl/Chat.json
  layouts/basic/modules/Chat/Chat.tpl
  layouts/basic/modules/Chat/Item.tpl
  layouts/basic/modules/Chat/Modal.tpl
  layouts/basic/modules/Chat/ModalFooter.tpl
  public_html/layouts/basic/modules/Chat/resources/Chat.js
  public_html/layouts/basic/styles/components/_Chat.scss
Labels: Not Finished, in progress

#8498 Fixed renewal
  modules/Assets/models/Record.php
  modules/OSSSoldServices/models/Record.php
Labels: finished

#8510 Added test for encryption
  tests/App/Encryption.php
Labels: finished

#8517 New timeline style (changed colors)
  public_html/layouts/basic/styles/pages/_Detail.scss
Labels: finished

#8522 Added icon to chat button more message
  layouts/basic/modules/Chat/Entries.tpl
  public_html/layouts/basic/modules/Chat/resources/Chat.js
  public_html/layouts/basic/styles/components/_Chat.scss
Labels: finished

#8521 Fixed #8389
  app/Json.php
Labels: finished

#8514 Fixed #8511, #8456
  modules/com_vtiger_workflow/WorkFlowScheduler.php
Labels: finished

#8523 Fixed detail view summary
  layouts/basic/modules/Vtiger/Detail/Widget/Activities.tpl
  layouts/basic/modules/Vtiger/Detail/Widget/Basic.tpl
  layouts/basic/modules/Vtiger/Detail/Widget/BasicComments.tpl
  layouts/basic/modules/Vtiger/Detail/Widget/EmailList.tpl
  layouts/basic/modules/Vtiger/Detail/Widget/FastEdit.tpl
  layouts/basic/modules/Vtiger/Detail/Widget/HistoryRelation.tpl
  layouts/basic/modules/Vtiger/Detail/Widget/ProductsServicesBasic.tpl
  layouts/basic/modules/Vtiger/Detail/Widget/SummaryCategory.tpl
  layouts/basic/modules/Vtiger/Detail/Widget/Updates.tpl
  layouts/basic/modules/Vtiger/Detail/Widget/WYSIWYG.tpl
Labels: finished

#8527 Fixed #8520
  modules/Vtiger/views/Detail.php
  modules/Vtiger/views/DetailPreview.php
  modules/Vtiger/views/ListPreview.php
Labels: finished

#8531 Fixed modules color
  app/Colors.php
  modules/Settings/Colors/actions/SaveAjax.php
  modules/Settings/ModuleManager/actions/Basic.php
  tests/Settings/Colors.php
Labels: finished

#8533 Fixed edit calendar record in list preview
  public_html/layouts/basic/modules/Vtiger/resources/Detail.js
Labels: finished

#8535 Chat minor improvements
  modules/Chat/views/Modal.php
Labels: finished

#8536 Chat removal of unnecessary code
  modules/Chat/models/Module.php
Labels: finished

#8537 Calendar - history improvement
  public_html/layouts/basic/modules/Calendar/resources/Extended/CalendarView.js
  public_html/layouts/resources/Calendar.js
Labels: finished

#8562 Added count badge text contrast on calendar widget
  public_html/layouts/basic/modules/Vtiger/resources/dashboards/Widget.js
  public_html/layouts/basic/styles/components/_Utilities.scss
Labels: finished

#8565 Fixed data format
  modules/Vtiger/actions/Fields.php
  public_html/layouts/basic/modules/Vtiger/resources/dashboards/Widget.js
Labels: finished

#8564 Removed image upload from KnowledgeDatabase module wyswing editor
  modules/KnowledgeBase/actions/ImageUploadAjax.php
  public_html/layouts/basic/modules/KnowledgeBase/resources/Edit.js
Labels: finished

#8563 Fixed extension type module import (no default language error)
  modules/Settings/ModuleManager/views/ModuleImport.php
  vtlib/Vtiger/PackageImport.php
  vtlib/Vtiger/PackageUpdate.php
Labels: finished

#8560 Fix notice undefined index
  layouts/basic/modules/Vtiger/ListViewContents.tpl
Labels: finished

#8572 Style fix - timeline style on detail page
  public_html/layouts/basic/styles/pages/_Detail.scss
Labels: finished

#8577 Fixed SQuotes inventory fields handling
  modules/Vtiger/inventoryfields/Currency.php
  modules/Vtiger/inventoryfields/DiscountMode.php
Labels: finished

#8576 Corrected contrasts in colors set by user
  app/Colors.php
  modules/Vtiger/uitypes/Picklist.php
  public_html/layouts/basic/modules/Vtiger/resources/dashboards/Widget.js
Labels: finished

#8578 Generate contrast color for all fields
  app/Colors.php
Labels: finished

#8579 Fixed currency field
  layouts/basic/modules/Services/Edit/Currencies.tpl
  layouts/basic/modules/Vtiger/Edit/Field/Currency.tpl
Labels: finished

#8586 Corrected hiding and showing pdf button
  layouts/basic/modules/Vtiger/Detail/HeaderButtons.tpl
  modules/Documents/models/ListView.php
  modules/SMSNotifier/models/ListView.php
  modules/Vtiger/models/DetailView.php
  modules/Vtiger/models/ListView.php
  public_html/layouts/basic/modules/Vtiger/resources/Detail.js
  public_html/layouts/basic/modules/Vtiger/resources/Header.js
Labels: finished

#8592 Fixed #7840
  app/QueryField/MultipicklistField.php
Labels: finished

#8597 Added lacking icons for submenu
  layouts/basic/modules/Vtiger/menu/CustomFilter.tpl
  layouts/basic/modules/Vtiger/menu/Module.tpl
  layouts/basic/modules/Vtiger/menu/Script.tpl
  layouts/basic/modules/Vtiger/menu/SubMenu.tpl
Labels: finished

#8599 Fixed sending mails actions buttons
  layouts/basic/modules/Settings/ConfReport/Index.tpl
  public_html/layouts/basic/modules/OSSMailView/resources/Detail.js
  public_html/layouts/basic/styles/_Style.scss
Labels: finished

#8596 Fixed #8284
  layouts/basic/modules/KnowledgeBase/PageView.tpl
  layouts/basic/modules/KnowledgeBase/PresentationView.tpl
  public_html/layouts/resources/Fields.js
Labels: finished

#8598 Fixed #8595
  modules/Vtiger/models/Record.php
Labels: finished

#8602 Reverted condition from button link
  layouts/basic/modules/Vtiger/ButtonLink.tpl
Labels: finished

#8601 Added remaping fields for OpenCage (#7290)
  app/Map/Address/OpenCageGeocoder.php
  config/modules/AddressFinder.php
Labels: finished

#8603 Fixed fatal error
  layouts/basic/modules/Vtiger/Edit/Inventory.tpl
Labels: finished

#8604 Fixed mass actions (Fixed #8068)
  app/Mailer.php
  modules/Calendar/models/Export.php
  modules/Portal/models/Module.php
  modules/SMSNotifier/actions/MassSaveAjax.php
  modules/Vtiger/actions/Mail.php
  modules/Vtiger/actions/TransferOwnership.php
  modules/Vtiger/views/IndexAjax.php
  modules/Vtiger/views/MassActionAjax.php
  modules/Vtiger/views/SendMailModal.php
  public_html/layouts/basic/modules/Settings/SMSNotifier/resources/Edit.js
  public_html/layouts/basic/modules/Vtiger/resources/List.js
Labels: finished

#8607 Automatic replenishment of the contractor field
  user_privileges/moduleHierarchy.php
Labels: finished

#8611 Empty value when is not selected item in picklist depedency
  app/Fields/Picklist.php
  config/performance.php
Labels: finished

#8618 Improved validation data from request for "Path"
  app/Purifier.php
Labels: finished

#8610 Fixed "The expression \App\Session::clean() of type string is not tra…
  app/Session.php
  app/Session/Base.php
Labels: finished

#8612 Api multiimage upload
  app/Fields/File.php
  modules/Vtiger/uitypes/MultiImage.php
Labels: AmendmentsRequired

#8615 Added favorites star in owner field (select2)
  layouts/basic/modules/Vtiger/Edit/Field/Owner.tpl
  public_html/layouts/resources/Fields.js
Labels: finished

#8631 Fix when somebody is not permitted to view default module after login
  include/main/WebUI.php
Labels: finished

#8624 Show taxes/discounts on list with user decimal separator
  layouts/basic/modules/Vtiger/Detail/InventorySummary.tpl
  public_html/layouts/basic/modules/Settings/Inventory/resources/Index.js
Labels: finished

#8635 Improved save attachments
  app/Fields/File.php
Labels: finished

#8638 Fixed export records in calendar
  modules/Calendar/models/Export.php
Labels: finished

#8630 Added favorites star in shared owner field
  layouts/basic/modules/Vtiger/Edit/Field/Owner.tpl
  layouts/basic/modules/Vtiger/Edit/Field/SharedOwner.tpl
  public_html/layouts/resources/Fields.js
Labels: finished

#8639 Fixed #8230
  layouts/basic/modules/Vtiger/InventoryTaxesType0.tpl
Labels: finished

#8641 Fixed a few notices
  app/TextParser/TableTaxSTwoLang.php
  app/TextParser/TableTaxSummary.php
Labels: finished

#8642 Fixed ui-sortable placeholder's width
  layouts/basic/modules/Vtiger/Edit/InventoryItem.tpl
  public_html/layouts/basic/styles/libraries/_Libraries.scss
Labels: finished

#8653 ListPreview.js cache fix
  public_html/layouts/basic/modules/Vtiger/resources/ListPreview.js
Labels: finished

#8646 Fixed Name of IMAP server select
  layouts/basic/modules/Settings/OSSMail/Index.tpl
Labels: finished

#8644 Added 0.00 to numberToWords tests [Issue #7802]
  tests/App/Custom_NumberToWords.php
Labels: finished

#8649 Fixed #7835 - Fix error when adding language
  modules/Settings/LangManagement/actions/SaveAjax.php
  public_html/layouts/basic/modules/Settings/LangManagement/resources/LangManagement.js
Labels: finished

#8652 Improved widget a newest mails
  modules/OSSMail/models/Record.php
Labels: finished

#8650 Fixed Notice: Only variables should be passed by reference
  modules/Vtiger/actions/TransferOwnership.php
Labels: finished

#8648 Fix notice "Undefined variable" in "OSSTimeControl" module.
  modules/OSSTimeControl/views/InRelation.php
Labels: finished

#8658 Corrected dropdown size
  public_html/layouts/basic/styles/libraries/_Bootstrap.scss
Labels: finished

#8665 Fixed notice
  app/Fields/File.php
Labels: finished

#8670 Dont convert percentage display value by currency exchange rate
  modules/Vtiger/uitypes/Percentage.php
Labels: finished

#8661 Fixed #7630
  modules/Vtiger/inventoryfields/Quantity.php
Labels: finished

#8640 Fix notice "Undefined variable" in "Notification" module.
  modules/Notification/models/Record.php
Labels: finished

#8668 Fixed quick edit events
  public_html/layouts/basic/modules/Vtiger/resources/Detail.js
Labels: finished

#8664 Fixed OSSPasswords record save
  public_html/layouts/basic/modules/OSSPasswords/resources/Edit.js
Labels: finished

#8673 Improved display number (Double and Integer) - Fixed #8620
  app/Fields/Double.php
  app/Fields/Integer.php
  modules/Vtiger/uitypes/Double.php
  modules/Vtiger/uitypes/Integer.php
  public_html/layouts/resources/validator/FieldValidator.js
Labels: finished

#8678 Fixed roundcube version in config/version.php
  config/version.php
Labels: finished

#8679 Scrutinizer - Improving comments
  app/Cache.php
Labels: finished

#8672 Fixed edit system configuration
  modules/Settings/Vtiger/models/ConfigModule.php
Labels: finished

#8655 Fixed notice in pricebooks
  modules/Products/models/Module.php
  modules/Products/models/RelationListView.php
Labels: finished

#8676 Fixed #8555
  modules/Vtiger/dashboards/MiniList.php
  public_html/layouts/basic/modules/Vtiger/resources/DashBoard.js
Labels: finished

#8659 Fix notice "Undefined index" in System – Configuration
  layouts/basic/modules/Settings/Vtiger/ConfigEditorDetail.tpl
Labels: finished

#8694 Improved conditions in QueryGenerator for field SharedOwner
  app/QueryField/SharedOwnerField.php
Labels: finished

#8695 Fixed notice when save filter
  modules/CustomView/models/Record.php
Labels: finished

#8689 Fix #8474 - Multi PDF generation
  modules/Settings/LayoutEditor/models/Module.php
  modules/Vtiger/models/PDF.php
Labels: finished

#8704 Added improvement to multifilter widget
  modules/Vtiger/models/Multifilter.php
Labels: finished

#8703 SONAR: Remove this redundant jump, Remove this method "xxx" to simply…
  app/Controller/View.php
  app/Fields/Date.php
  app/Fields/DateTime.php
  app/Record.php
  app/UserPrivilegesFile.php
  modules/Import/actions/Data.php
  modules/LettersIn/LettersIn.php
  modules/LettersOut/LettersOut.php
  modules/ModComments/ModCommentsCore.php
  modules/PriceBooks/actions/RelationAjax.php
  modules/Project/Project.php
  modules/ProjectMilestone/ProjectMilestone.php
  modules/ProjectTask/ProjectTask.php
  modules/SMSNotifier/SMSNotifier.php
  modules/Services/Services.php
  modules/Settings/Inventory/models/Record.php
  modules/Settings/Vtiger/views/List.php
  modules/Settings/Workflows/models/Record.php
  modules/Users/Users.php
  modules/Users/models/Privileges.php
Labels: finished

#8696 Fixed currency save in settings
  modules/Settings/Currency/models/Record.php
Labels: finished

#8709 A small change in the system configuration
  layouts/basic/modules/Settings/Vtiger/ConfigEditorDetail.tpl
Labels: finished

#8693 Corrected profile checkboxes' logic (selecting permission to create)
  public_html/layouts/basic/modules/Settings/Profiles/resources/Profiles.js
Labels: finished

#8717 Added minor improvements in model "RecordPopover"
  modules/Calendar/models/RecordPopover.php
  modules/OSSTimeControl/models/RecordPopover.php
  modules/Vtiger/models/RecordPopover.php
Labels: finished

#8725 Fixed load markers into map
  public_html/layouts/basic/modules/OpenStreetMap/resources/Map.js
Labels: finished

#8721 Removed profiles and pdfs
  app/Db/Fixer.php
  app/Field.php
  install/install_schema/data.sql
  install/install_schema/scheme.sql
  tests/Settings/ModuleManager.php
  vtlib/Vtiger/FieldBasic.php
  vtlib/Vtiger/Profile.php
Labels: finished

#8719 Improved message when dav is disabled
  app/Exceptions/NoPermittedToApi.php
  dav.php
Labels: finished

#8724 UiTypes sample value generation
  modules/Vtiger/uitypes/Currency.php
  modules/Vtiger/uitypes/Date.php
  modules/Vtiger/uitypes/Datetime.php
  modules/Vtiger/uitypes/Double.php
  modules/Vtiger/uitypes/Integer.php
  modules/Vtiger/uitypes/Time.php
Labels: AmendmentsRequired

#8714 Updated dependencies security validation API usage
  app/SystemWarnings/Security/Dependencies.php
Labels: finished
