Repository YetiForceCompany/YetiForceCRM, pull requests merged in 2019-01, with the labels that each got.

#9007 Added minor improvements
  app/Encryption.php
  modules/ModComments/models/Record.php
  modules/ModTracker/models/Field.php
Labels: finished

#9005 Improved visibility icons
  public_html/layouts/basic/modules/Settings/LayoutEditor/resources/LayoutEditor.js
  public_html/layouts/basic/modules/Vtiger/resources/RelatedList.js
Labels: finished

#9004 Fixed notice in action "ChangesReviewedOn"
  modules/ModTracker/actions/ChangesReviewedOn.php
Labels: finished

#9003 Fixed removing OutsourcedProducts from tree
  public_html/layouts/resources/libraries/jstree.edit.js
Labels: finished

#9000 Fixed preview list with last imported records
  layouts/basic/modules/Import/ImportPreview.tpl
Labels: finished

#8984 RoundCube language fix
  modules/OSSMail/views/Index.php
Labels: VerificationRequired, finished

#9006 Fixed #8982
  modules/Settings/LayoutEditor/actions/SaveAjax.php
Labels: AmendmentsRequired, finished

#9011 gantt-elastic 0.6.3 update
  package.json
  public_html/layouts/basic/modules/Project/resources/Gantt.js
Labels: finished

#9013 Improved reading unit price for Products or Services in inventory
  modules/Products/models/Record.php
  public_html/layouts/basic/modules/Vtiger/resources/Inventory.js
Labels: finished

#9014 yetiforcepdf version update 0.1.1
  composer.json
Labels: finished

#9018 Improved security when edit config file for system
  modules/Settings/Vtiger/actions/ConfigEditorSaveAjax.php
  modules/Settings/Vtiger/models/ConfigModule.php
Labels: finished

#9020 gantt minor visual improvements
  modules/Project/models/Gantt.php
  public_html/layouts/basic/modules/Project/resources/Gantt.js
Labels: finished

#9032 gantt columns text alignment improvements, gantt label icons added
  languages/pl-PL/Project.json
  modules/Project/models/Gantt.php
  public_html/layouts/basic/modules/Project/resources/Gantt.js
Labels: finished

#9034 gant height calculation bugfix
  public_html/layouts/basic/modules/Project/resources/Gantt.js
Labels: finished

#9045 Fixed notification bug - assigned users (414689)
  modules/Notification/models/Record.php
Labels: finished

#9044 YetiForcePDF updated to 0.1.3, barcode implementation
  app/TextParser/ProductsTableLongVTwoLang.php
  app/TextParser/ProductsTableLongVersion.php
  app/TextParser/ProductsTableNew.php
  app/TextParser/ProductsTableRelatedModule.php
  app/TextParser/ProductsTableShortVersion.php
  composer.json
Labels: finished

#9040 Fixed #9038 - create inventory module
  modules/Settings/ModuleManager/models/Module.php
  vtlib/Vtiger/ModuleBasic.php
Labels: finished

#9041 Fixed import inventory module
  vtlib/Vtiger/PackageImport.php
Labels: finished

#9036 Fixed calendar event on activities modal
  public_html/layouts/basic/modules/Calendar/resources/Extended/CalendarView.js
Labels: finished

#9047 Improved encoding data from JSON
  layouts/basic/modules/Users/Edit/Field/Base.tpl
  layouts/basic/modules/Users/Edit/Field/Boolean.tpl
  layouts/basic/modules/Users/Edit/Field/Picklist.tpl
  layouts/basic/modules/Users/Export.tpl
  layouts/basic/modules/Users/PreferenceDetailViewHeader.tpl
  layouts/basic/modules/Users/UserViewHeader.tpl
  layouts/basic/modules/Vtiger/AddCommentForm.tpl
  layouts/basic/modules/Vtiger/AdvanceFilter.tpl
  layouts/basic/modules/Vtiger/AdvanceFilterCondition.tpl
  layouts/basic/modules/Vtiger/AdvanceSearch.tpl
  layouts/basic/modules/Vtiger/DetailViewHeader.tpl
  layouts/basic/modules/Vtiger/Edit/Field/Base.tpl
  layouts/basic/modules/Vtiger/Edit/Field/Country.tpl
  layouts/basic/modules/Vtiger/Edit/Field/DateTime.tpl
  layouts/basic/modules/Vtiger/Edit/Field/MultiOwner.tpl
  layouts/basic/modules/Vtiger/Edit/Field/Reference.tpl
  layouts/basic/modules/Vtiger/Edit/Field/SharedOwner.tpl
  layouts/basic/modules/Vtiger/Edit/Field/Theme.tpl
  layouts/basic/modules/Vtiger/Edit/Field/Tree.tpl
  layouts/basic/modules/Vtiger/Export.tpl
  layouts/basic/modules/Vtiger/MassEditForm.tpl
  layouts/basic/modules/Vtiger/SendSMSForm.tpl
  layouts/basic/modules/Vtiger/UnifiedSearchResults.tpl
Labels: finished

#9049 ListViewHeader.tpl
  layouts/basic/modules/Users/UserViewHeader.tpl
Labels: finished

#9050 Improved templates
  layouts/basic/modules/Users/Export.tpl
  layouts/basic/modules/Vtiger/AddCommentForm.tpl
  layouts/basic/modules/Vtiger/AdvanceFilterCondition.tpl
  layouts/basic/modules/Vtiger/Export.tpl
  layouts/basic/modules/Vtiger/SendSMSForm.tpl
Labels: finished

#9054 Improved download attachments from email
  layouts/basic/modules/OSSMailView/sview.tpl
Labels: finished

#9057 missing milestone tasks bugfix
  modules/Project/models/Gantt.php
Labels: finished

#9056 gantt-elastic update 0.6.20
  package.json
Labels: finished

#9064 Improved valid data in module "MailSmtp"
  layouts/basic/modules/Settings/MailSmtp/Edit.tpl
  modules/Settings/MailSmtp/actions/SaveAjax.php
  public_html/layouts/basic/modules/Settings/MailSmtp/resources/Edit.js
Labels: finished

#9071 correcting invoice text parser
  app/TextParser/ProductsTableCorrectingBefore.php
Labels: finished

#9075 Remove unused language pharses
  languages/pl-PL/CallHistory.json
  languages/pl-PL/Campaigns.json
  languages/pl-PL/IStorages.json
  languages/pl-PL/KnowledgeBase.json
  languages/pl-PL/ModTracker.json
  languages/pl-PL/Notification.json
  languages/pl-PL/Products.json
  languages/pl-PL/SMSNotifier.json
  languages/pl-PL/SSingleOrders.json
Labels: finished

#9076 Language improvement
  languages/pl-PL/Settings/Currency.json
  languages/pl-PL/Settings/MappedFields.json
  languages/pl-PL/Settings/PDF.json
  languages/pl-PL/Settings/_Base.json
Labels: finished

#9079 Fixed increase number of record
  app/Fields/RecordNumber.php
Labels: finished

#9078 Add templates for invoices and few improvements
  install/install_schema/data.sql
  languages/de-DE/Other/PDF.json
  languages/en-US/Other/PDF.json
  languages/es-ES/Other/PDF.json
  languages/fr-FR/Other/PDF.json
  languages/it-IT/Other/PDF.json
  languages/pl-PL/Other/PDF.json
  languages/pt-BR/Other/PDF.json
  languages/ro-RO/Other/PDF.json
  languages/ru-RU/Other/PDF.json
  languages/tr-TR/Other/PDF.json
  layouts/basic/modules/Vtiger/ExportPDF.tpl
Labels: finished

#8859 String formatting/conversion tests
  tests/Base/Z_StringFormatting.php
Labels: finished

#9082 Update language files
  languages/pl-PL/Settings/CurrencyUpdate.json
  languages/pl-PL/Settings/CustomView.json
  languages/pl-PL/_Base.json
Labels: finished

#9084 gantt-elastic update 0.6.26
  package.json
Labels: finished

#9093 Optimization - removal of the settype function
  app/Field.php
  app/Request.php
  modules/Home/models/Module.php
  modules/OSSMail/models/Mail.php
  modules/Settings/LangManagement/models/Module.php
  modules/Settings/MappedFields/models/Module.php
  modules/Users/models/Privileges.php
  modules/Vtiger/widgets/RelatedModule.php
Labels: finished

#9108 Fixed language in test
  tests/Base/G_Cron.php
Labels: finished

#9109 Fixed loading completions in comments tab
  public_html/layouts/basic/modules/Vtiger/resources/Detail.js
Labels: finished

#9112 Improved installation styles
  install/tpl/InstallPreProcess.tpl
  public_html/install/tpl/resources/css/style.css
Labels: finished

#9118 [IT225] Fixed pagination
  layouts/basic/modules/Settings/LoginHistory/ListViewHeader.tpl
Labels: finished

#9117 [IT223] Adding a relations to the contractor
  install/install_schema/data.sql
Labels: finished

#9116 Fixed showing hidden field in activities
  layouts/basic/modules/Vtiger/RecentActivitiesInventory.tpl
Labels: finished

#9113 [IT231] Fixed browsinghistory
  modules/Vtiger/helpers/BrowsingHistory.php
Labels: finished

#9119 Added flag to installation language
  install/tpl/Step1.tpl
Labels: finished

#9125 Fixed #9095
  layouts/basic/modules/Vtiger/Edit/InventoryItem.tpl
Labels: finished

#9122 Fix: modal bug in layout editor
  public_html/layouts/basic/modules/Settings/LayoutEditor/resources/LayoutEditor.js
Labels: finished

#9127 Removal of unnecessary relations
  install/install_schema/data.sql
Labels: finished

#9121 Fix: modal close bug [IT210]
  public_html/layouts/basic/modules/Calendar/resources/ActivityStateModal.js
Labels: finished

#9136 Compiled styles
  public_html/layouts/basic/styles/Main.css
  public_html/layouts/basic/styles/Main.css.map
Labels: finished

#9142 load fonts for wysiwyg editors from file
  public_html/layouts/basic/modules/Settings/PDF/resources/Edit.js
  public_html/layouts/resources/fonts/fonts.json
Labels: finished

#9144 YetiForcePDF update 0.1.5
  composer.json
Labels: finished

#9147 Noto Sans changed to DejaVu Sans inside pdf templates
  install/install_schema/data.sql
Labels: finished

#9149 siteUrl instead of plain text url
  public_html/layouts/basic/modules/Settings/PDF/resources/Edit.js
Labels: finished

#9150 Added minor improvements in comments
  public_html/layouts/basic/modules/Vtiger/resources/Detail.js
Labels: finished

#9158 Corrected fields' sizes in widgets
  layouts/basic/modules/Vtiger/List/Field/Base.tpl
  layouts/basic/modules/Vtiger/List/Field/PickList.tpl
  layouts/basic/modules/Vtiger/dashboards/ChartFilterHeader.tpl
  layouts/basic/modules/Vtiger/dashboards/MiniList.tpl
Labels: finished

#9156 Corrected viewport height bugs with different footer configurations
  public_html/layouts/basic/styles/_Variables.scss
  public_html/layouts/basic/styles/components/_Global.scss
  public_html/layouts/basic/styles/layout/_Base.scss
  public_html/layouts/basic/styles/layout/_Header.scss
  public_html/layouts/basic/styles/pages/_Calendar.scss
Labels: finished

#9165 Fixed notice in completion owners' search
  modules/Vtiger/actions/Search.php
Labels: finished

#9173 Added styles correction for setting inventory column width
  layouts/basic/modules/Settings/LayoutEditor/Index.tpl
  layouts/basic/modules/Vtiger/Edit/Inventory.tpl
  layouts/basic/modules/Vtiger/Edit/InventoryItem.tpl
  public_html/layouts/basic/styles/components/_Utilities.scss
  public_html/layouts/basic/styles/pages/_Edit.scss
Labels: finished

#9169 YetiForcePDF update 0.1.7
  composer.json
Labels: finished

#9187 Added Drag'n'Drop to calendar in reservations and time control [IT208]
  public_html/layouts/resources/Calendar.js
Labels: finished

#9184 Improved edit comment buttons
  layouts/basic/modules/Vtiger/CommentsList.tpl
  layouts/basic/modules/Vtiger/RecentComments.tpl
  layouts/basic/modules/Vtiger/ShowAllComments.tpl
Labels: finished

#9176 gantt-elastic update 0.7.0
  package.json
Labels: finished

#9185 Added validation to field mask [IT224]
  layouts/basic/modules/Settings/LayoutEditor/EditField.tpl
Labels: finished

#9199 Could not find template bugfix [IT275]
  layouts/basic/modules/Project/gantt/GanttContents.tpl
Labels: finished

#9197 Fixed twelve hour clockpicker in modal by changing autoclosing to true
  public_html/layouts/resources/app.js
Labels: finished

#9198 [IT240] Fixed "Data too long for column"
  install/install_schema/scheme.sql
Labels: finished

#9200 Revert "backdrop not covering actions menu bugfix [IT114]"
  layouts/basic/modules/Vtiger/BodyHeader.tpl
  public_html/layouts/basic/styles/_Style.scss
  public_html/layouts/basic/styles/libraries/_Bootstrap.scss
Labels: finished

#9212 Adding a missing comment
  modules/Import/helpers/Utils.php
Labels: finished

#9226 Added minor improvements in encryption
  app/Encryption.php
  config/ConfigTemplates.php
  modules/Settings/Password/actions/Save.php
Labels: finished

#9227 Fixed Delete Custom Block button
  layouts/basic/modules/Settings/WidgetsManagement/Configuration.tpl
Labels: finished

#9230 Improved link in chart filter
  modules/Vtiger/models/ChartFilter.php
Labels: finished

#9233 Fixed save users
  modules/Vtiger/uitypes/MultiDependField.php
Labels: finished

#9232 Added a few fixes [IT232]
  vtlib/Vtiger/PackageImport.php
Labels: finished

#9244 Improved reading data from configuration
  modules/Settings/Dav/views/Keys.php
Labels: finished

#9252 Improved popover header [ IT292]
  layouts/basic/modules/Vtiger/RecordPopover.tpl
  public_html/layouts/basic/styles/components/_Global.scss
Labels: finished

#9250 The display of items in the calendar event title has been fixed [IT179]
  public_html/layouts/resources/Calendar.js
Labels: finished

#9249 [289] The MultiReferenceValue field has been fixed
  modules/Settings/LayoutEditor/models/Module.php
  modules/Vtiger/models/Block.php
  modules/Vtiger/models/Module.php
  modules/Vtiger/uitypes/MultiReferenceValue.php
Labels: finished

#9241 Improved gantt filters' select layout and RWD [IT201]
  layouts/basic/modules/Project/gantt/GanttAll.tpl
Labels: finished

#9253 Fixed #9243
  layouts/basic/modules/Calendar/Extended/CalendarView.tpl
  layouts/basic/modules/Calendar/Standard/CalendarView.tpl
  layouts/basic/modules/OSSTimeControl/CalendarView.tpl
  layouts/basic/modules/Reservations/CalendarView.tpl
  layouts/basic/modules/Vtiger/dashboards/CalendarContents.tpl
  public_html/layouts/basic/modules/Vtiger/resources/dashboards/Widget.js
  public_html/layouts/resources/Calendar.js
Labels: finished

#9235 Fixed displaying breadcrumb's item without url [IT280]
  layouts/basic/modules/Vtiger/BreadCrumbs.tpl
Labels: finished

#9239 Fixed the half-transparent loader when Gantt is loading [ IT168]
  public_html/layouts/basic/modules/Project/resources/Gantt.js
  public_html/layouts/resources/ProgressIndicator.js
Labels: finished

#9183 add calendar event in 12h user format bugfix [IT64]
  install/install_schema/data.sql
Labels: VerificationRequired

#9175 text parser currency summary width fixed
  app/TextParser/TableCurrencySummary.php
Labels: finished

#9234 Improved reading data from request [IT246]
  modules/Settings/AutomaticAssignment/actions/SaveAjax.php
Labels: finished

#9257 Removed "Script" as type of menu
  layouts/basic/modules/Settings/Menu/types/Script.tpl
  layouts/basic/modules/Vtiger/menu/Script.tpl
  modules/Settings/Menu/models/Module.php
Labels: finished

#9264 [IT308] - Unit test amendment - part 1
  tests/Base/Z_Authy2FA.php
  tests/Init/A_LanguageFiles.php
  tests/Settings/OSSMail.php
Labels: finished

#9263 Fixed related list in campaigns [IT300]
  layouts/basic/modules/Campaigns/RelatedList.tpl
Labels: finished

#9262 Added a few fixes
  languages/en-US/Settings/Menu.json
  layouts/basic/modules/Settings/MappedFields/Step1.tpl
  modules/OSSTimeControl/models/Calendar.php
  modules/Reservations/models/Calendar.php
  modules/Settings/MappedFields/actions/SaveAjax.php
  modules/Settings/PublicHoliday/views/Configuration.php
  modules/Vtiger/uitypes/MultiEmail.php
  modules/com_vtiger_workflow/VTTaskManager.php
Labels: finished

#9256 Added list_fields_name to popover record [IT242]
  modules/Vtiger/models/RecordPopover.php
Labels: finished

#9268 Added relation between SQuoteEnquiries and Leads
  install/install_schema/data.sql
  install/install_schema/scheme.sql
Labels: finished

#9269 Updated compiled files with much lighter Main.min.css [IT313]
  public_html/install/tpl/resources/Index.min.js
  public_html/install/tpl/resources/Index.min.js.map
  public_html/layouts/basic/modules/Calendar/resources/ActivityStateModal.min.js
  public_html/layouts/basic/modules/Calendar/resources/ActivityStateModal.min.js.map
  public_html/layouts/basic/modules/Calendar/resources/Extended/CalendarView.min.js
  public_html/layouts/basic/modules/Calendar/resources/Extended/CalendarView.min.js.map
  public_html/layouts/basic/modules/Calendar/resources/List.min.js
  public_html/layouts/basic/modules/Calendar/resources/List.min.js.map
  public_html/layouts/basic/modules/Chat/resources/Chat.min.js
  public_html/layouts/basic/modules/Chat/resources/Chat.min.js.map
  public_html/layouts/basic/modules/Import/resources/Import.min.js
  public_html/layouts/basic/modules/Import/resources/Import.min.js.map
  public_html/layouts/basic/modules/Project/resources/Gantt.min.js
  public_html/layouts/basic/modules/Project/resources/Gantt.min.js.map
  public_html/layouts/basic/modules/Settings/MappedFields/resources/Edit1.min.js
  public_html/layouts/basic/modules/Settings/MappedFields/resources/Edit1.min.js.map
  public_html/layouts/basic/modules/Settings/MappedFields/resources/Edit3.min.js
  public_html/layouts/basic/modules/Settings/MappedFields/resources/Edit3.min.js.map
  public_html/layouts/basic/modules/Settings/OSSMailScanner/resources/Index.min.js
  public_html/layouts/basic/modules/Settings/OSSMailScanner/resources/Index.min.js.map
  public_html/layouts/basic/modules/Settings/PDF/resources/Edit.min.js
  public_html/layouts/basic/modules/Settings/PDF/resources/Edit.min.js.map
  public_html/layouts/basic/modules/Settings/SalesProcesses/resources/Index.min.js
  public_html/layouts/basic/modules/Settings/SalesProcesses/resources/Index.min.js.map
  public_html/layouts/basic/modules/Settings/TimeControlProcesses/resources/Index.min.js
  public_html/layouts/basic/modules/Settings/TimeControlProcesses/resources/Index.min.js.map
  public_html/layouts/basic/modules/Settings/TreesManager/resources/Edit.min.js
  public_html/layouts/basic/modules/Settings/TreesManager/resources/Edit.min.js.map
  public_html/layouts/basic/modules/Settings/WebserviceUsers/resources/Edit.min.js
  public_html/layouts/basic/modules/Settings/WebserviceUsers/resources/Edit.min.js.map
  public_html/layouts/basic/modules/Users/resources/List.min.js
  public_html/layouts/basic/modules/Users/resources/List.min.js.map
  public_html/layouts/basic/modules/Vtiger/resources/AdvanceFilterEx.min.js
  public_html/layouts/basic/modules/Vtiger/resources/AdvanceFilterEx.min.js.map
  public_html/layouts/basic/modules/Vtiger/resources/DashBoard.min.js
  public_html/layouts/basic/modules/Vtiger/resources/DashBoard.min.js.map
  public_html/layouts/basic/modules/Vtiger/resources/Detail.min.js
  public_html/layouts/basic/modules/Vtiger/resources/Detail.min.js.map
  public_html/layouts/basic/modules/Vtiger/resources/ListSearch.min.js
  public_html/layouts/basic/modules/Vtiger/resources/ListSearch.min.js.map
  public_html/layouts/basic/modules/Vtiger/resources/dashboards/Widget.min.js
  public_html/layouts/basic/modules/Vtiger/resources/dashboards/Widget.min.js.map
  public_html/layouts/basic/styles/Main.css
  public_html/layouts/basic/styles/Main.css.map
  public_html/layouts/basic/styles/Main.min.css
  public_html/layouts/basic/styles/pages/_List.scss
  public_html/layouts/resources/Calendar.min.js
  public_html/layouts/resources/Calendar.min.js.map
  public_html/layouts/resources/Fields.min.js
  public_html/layouts/resources/Fields.min.js.map
  public_html/layouts/resources/ProgressIndicator.min.js
  public_html/layouts/resources/ProgressIndicator.min.js.map
  public_html/layouts/resources/app.min.js
  public_html/layouts/resources/app.min.js.map
Labels: finished

#9277 Fixed clockpicker pm/am [IT241]
  public_html/layouts/resources/app.js
Labels: finished

#9278 Improved configuration calendar
  layouts/basic/modules/Settings/Calendar/UserColors.tpl
  modules/Settings/Calendar/actions/SaveAjax.php
  modules/Settings/Calendar/models/Module.php
Labels: finished

#9275 Prevented closing modal before ckeditor is loaded by adding progress indicator [IT314]
  public_html/layouts/resources/Fields.js
Labels: finished

#9279 Fixed mask validation in default value field (LayoutEditor.js) [IT224]
  layouts/basic/modules/Settings/LayoutEditor/EditField.tpl
  layouts/basic/modules/Vtiger/Edit/Field/Base.tpl
  public_html/layouts/basic/modules/Settings/LayoutEditor/resources/LayoutEditor.js
Labels: finished

#9284 Fixed language validator
  app/Validator.php
Labels: finished
