Repository YetiForceCompany/YetiForceCRM, pull requests merged in 2019-03, with the labels that each got.

#9714 Added maximumLength to fields estimated_work_time
  install/install_schema/data.sql
Labels: finished

#9717 Fixed bug in SummationByMonths widget
  layouts/basic/modules/FInvoice/dashboards/SummationByMonths.tpl
Labels: finished

#9719 Added module name to Exceptions
  modules/Vtiger/uitypes/Boolean.php
  modules/Vtiger/uitypes/CategoryMultipicklist.php
  modules/Vtiger/uitypes/CompanySelect.php
  modules/Vtiger/uitypes/Currency.php
  modules/Vtiger/uitypes/CurrencyList.php
  modules/Vtiger/uitypes/Date.php
  modules/Vtiger/uitypes/Double.php
  modules/Vtiger/uitypes/Email.php
  modules/Vtiger/uitypes/FileLocationType.php
  modules/Vtiger/uitypes/Integer.php
  modules/Vtiger/uitypes/InventoryLimit.php
  modules/Vtiger/uitypes/Languages.php
  modules/Vtiger/uitypes/MultiDependField.php
  modules/Vtiger/uitypes/MultiEmail.php
  modules/Vtiger/uitypes/MultiImage.php
  modules/Vtiger/uitypes/Multiowner.php
  modules/Vtiger/uitypes/Multipicklist.php
  modules/Vtiger/uitypes/Owner.php
  modules/Vtiger/uitypes/Smtp.php
  modules/Vtiger/uitypes/Taxes.php
  modules/Vtiger/uitypes/Text.php
  modules/Vtiger/uitypes/Theme.php
  modules/Vtiger/uitypes/Time.php
  modules/Vtiger/uitypes/Tree.php
  modules/Vtiger/uitypes/Twitter.php
  modules/Vtiger/uitypes/Url.php
  modules/Vtiger/uitypes/UserReference.php
  modules/Vtiger/uitypes/UserRole.php
Labels: finished

#9704 Changed name file [IT515]
  layouts/basic/modules/OSSPasswords/Detail/BlockView.tpl
Labels: finished

#9702 Fixed #9688
  public_html/layouts/basic/modules/Calendar/resources/Extended/CalendarView.js
  public_html/layouts/resources/Calendar.js
Labels: finished

#9699 Fixed "Call to member function regenerateId() on null"
  app/Session.php
Labels: finished

#9679 Improvement utils [IT502]
  app/Utils/ConfReport.php
Labels: finished

#9677 Fixed bug: Fields owner
  app/Fields/Owner.php
Labels: finished

#9721 Added module name to Exceptions
  languages/en-US/Other/Exceptions.json
  modules/Vtiger/uitypes/MultiImage.php
  modules/Vtiger/uitypes/Percentage.php
Labels: finished

#9676 Fixed #9626
  app/TextParser.php
Labels: finished

#9734 Corrected translation in Exception
  languages/en-US/Other/Exceptions.json
Labels: finished

#9735 YetiForcePDF update 0.1.14
  composer.json
Labels: finished

#9745 Fixed #9712
  layouts/basic/modules/Settings/Profiles/EditView.tpl
Labels: finished

#9608 Fixed TextParser on ProductsTableLongVTwoLang, ProductsTableLongVersi…
  app/TextParser/ProductsTableLongVTwoLang.php
  app/TextParser/ProductsTableLongVersion.php
  app/TextParser/ProductsTableShortVersion.php
Labels: finished

#9668 Improvements in user module
  modules/Users/Users.php
Labels: finished

#9753 💫 router mode from window global (because it is not available yet in vuex)
  src/router/index.js
Labels: finished

#9759 Correction php cs
  cron/SocialGet.php
  modules/Leads/models/Record.php
Labels: finished

#9739 Removal of unnecessary logs
  modules/Vtiger/dashboards/Rss.php
Labels: finished

#9741 Fixed notice errors
  modules/Import/readers/XmlReader.php
Labels: finished

#9754 [IT517] Change in the calculation of project progress
  modules/Project/handlers/ProjectHandler.php
  modules/ProjectTask/handlers/ProjectTaskHandler.php
Labels: finished

#9760 Fixed adding files contain "&" in filename
  modules/Documents/models/Record.php
Labels: finished

#9693 [IT514] Fixed button more
  app/TextParser.php
  layouts/basic/modules/Vtiger/Detail/Widget/WYSIWYG.tpl
Labels: finished

#9701 [IT431] rebuild AdvancedPermission DetailView
  layouts/basic/modules/Settings/AdvancedPermission/DetailView.tpl
Labels: finished

#9670 Fixed #9622
  modules/Vtiger/models/Record.php
Labels: finished

#9526 Added new autocomplete values to user and password fields, cleaned code
  layouts/basic/modules/Users/Edit/Field/Base.tpl
  layouts/basic/modules/Vtiger/Edit/Field/Password.tpl
Labels: finished

#9690 Fixed #9667
  modules/Vtiger/views/BasicAjax.php
  public_html/layouts/resources/Fields.js
Labels: finished

#9733 Added module name to Exceptions
  modules/Vtiger/inventoryfields/Basic.php
  modules/Vtiger/uitypes/Phone.php
  modules/Vtiger/uitypes/Recurrence.php
  modules/Vtiger/uitypes/Reference.php
  modules/Vtiger/uitypes/Reminder.php
  modules/Vtiger/uitypes/SharedOwner.php
Labels: finished

#9742 Fixed import xml [IT525]
  modules/Import/readers/XmlReader.php
Labels: finished

#9782 Conversion PearDatabase to yii [IT529]
  modules/Contacts/Contacts.php
Labels: AmendmentsRequired

#9796 Added translation in TextParser [IT475]
  languages/en-US/Other/TextParser.json
Labels: finished

#9770 Fixed "Notice: Undefined index"
  modules/Settings/ModuleManager/views/ModuleImport.php
Labels: finished

#9776 CardDav - Fixed "Warning: Illegal offset type in isset or empty"
  modules/API/models/CardDAV.php
Labels: finished

#9805 💫 Added source-maps to build for debugging in VSC
  quasar.conf.js
Labels: finished

#9792 Conversion PearDatabase to yii [IT529]
  modules/Products/Products.php
Labels: finished

#9791 Conversion PearDatabase to yii [IT529]
  modules/Leads/Leads.php
Labels: finished

#9790 Conversion PearDatabase to yii [IT529]
  modules/HelpDesk/HelpDesk.php
Labels: finished

#9781 Conversion PearDatabase to yii [IT529]
  modules/Competition/Competition.php
Labels: finished

#9778 #9578 fix for wrong tax format
  public_html/layouts/basic/modules/Vtiger/resources/Inventory.js
Labels: finished

#9775 [IT530] fix uncheck generatedtype checkbox in edit field
  layouts/basic/modules/Settings/LayoutEditor/EditField.tpl
Labels: finished

#9773 [IT531] fix copy field name in LayoutEditor
  public_html/layouts/basic/modules/Settings/LayoutEditor/resources/LayoutEditor.js
Labels: finished

#9772 Conversion PearDatabase to yii [IT529]
  include/Webservices/Utils.php
Labels: finished

#9767 Conversion PearDatabase to yii [IT529]
  include/Webservices/ConvertLead.php
Labels: finished

#9771 Improved csv import [IT534]
  layouts/basic/modules/Import/Import_Step4.tpl
  modules/Import/readers/XmlReader.php
Labels: finished

#9799 #9746 add improvment to cache getByType value and reformat code
  app/Request.php
Labels: finished

#9543 Added popove to owner type field and sharing persons type field [IT451]
  modules/Vtiger/uitypes/Owner.php
  modules/Vtiger/uitypes/SharedOwner.php
Labels: finished

#9672 Improved validation form when add chart from filter [IT483]
  layouts/basic/modules/Vtiger/dashboards/ChartFilter.tpl
Labels: finished

#9678 Add fix for ListViewLeftSide.tpl when array doesn't exist
  layouts/basic/modules/Documents/ListViewLeftSide.tpl
  layouts/basic/modules/Vtiger/ListViewLeftSide.tpl
  modules/OpenStreetMap/models/Module.php
Labels: finished

#9810 Corrected "Conversion PearDatabase to yii"
  include/Webservices/ConvertLead.php
  include/Webservices/Utils.php
Labels: finished

#9809 YetiForcePDF update v0.1.17
  composer.json
Labels: finished

#9808 Fixed getting phone details [IT535]
  layouts/basic/modules/Vtiger/Edit/Field/Phone.tpl
Labels: finished

#9803 [IT250] Add fix for show message
  modules/Vtiger/actions/TransferOwnership.php
  public_html/layouts/basic/modules/Vtiger/resources/List.js
Labels: finished

#9811 Improved ignore system warnings
  layouts/basic/modules/Settings/Vtiger/SystemWarningsList.tpl
Labels: finished

#9801 Conversion PearDatabase to yii [IT529]
  modules/Assets/Assets.php
Labels: finished

#9798 Conversion PearDatabase to yii [IT529]
  modules/Vendors/Vendors.php
Labels: finished

#9797 Conversion PearDatabase to yii [IT529]
  modules/Services/Services.php
Labels: finished

#9795 Conversion PearDatabase to yii [IT529]
  modules/ServiceContracts/ServiceContracts.php
Labels: finished

#9818 Improved security when import records from CSV
  modules/Import/readers/CSVReader.php
Labels: finished

#9813 YetiForcePDF update v0.1.18
  composer.json
Labels: finished

#9820 Improved formatToDisplay in Double [IT538]
  app/Fields/Double.php
Labels: finished

#9822 Sensiolabs: Unused method, property, variable or parameter
  modules/Vtiger/uitypes/Base.php
Labels: finished

#9530 [IT436] Addition of parameters validation for the module "Settings::W…
  layouts/basic/modules/Vtiger/Detail/Widget/ActivitiesConfig.tpl
  layouts/basic/modules/Vtiger/Detail/Widget/BasicConfig.tpl
  layouts/basic/modules/Vtiger/Detail/Widget/CommentsConfig.tpl
  layouts/basic/modules/Vtiger/Detail/Widget/DetailViewConfig.tpl
  layouts/basic/modules/Vtiger/Detail/Widget/EmailListConfig.tpl
  layouts/basic/modules/Vtiger/Detail/Widget/FastEditConfig.tpl
  layouts/basic/modules/Vtiger/Detail/Widget/HistoryRelationConfig.tpl
  layouts/basic/modules/Vtiger/Detail/Widget/ProductsServicesConfig.tpl
  layouts/basic/modules/Vtiger/Detail/Widget/RelatedModuleConfig.tpl
  layouts/basic/modules/Vtiger/Detail/Widget/SummaryCategoryConfig.tpl
  layouts/basic/modules/Vtiger/Detail/Widget/WYSIWYGConfig.tpl
  modules/Settings/Widgets/actions/SaveAjax.php
  modules/Settings/Widgets/views/Widget.php
  public_html/layouts/basic/modules/Settings/Widgets/resources/Widgets.js
Labels: finished

#9823 Corrected new bootbox file path
  app/Controller/View.php
Labels: finished

#9827 Improved method to save data into column which is not field in the sy…
  modules/Vtiger/models/Record.php
Labels: finished

#9826 Fixed skipping record in import
  layouts/basic/modules/Import/Import_Step3.tpl
Labels: finished

#9824 Changed translation
  languages/en-US/Install.json
Labels: finished

#9829 Improved display address URL in "YetiForce Status"
  layouts/basic/modules/Settings/YetiForce/Status.tpl
Labels: finished

#9841 YetiForcePDF update v0.1.20, watermark_text as text
  composer.json
  install/install_schema/scheme.sql
Labels: finished

#9843 Fixed saving records with inventory when removed the first row
  layouts/basic/modules/Vtiger/Edit/Inventory.tpl
  layouts/basic/modules/Vtiger/inventoryfields/EditViewCurrency.tpl
  layouts/basic/modules/Vtiger/inventoryfields/EditViewDiscountMode.tpl
  layouts/basic/modules/Vtiger/inventoryfields/EditViewTaxMode.tpl
  public_html/layouts/basic/modules/Vtiger/resources/Inventory.js
Labels: finished

#9851 Corrected translation in registration offline
  languages/en-US/Settings/YetiForce.json
Labels: finished

#9695 Added new upcoming project tasks widget [IT508]
  app/Fields/Picklist.php
  install/install_schema/data.sql
  install/install_schema/scheme.sql
  languages/en-US/ProjectTask.json
  languages/en-US/_Base.json
  layouts/basic/modules/ProjectTask/dashboards/CompletedProjectTasks.tpl
  layouts/basic/modules/ProjectTask/dashboards/CompletedProjectTasksContents.tpl
  layouts/basic/modules/ProjectTask/dashboards/UpcomingProjectTasks.tpl
  layouts/basic/modules/ProjectTask/dashboards/UpcomingProjectTasksContents.tpl
  layouts/basic/modules/Settings/LangManagement/Edit.tpl
  modules/ProjectTask/dashboards/CompletedProjectTasks.php
  modules/ProjectTask/dashboards/UpcomingProjectTasks.php
  modules/ProjectTask/models/Module.php
  modules/Settings/Picklist/models/Module.php
  modules/Settings/WidgetsManagement/models/Module.php
  public_html/layouts/basic/modules/Vtiger/resources/dashboards/Widget.js
Labels: finished

#9846 Conversion PearDatabase to yii iCalLastImport
  modules/Calendar/ICalLastImport.php
  modules/Calendar/models/Module.php
  modules/Calendar/views/Import.php
Labels: finished

#9715 [IT495] Improving workflow import
  languages/en-US/Other/Exceptions.json
  languages/en-US/Settings/Workflows.json
  layouts/basic/modules/Settings/Workflows/Import.tpl
  modules/Settings/ModuleManager/actions/Basic.php
  modules/Settings/Workflows/models/Module.php
Labels: finished

#9844 Conversion PearDatabase to yii CRMEntity
  include/CRMEntity.php
  modules/Calendar/Calendar.php
  modules/ModComments/ModCommentsCore.php
  modules/Vtiger/CRMEntity.php
Labels: finished

#9850 💫 Setting translation module moved to routing
  src/boot/i18n.js
  src/layouts/Users/Login.vue
  src/router/routes.js
Labels: finished

#9832 Improved display URL in RSS
  layouts/basic/modules/Vtiger/dashboards/RssContents.tpl
Labels: finished

#9842 Conversion PearDatabase to yii [IT529]
  modules/OSSPasswords/actions/SaveAjax.php
Labels: finished

#9705 Gantt improvements
  languages/en-US/_Base.json
  modules/Project/models/Gantt.php
  public_html/layouts/basic/modules/Project/resources/Gantt.js
Labels: finished

#9853 Improved display "default_host" in configuration roundcube
  layouts/basic/modules/Settings/OSSMail/Index.tpl
  modules/OSSMail/ConfigTemplate.php
Labels: finished

#9854 Conversion PearDatabase to yii OSSPasswords_Record_Model
  modules/OSSPasswords/models/Record.php
Labels: ✔ finished

#9849 Conversion PearDatabase to yii Leads_Module_Model
  modules/Leads/models/Module.php
Labels: ✔ finished

#9855 Conversion PearDatabase to yii Products_Record_Model
  modules/Products/models/Record.php
Labels: ✔ finished

#9862 💫Modified css-loader config for better module class names
  quasar.conf.js
Labels: ✔ finished

#9868 Conversion PearDatabase to yii Vtiger_Util_Helper
  modules/Vtiger/helpers/Util.php
Labels: ✔ finished

#9867 Conversion PearDatabase to yii Vtiger_ShortURL_Helper
  modules/Vtiger/helpers/ShortURL.php
Labels: ✔ finished

#9864 Corrected translation and Added function that retrieves the last error of checking in Companies
  app/YetiForce/Register.php
  languages/en-US/Other/Exceptions.json
  languages/en-US/Settings/Companies.json
  layouts/basic/modules/Settings/Companies/EditView.tpl
  layouts/basic/modules/Settings/Companies/ListViewHeader.tpl
  layouts/basic/modules/Settings/YetiForce/RegistrationOnlineModal.tpl
Labels: ✔ finished

#9869 Conversion PearDatabase to yii Vtiger_Record_Model
  modules/Vtiger/models/Record.php
Labels: ✔ finished

#9865 Delete Settings_Vtiger_Systems_Model
  modules/Settings/Vtiger/models/Systems.php
Labels: ✔ finished

#9875 Added margin in icons
  layouts/basic/modules/Settings/LangManagement/LangList.tpl
Labels: ✔ finished

#9876 Remove unused getCurrencySymbol from Vtiger_RelationListView_Model
  modules/Vtiger/models/RelationListView.php
Labels: ✔ finished

#9874 Fixed #9856
  modules/Project/ConfigTemplate.php
  modules/Project/models/Gantt.php
Labels: ✔ finished

#9878 Language import added progress + DB
  install/install_schema/scheme.sql
  vtlib/Vtiger/LanguageExport.php
  vtlib/Vtiger/LanguageImport.php
Labels: 🔧 AmendmentsRequired

#9877 Fixed copy inventory into correct invoices
  public_html/layouts/basic/modules/Vtiger/resources/Inventory.js
Labels: ✔ finished

#9866 Conversion PearDatabase to yii Users_Record_Model
  modules/Users/models/Record.php
Labels: ✔ finished

#9872 Remove getDescriptionValue from Vtiger_Record_Model
  layouts/basic/modules/Vtiger/HelpDeskSummaryWidgetContents.tpl
  modules/Vtiger/models/Record.php
Labels: ✔ finished

#9873 Add improvement to encode Json in Vtiger_ShortURL_Helper
  modules/Vtiger/helpers/ShortURL.php
Labels: ✔ finished

#9879 Conversion PearDatabase to yii LanguageExport
  vtlib/Vtiger/LanguageExport.php
Labels: ✔ finished

#9863 Conversion PearDatabase to yii Settings_OSSPasswords_ConfigurePass_View
  modules/Settings/OSSPasswords/views/ConfigurePass.php
Labels: ✔ finished

#9871 Add button in Yetiforce settings
  app/YetiForce/Register.php
  languages/en-US/Settings/Companies.json
  languages/en-US/Settings/YetiForce.json
  modules/Settings/Companies/models/ListView.php
  modules/Settings/YetiForce/actions/Register.php
  public_html/layouts/basic/modules/Settings/Companies/resources/List.js
Labels: ✔ finished

#9883 Installation template improvements
  install/languages/en-US/ConfReport.json
  install/languages/en-US/Install.json
  install/tpl/Step1.tpl
  install/tpl/Step3.tpl
  install/tpl/Step4.tpl
  install/tpl/Step6.tpl
  languages/en-US/Install.json
  languages/en-US/Settings/ConfReport.json
Labels: ✔ finished

#9887 Remove initialize PearDatabase from SMSNotifier
  modules/SMSNotifier/SMSNotifier.php
Labels: ✔ finished

#9881 Improvements on language download
  app/Installer/Languages.php
  modules/Settings/YetiForce/actions/DownloadLanguage.php
Labels: ✔ finished

#9880 Conversion PearDatabase to yii LayoutExport
  vtlib/Vtiger/FieldBasic.php
  vtlib/Vtiger/LanguageExport.php
  vtlib/Vtiger/LayoutExport.php
Labels: ✔ finished

#9888 Added minor improvements
  vtlib/Vtiger/FieldBasic.php
Labels: ✔ finished

#9889 Remove unused old Kpi dashboard and helper
  layouts/basic/modules/Vtiger/dashboards/Kpi.tpl
  layouts/basic/modules/Vtiger/dashboards/KpiContents.tpl
  modules/Vtiger/dashboards/Kpi.php
  modules/Vtiger/helpers/Kpi.php
Labels: ✔ finished

#9847 Conversion PearDatabase to yii [IT529]
  vtlib/Vtiger/PackageExport.php
Labels: ✔ finished

#9892 Remove sequence form workflow
  install/install_schema/data.sql
  install/install_schema/scheme.sql
  modules/com_vtiger_workflow/VTEntityMethodManager.php
  modules/com_vtiger_workflow/VTTaskType.php
Labels: ✔ finished

#9891 Added minor improvements
  modules/Settings/LayoutEditor/models/Module.php
Labels: ✔ finished

#9893 Changed pharse LBL_REGISTRATION_PENDING
  languages/en-US/Settings/YetiForce.json
Labels: ✔ finished

#9903 #9886 add space between dot and link
  layouts/basic/modules/Vtiger/ListViewContents.tpl
Labels: ✔ finished

#9895 Transfer of DAV cron synchronization
  cron/CalDav.php
  cron/CardDav.php
  install/install_schema/data.sql
Labels: ✔ finished

#9911 Fixed #9910
  app/ModuleHierarchy.php
  modules/Vtiger/widgets/HistoryRelation.php
Labels: ✔ finished

#9913 Small changes tpl
  install/tpl/Step1.tpl
  languages/en-US/Settings/_Base.json
Labels: ✔ finished

#9915 💫 dir aliases for vsc and vue/quasar
  ModuleLoader.server.js
  jsconfig.json
  quasar.conf.js
  src/store/index.js
Labels: ✔ finished

#9919 Changed pharses on ApiAddress.json
  languages/en-US/Settings/ApiAddress.json
Labels: ✔ finished

#9920 Add fix for copy address to undefined select value
  public_html/layouts/basic/modules/Vtiger/resources/Edit.js
Labels: ✔ finished

#9916 Changed tpl settings confReport
  layouts/basic/modules/Settings/Vtiger/Security.tpl
Labels: ✔ finished

#9896 Conversion PearDatabase to yii IStorages
  modules/IStorages/IStorages.php
Labels: ✔ finished

#9899 Remove unused methods in IStorages_Module_Model
  modules/IStorages/handlers/RecalculateStockHandler.php
  modules/IStorages/models/Module.php
Labels: ✔ finished

#9922 Improved display field SharedOwner when you are admin
  modules/Vtiger/uitypes/SharedOwner.php
Labels: ✔ finished

#9923 Add picklist OSSTimeControl value + DB
  install/install_schema/data.sql
  install/install_schema/scheme.sql
  languages/en-US/OSSTimeControl.json
Labels: ✔ finished

#9941 💫 debug logger, module loader improvements, routes.js
  ModuleLoader.server.js
  jsconfig.json
  quasar.conf.js
  src/Main.vue
  src/ModuleLoader.js
  src/layouts/Basic.vue
  src/modules/App/App.vue
  src/modules/App/module.config.json
  src/modules/App/modules/Debug/Debug.vue
  src/modules/App/modules/Debug/module.config.json
  src/modules/App/modules/Debug/store/getters.js
  src/modules/App/modules/Debug/store/mutations.js
  src/modules/App/modules/Debug/store/state.js
  src/modules/App/modules/Hooks/Hooks.vue
  src/modules/App/modules/Menu/components/LeftMenu.vue
  src/modules/App/modules/Menu/components/Positions/RoutePush.vue
  src/modules/App/modules/Menu/module.config.json
  src/modules/App/modules/Users/module.config.json
  src/modules/App/router/routes.js
  src/modules/App/store/getters.js
  src/modules/App/store/mutations.js
  src/modules/App/store/state.js
  src/modules/Base/modules/Home/Home.vue
  src/modules/Base/modules/Home/router/routes.js
  src/modules/Base/modules/ModuleExample/ModuleExample.vue
  src/modules/Base/router/routes.js
  src/modules/Settings/modules/ModuleExample/ModuleExample.vue
  src/modules/Settings/router/routes.js
  src/statics/modules.js
  src/store/getters.js
  src/store/index.js
  src/store/mutations.js
  src/store/routes.js
  src/utilities/Objects.js
Labels: ✔ finished

#9960 💫 Cleaned quasar.conf.js and changed icon names to mdi-
  quasar.conf.js
  src/components/Base/YBreadcrumbs.vue
  src/layouts/Basic.vue
  src/modules/App/modules/Base/modules/Home/Home.vue
  src/modules/App/modules/Base/modules/ModuleExample/ModuleExample.vue
  src/modules/App/modules/Core/modules/Menu/components/LeftMenu.vue
  src/modules/App/modules/Core/modules/Users/Users.vue
  src/modules/App/modules/Core/modules/Users/pages/Login/Form.vue
  src/modules/App/modules/Core/modules/Users/pages/Login/Reminder.vue
  src/modules/App/modules/Settings/modules/ModuleExample/ModuleExample.vue
Labels: ✔ finished

#9961 💫Improved login and added logout action
  app/Controller/WebUI.php
  src/components/Base/YGlobalActions.vue
  src/layouts/Basic.vue
  src/modules/App/modules/Core/modules/Url/store/state.js
  src/modules/App/modules/Core/modules/Users/Users.vue
  src/modules/App/modules/Core/modules/Users/layouts/Login.vue
  src/modules/App/modules/Core/modules/Users/store/actions.js
  src/modules/App/modules/Core/modules/Users/store/state.js
  src/router/index.js
  src/router/routes.js
  src/statics/modules.js
  src/store/actions.js
Labels: ✔ finished

#9964 💫Added reactivity to breadcrumbs
  src/components/Base/YBreadcrumbs.vue
Labels: ✔ finished

#9968 💫 nested menu with expander
  modules/Settings/Menu/models/Record.php
  quasar.conf.js
  src/modules/Base/modules/Home/Home.vue
  src/modules/Base/modules/ModuleExample/ModuleExample.vue
  src/modules/Core/modules/Menu/Menu.vue
  src/modules/Core/modules/Menu/components/Items/Expander.vue
  src/modules/Core/modules/Menu/components/Items/Item.vue
  src/modules/Core/modules/Menu/components/Items/RoutePush.vue
  src/modules/Core/modules/Menu/components/LeftMenu.vue
  src/modules/Settings/modules/ModuleExample/ModuleExample.vue
  src/utilities/Objects.js
Labels: ✔ finished

#9969 💫 module loader appRequire bugfix
  ModuleLoader.server.js
Labels: ✔ finished

#9980 💫 module loader 'module quasar not found' bugfix
  ModuleLoader.server.js
Labels: ✔ finished

#9972 💫 Corrected routes, login messages, RWD
  quasar.conf.js
  src/components/Base/YfBreadcrumbs.vue
  src/components/Base/YfCopyright.vue
  src/components/Base/YfFooter.vue
  src/components/Base/YfGlobalActions.vue
  src/components/Base/YfGlobalSearch.vue
  src/components/Base/YfHeader.vue
  src/css/quasar.variables.styl
  src/layouts/Basic.vue
  src/modules/Base/modules/Home/Home.vue
  src/modules/Base/modules/ModuleExample/ModuleExample.vue
  src/modules/Base/modules/ModuleExample/pages/ModuleExample.vue
  src/modules/Base/router/routes.js
  src/modules/Core/modules/Users/layouts/Login.vue
  src/modules/Core/modules/Users/pages/Login/Form.vue
  src/modules/Core/modules/Users/pages/Login/Reminder.vue
  src/modules/Core/modules/Users/store/actions.js
  src/modules/Core/modules/Users/store/getters.js
  src/modules/Core/modules/Users/store/mutations.js
  src/modules/Core/modules/Users/store/state.js
  src/modules/Core/router/routes.js
  src/router/index.js
  src/statics/modules.js
  src/store/getters.js
  src/store/mutations.js
Labels: ✔ finished

#9981 💫 global hook-wrapper
  src/modules/Core/modules/Hooks/Hooks.vue
  src/modules/Core/modules/Hooks/components/Hook.vue
  src/modules/Core/modules/Hooks/components/HookWrapper.vue
  src/modules/Core/modules/Hooks/module.config.json
Labels: ✔ finished

#9983 💫Corrected login mutations
  src/modules/Core/modules/Users/store/actions.js
  src/modules/Core/modules/Users/store/mutations.js
  src/statics/modules.js
  src/store/mutations.js
Labels: ✔ finished

#9992 Connection of attachments from the email
  languages/en-US/OSSMail.json
  layouts/basic/modules/OSSMail/MailActionBarRow.tpl
  layouts/basic/modules/Vtiger/ButtonLink.tpl
  layouts/basic/modules/Vtiger/Modals/RecordsList.tpl
  modules/OSSMail/views/MailActionBar.php
  modules/OSSMailView/models/Record.php
  modules/Vtiger/actions/RelationAjax.php
  modules/Vtiger/views/RecordsList.php
Labels: ✔ finished

#9921 #9909 add fix for setting a field picklist/relation
  public_html/layouts/basic/modules/Settings/PickListDependency/resources/PickListDependency.js
Labels: ✔ finished

#9936 [IT543] add username validation on install
  install/views/Index.php
  public_html/install/tpl/resources/Index.js
Labels: ✔ finished

#9973 Fixed #9951
  layouts/basic/modules/Calendar/Extended/EventForm.tpl
Labels: ✔ finished

#9999 DB for #9982
  install/install_schema/data.sql
  install/install_schema/scheme.sql
Labels: ✔ finished

#9995 Improved cron PrivilegesUpdater
  cron/PrivilegesUpdater.php
Labels: ✔ finished

#10033 💫 gulp-vue-es-compiler with style tag support
  public_html/gulp-vue-es-compiler.js
  public_html/gulpfile.js
  public_html/package-lock.json
  public_html/package.json
  public_html/src/App.js
  public_html/src/layouts/Basic.js
  public_html/src/modules/Base/Base.js
  public_html/src/modules/Base/layouts/Base.js
  public_html/src/modules/Base/modules/Home/Home.js
  public_html/src/modules/Base/modules/Home/pages/Home.js
  public_html/src/modules/Base/modules/ModuleExample/ModuleExample.js
  public_html/src/modules/Base/modules/ModuleExample/pages/ModuleExample.js
  public_html/src/modules/Core/Core.js
  public_html/src/modules/Core/components/YfBreadcrumbs.js
  public_html/src/modules/Core/components/YfCopyright.js
  public_html/src/modules/Core/components/YfFooter.js
  public_html/src/modules/Core/components/YfGlobalActions.js
  public_html/src/modules/Core/components/YfGlobalSearch.js
  public_html/src/modules/Core/components/YfHeader.js
  public_html/src/modules/Core/layouts/Core.js
  public_html/src/modules/Core/modules/Debug/Debug.js
  public_html/src/modules/Core/modules/Env/Env.js
  public_html/src/modules/Core/modules/Hooks/Hooks.js
  public_html/src/modules/Core/modules/Hooks/components/Hook.js
  public_html/src/modules/Core/modules/Hooks/components/HookWrapper.js
  public_html/src/modules/Core/modules/Language/Language.js
  public_html/src/modules/Core/modules/Menu/Menu.js
  public_html/src/modules/Core/modules/Menu/components/Items/Expander.js
  public_html/src/modules/Core/modules/Menu/components/Items/Item.js
  public_html/src/modules/Core/modules/Menu/components/Items/RoutePush.js
  public_html/src/modules/Core/modules/Menu/components/LeftMenu.js
  public_html/src/modules/Core/modules/Url/Url.js
  public_html/src/modules/Core/modules/Users/Users.js
  public_html/src/modules/Core/modules/Users/layouts/Login.js
  public_html/src/modules/Core/modules/Users/pages/Login/2FA.js
  public_html/src/modules/Core/modules/Users/pages/Login/Form.js
  public_html/src/modules/Core/modules/Users/pages/Login/Reminder.js
  public_html/src/modules/Settings/Settings.js
  public_html/src/modules/Settings/layouts/Settings.js
  public_html/src/modules/Settings/modules/ModuleExample/ModuleExample.js
  public_html/src/modules/Settings/modules/ModuleExample/pages/ModuleExample.js
  public_html/src/pages/Error404.js
  public_html/src/pages/Index.js
Labels: ✔ finished

#10045 💫 restored production functionality with native import
  app/Controller/WebUI.php
  public_html/dev-server.js
  public_html/gulp-vue-es-compiler.js
  public_html/gulpfile.js
  public_html/package-lock.json
  public_html/package.json
  public_html/src/App.js
  public_html/src/i18n/index.js
  public_html/src/layouts/Basic.js
  public_html/src/main.js
  public_html/src/modules/Base/Base.js
  public_html/src/modules/Base/layouts/Base.js
  public_html/src/modules/Base/modules/Home/Home.js
  public_html/src/modules/Base/modules/Home/pages/Home.js
  public_html/src/modules/Base/modules/ModuleExample/ModuleExample.js
  public_html/src/modules/Base/modules/ModuleExample/pages/ModuleExample.js
  public_html/src/modules/Core/Core.js
  public_html/src/modules/Core/components/YfBreadcrumbs.js
  public_html/src/modules/Core/components/YfCopyright.js
  public_html/src/modules/Core/components/YfFooter.js
  public_html/src/modules/Core/components/YfGlobalActions.js
  public_html/src/modules/Core/components/YfGlobalSearch.js
  public_html/src/modules/Core/components/YfHeader.js
  public_html/src/modules/Core/components/YfHeader.vue
  public_html/src/modules/Core/layouts/Core.js
  public_html/src/modules/Core/modules/Debug/Debug.js
  public_html/src/modules/Core/modules/Env/Env.js
  public_html/src/modules/Core/modules/Hooks/Hooks.js
  public_html/src/modules/Core/modules/Hooks/components/Hook.js
  public_html/src/modules/Core/modules/Hooks/components/HookWrapper.js
  public_html/src/modules/Core/modules/Language/Language.js
  public_html/src/modules/Core/modules/Menu/Menu.js
  public_html/src/modules/Core/modules/Menu/components/Items/Expander.js
  public_html/src/modules/Core/modules/Menu/components/Items/Item.js
  public_html/src/modules/Core/modules/Menu/components/Items/RoutePush.js
  public_html/src/modules/Core/modules/Menu/components/LeftMenu.js
  public_html/src/modules/Core/modules/Url/Url.js
  public_html/src/modules/Core/modules/Users/Users.js
  public_html/src/modules/Core/modules/Users/layouts/Login.js
  public_html/src/modules/Core/modules/Users/layouts/Login.vue
  public_html/src/modules/Core/modules/Users/pages/Login/2FA.js
  public_html/src/modules/Core/modules/Users/pages/Login/Form.js
  public_html/src/modules/Core/modules/Users/pages/Login/Reminder.js
  public_html/src/modules/Settings/Settings.js
  public_html/src/modules/Settings/layouts/Settings.js
  public_html/src/modules/Settings/modules/ModuleExample/ModuleExample.js
  public_html/src/modules/Settings/modules/ModuleExample/pages/ModuleExample.js
  public_html/src/pages/Error404.js
  public_html/src/pages/Index.js
  public_html/src/router/index.js
  public_html/src/statics/modules.js
  src/modules/Core/components/YfBreadcrumbs.vue
  src/modules/Core/components/YfCopyright.vue
  src/modules/Core/components/YfFooter.vue
  src/modules/Core/components/YfGlobalActions.vue
  src/modules/Core/components/YfGlobalSearch.vue
  src/modules/Core/components/YfHeader.vue
  src/statics/modules.js
Labels: ✔ finished

#10032 Fixed #9965
  app/QueryGenerator.php
Labels: ✔ finished

#10009 Add fix to search params link from charts
  modules/Vtiger/models/ChartFilter.php
Labels: ✔ finished

#10048 💫 native imports bugfixes
  app/Controller/WebUI.php
  public_html/ModuleLoader.server.js
  public_html/src/ModuleLoader.js
  public_html/src/i18n/index.js
  public_html/src/main.js
  public_html/src/modules/Core/components/YfHeader.js
  public_html/src/modules/Core/modules/Users/layouts/Login.js
  public_html/src/modules/Core/modules/Users/store/actions.js
  public_html/src/statics/modules.js
  public_html/src/store/index.js
  public_html/src/utilities/Objects.js
Labels: ✔ finished

#10049 💫 further native import bugfixes
  public_html/ModuleLoader.server.js
  public_html/gulpfile.js
  public_html/src/modules/Core/modules/Users/store/actions.js
Labels: ✔ finished

#9976 Fixed parsing mail message.
  app/Utils.php
  modules/OSSMailScanner/scanneractions/CreatedEmail.php
  vtlib/Vtiger/Functions.php
Labels: ✔ finished

#10020 Removed _seq tables (DB)
  install/install_schema/data.sql
  install/install_schema/scheme.sql
Labels: ✔ finished, 👮‍♂️ VerificationRequired

#10012 Restore go to full form button in extended calendar
  layouts/basic/modules/Calendar/Extended/EventForm.tpl
Labels: ✔ finished

#10013 Added some modal changes
  app/YetiForce/Register.php
  languages/en-US/Settings/YetiForce.json
  layouts/basic/modules/Settings/YetiForce/RegistrationOfflineModal.tpl
Labels: ✔ finished

#10044 Fixed time format in date and time field
  public_html/layouts/resources/Fields.js
Labels: ✔ finished

#10025 Remove possibility to create cf fields
  layouts/basic/modules/Settings/LayoutEditor/CreateFieldModal.tpl
  modules/Settings/LayoutEditor/models/Module.php
  public_html/layouts/basic/modules/Settings/LayoutEditor/resources/LayoutEditor.js
Labels: ✔ finished

#10047 Moved calendar notifications limit to config file
  modules/Calendar/ConfigTemplate.php
  modules/Calendar/models/Module.php
Labels: ✔ finished

#10046 Added possibility copy emails in workflow task [IT555]
  layouts/basic/modules/Settings/Workflows/Tasks/VTEmailTask.tpl
Labels: ✔ finished
