Repository YetiForceCompany/YetiForceCRM, pull requests merged in 2019-09, with the labels that each got.

#11380 Fixed chat bugs
  app/Chat.php
  modules/Chat/actions/ChatAjax.php
  modules/Chat/actions/Room.php
  public_html/layouts/basic/modules/Chat/Chat.vue.js
  public_html/layouts/basic/modules/Chat/Chat.vue.js.map
  public_html/layouts/resources/views/KnowledgeBase/KnowledgeBase.vue.js
  public_html/layouts/resources/views/KnowledgeBase/KnowledgeBase.vue.js.map
  public_html/src/components/Drag.vue
  public_html/src/components/DragResize.vue
  public_html/src/components/IconInfo.vue
  public_html/src/layouts/basic/modules/Chat/components/ChatHeader.vue
  public_html/src/layouts/basic/modules/Chat/components/ChatTab.vue
  public_html/src/layouts/basic/modules/Chat/components/LeftPanel.vue
  public_html/src/layouts/basic/modules/Chat/components/SelectModules.vue
  public_html/src/layouts/basic/modules/Chat/store/mutations.js
  public_html/src/mixins/DragResize.js
Labels: ▶ in progress

#11383 Fixed chat button click event
  public_html/layouts/basic/modules/Chat/Chat.vue.js
  public_html/layouts/basic/modules/Chat/Chat.vue.js.map
  public_html/layouts/resources/views/KnowledgeBase/KnowledgeBase.vue.js
  public_html/layouts/resources/views/KnowledgeBase/KnowledgeBase.vue.js.map
  public_html/src/layouts/basic/modules/Chat/views/Dialog.vue
Labels: ✔ finished

#11384 Fixed focus on checkbox
  public_html/layouts/basic/modules/Vtiger/resources/Edit.js
  public_html/layouts/basic/styles/Main.css
  public_html/layouts/basic/styles/Main.css.map
  public_html/layouts/basic/styles/components/_Checkbox.scss
Labels: ✔ finished

#11387 Changed dropdown to select in address search and edit view buttons
  layouts/basic/modules/Vtiger/BlockHeader.tpl
  layouts/basic/modules/Vtiger/ButtonLink.tpl
  layouts/basic/modules/Vtiger/EditViewActions.tpl
  public_html/layouts/basic/modules/Vtiger/resources/Edit.js
Labels: ✔ finished

#11386 Fixed menu selected item for marketplace [IT673]
  modules/Settings/Vtiger/models/MenuItem.php
Labels: ✔ finished

#11385 Improved chat
  modules/Chat/actions/ChatAjax.php
  public_html/layouts/basic/modules/Chat/Chat.vue.js
  public_html/layouts/basic/modules/Chat/Chat.vue.js.map
  public_html/src/css/quasar.css
  public_html/src/css/quasar.styl
  public_html/src/layouts/basic/modules/Chat/components/Messages.vue
  public_html/src/layouts/basic/modules/Chat/components/RightPanel.vue
  public_html/src/layouts/basic/modules/Chat/components/Unread.vue
  public_html/src/layouts/basic/modules/Chat/store/actions.js
  public_html/src/layouts/basic/modules/Chat/store/mutations.js
  public_html/src/layouts/basic/modules/Chat/utils/utils.js
  public_html/src/layouts/basic/modules/Chat/views/RecordRoom.vue
Labels: ✔ finished

#11341 Added search input in tree modal
  layouts/basic/modules/Vtiger/Modals/TreeHeader.tpl
  modules/Vtiger/views/TreeModal.php
Labels: ✔ finished

#11393 Added chat minimum sizes
  public_html/layouts/basic/modules/Chat/Chat.vue.js
  public_html/layouts/basic/modules/Chat/Chat.vue.js.map
  public_html/layouts/resources/views/KnowledgeBase/KnowledgeBase.vue.js
  public_html/layouts/resources/views/KnowledgeBase/KnowledgeBase.vue.js.map
  public_html/src/components/DragResize.vue
Labels: ✔ finished

#11394 Improved shop
  layouts/basic/modules/Settings/Vtiger/DashBoard/PartnerZone.tpl
  layouts/basic/modules/Settings/Vtiger/DashBoard/PremiumZone.tpl
  layouts/basic/modules/Settings/Vtiger/DashBoard/SystemMonitoring.tpl
  layouts/basic/modules/Settings/Vtiger/Index.tpl
  layouts/basic/modules/Settings/YetiForce/BuyModal.tpl
  layouts/basic/modules/Settings/YetiForce/Shop.tpl
  layouts/basic/modules/Settings/YetiForce/Shop/ProductPremium.tpl
  modules/Settings/YetiForce/views/BuyModal.php
  public_html/layouts/basic/modules/Settings/Vtiger/resources/Index.js
  public_html/layouts/basic/modules/Settings/YetiForce/resources/Shop.js
  public_html/layouts/basic/styles/Main.css
  public_html/layouts/basic/styles/Main.css.map
  public_html/layouts/basic/styles/components/_Global.scss
  public_html/layouts/basic/styles/pages/Settings/_Shop.scss
Labels: ✔ finished

#11398 Changed plugin name to ckeditor-image-to-base
  app/Installer/Composer.php
  package.json
  public_html/layouts/resources/Fields.js
Labels: ✔ finished

#11395 Corrected chat privileges and record view bugs, added links
  app/Chat.php
  modules/Chat/actions/ChatAjax.php
  public_html/layouts/basic/modules/Chat/Chat.vue.js
  public_html/layouts/basic/modules/Chat/Chat.vue.js.map
  public_html/src/layouts/basic/modules/Chat/Chat.js
  public_html/src/layouts/basic/modules/Chat/components/ChatTab.vue
  public_html/src/layouts/basic/modules/Chat/components/History.vue
  public_html/src/layouts/basic/modules/Chat/components/LeftPanel.vue
  public_html/src/layouts/basic/modules/Chat/components/MainPanel.vue
  public_html/src/layouts/basic/modules/Chat/components/Messages.vue
  public_html/src/layouts/basic/modules/Chat/components/Unread.vue
  public_html/src/layouts/basic/modules/Chat/store/actions.js
  public_html/src/layouts/basic/modules/Chat/store/state.js
  public_html/src/layouts/basic/modules/Chat/views/Dialog.vue
Labels: ✔ finished

#11399 Corrected installation images
  install/tpl/StepChooseHost.tpl
  public_html/layouts/basic/styles/Main.css
  public_html/layouts/basic/styles/Main.css.map
  public_html/layouts/basic/styles/components/_Utilities.scss
  public_html/layouts/basic/styles/pages/Settings/_Shop.scss
Labels: ✔ finished

#11405 Added product modal to installation
  install/tpl/StepChooseHost.tpl
  install/views/Index.php
  languages/en-US/Install.json
  layouts/basic/modules/Settings/YetiForce/ProductModal.tpl
  modules/Settings/YetiForce/views/ProductModal.php
  public_html/install/tpl/resources/Index.js
Labels: ✔ finished

#11406 Added popover info to custom fields
  app/YetiForce/Shop/Product/InstallInCloud.php
  app/YetiForce/Shop/Product/InstallInHosting.php
  languages/en-US/Settings/YetiForce.json
  layouts/basic/modules/Settings/YetiForce/BuyModal.tpl
  public_html/install/tpl/resources/css/mkCheckbox.css
Labels: ✔ finished

#11412 Improved Chat
  app/Chat.php
  public_html/layouts/basic/modules/Chat/Chat.vue.js
  public_html/layouts/basic/modules/Chat/Chat.vue.js.map
  public_html/src/layouts/basic/modules/Chat/components/ChatTab.vue
Labels: ✔ finished

#11413 Updated min files
  public_html/install/tpl/resources/Index.min.js
  public_html/install/tpl/resources/Index.min.js.map
  public_html/layouts/basic/modules/Documents/resources/Edit.min.js.map
  public_html/layouts/basic/modules/Settings/Vtiger/resources/Index.min.js
  public_html/layouts/basic/modules/Settings/Vtiger/resources/Index.min.js.map
  public_html/layouts/basic/modules/Settings/Workflows/resources/Edit1.min.js
  public_html/layouts/basic/modules/Settings/Workflows/resources/Edit1.min.js.map
  public_html/layouts/basic/modules/Settings/YetiForce/resources/Shop.min.js
  public_html/layouts/basic/modules/Settings/YetiForce/resources/Shop.min.js.map
  public_html/layouts/basic/modules/Users/resources/Edit.min.js
  public_html/layouts/basic/modules/Users/resources/Edit.min.js.map
  public_html/layouts/basic/modules/Vtiger/resources/Detail.min.js
  public_html/layouts/basic/modules/Vtiger/resources/Detail.min.js.map
  public_html/layouts/basic/modules/Vtiger/resources/Edit.min.js
  public_html/layouts/basic/modules/Vtiger/resources/Edit.min.js.map
  public_html/layouts/basic/modules/Vtiger/resources/Inventory.min.js
  public_html/layouts/basic/modules/Vtiger/resources/Inventory.min.js.map
  public_html/layouts/basic/modules/Vtiger/resources/List.min.js
  public_html/layouts/basic/modules/Vtiger/resources/List.min.js.map
  public_html/layouts/basic/styles/Main.min.css
  public_html/layouts/resources/Fields.min.js
  public_html/layouts/resources/Fields.min.js.map
  public_html/layouts/resources/app.min.js
  public_html/layouts/resources/app.min.js.map
  public_html/layouts/resources/validator/FieldValidator.min.js
  public_html/layouts/resources/validator/FieldValidator.min.js.map
Labels: ✔ finished

#11417 Moved emoji mart to libraries from node_modules
  app/Controller/View.php
  package.json
  public_html/layouts/basic/modules/Chat/Chat.vue.js
  public_html/layouts/basic/modules/Chat/Chat.vue.js.map
  public_html/src/layouts/basic/modules/Chat/components/MessageInput.vue
  public_html/src/package.json
  public_html/src/yarn.lock
Labels: ✔ finished

#11415 Improved address api configuration
  app/Map/Address.php
  app/Map/Address/Base.php
  app/Map/Address/GoogleGeocode.php
  app/Map/Address/NominatimGeocoder.php
  app/Map/Address/OpenCageGeocoder.php
  app/Map/Address/YetiForceGeocoder.php
  config/Components/ConfigTemplates.php
  install/install_schema/data.sql
  install/install_schema/scheme.sql
  languages/en-US/Settings/ApiAddress.json
  layouts/basic/modules/Settings/ApiAddress/ApiConfigModal.tpl
  layouts/basic/modules/Settings/ApiAddress/Configuration.tpl
  layouts/basic/modules/Vtiger/BlockHeader.tpl
  modules/Settings/ApiAddress/actions/SaveConfig.php
  modules/Settings/ApiAddress/models/Module.php
  modules/Settings/ApiAddress/views/ApiConfigModal.php
  modules/Settings/ApiAddress/views/Configuration.php
  public_html/layouts/basic/modules/Settings/ApiAddress/resources/ApiAddress.js
  public_html/layouts/basic/modules/Settings/YetiForce/resources/Shop.js
Labels: ▶ in progress

#11418 Updated min files
  public_html/layouts/basic/modules/Settings/ApiAddress/resources/ApiAddress.min.js
  public_html/layouts/basic/modules/Settings/ApiAddress/resources/ApiAddress.min.js.map
  public_html/layouts/basic/modules/Settings/YetiForce/resources/Shop.min.js
  public_html/layouts/basic/modules/Settings/YetiForce/resources/Shop.min.js.map
Labels: ✔ finished

#11419 Fixed showing selected option for lazy select
  layouts/basic/modules/Vtiger/Edit/Field/Picklist.tpl
  public_html/layouts/resources/Fields.js
  public_html/layouts/resources/Fields.min.js
  public_html/layouts/resources/Fields.min.js.map
Labels: ✔ finished

#11438 Fixed list filter select actions
  public_html/layouts/basic/modules/Vtiger/resources/List.js
Labels: ✔ finished

#11439 Updated min files
  public_html/layouts/basic/modules/Vtiger/resources/List.min.js
  public_html/layouts/basic/modules/Vtiger/resources/List.min.js.map
Labels: ✔ finished

#11450 Updated libraries
  composer.lock
  package.json
  public_html/layouts/basic/modules/Chat/Chat.vue.js
  public_html/layouts/basic/modules/Chat/Chat.vue.js.map
  public_html/layouts/resources/views/KnowledgeBase/KnowledgeBase.vue.js
  public_html/layouts/resources/views/KnowledgeBase/KnowledgeBase.vue.js.map
  public_html/src/yarn.lock
  yarn.lock
Labels: ✔ finished

#11451 Fixed select2 sorting animation
  public_html/layouts/basic/styles/Main.css
  public_html/layouts/basic/styles/Main.css.map
  public_html/layouts/basic/styles/libraries/_Libraries.scss
Labels: ✔ finished

#11452 Updated npm libraries
  package.json
  public_html/src/package.json
  public_html/src/yarn.lock
  yarn.lock
Labels: ✔ finished

#11454 Added EditViewActions.tpl to Settings
  layouts/basic/modules/Settings/Vtiger/EditViewActions.tpl
Labels: ✔ finished

#11470 Corrected chat modules list
  app/Chat.php
  public_html/layouts/basic/modules/Chat/Chat.vue.js
  public_html/layouts/basic/modules/Chat/Chat.vue.js.map
  public_html/src/layouts/basic/modules/Chat/components/SelectModules.vue
Labels: ✔ finished

#11499 Added default value to fields in User module
  install/install_schema/data.sql
Labels: ✔ finished

#11500 Improved roundcube popover, updated min files
  config/version.php
  languages/en-US/Users.json
  public_html/layouts/basic/modules/Calendar/resources/Extended/CalendarView.min.js
  public_html/layouts/basic/modules/Calendar/resources/Extended/CalendarView.min.js.map
  public_html/layouts/basic/modules/Calendar/resources/Standard/CalendarView.min.js
  public_html/layouts/basic/modules/Calendar/resources/Standard/CalendarView.min.js.map
  public_html/layouts/basic/modules/Settings/LayoutEditor/resources/LayoutEditor.min.js
  public_html/layouts/basic/modules/Settings/LayoutEditor/resources/LayoutEditor.min.js.map
  public_html/layouts/basic/modules/Settings/Widgets/resources/Widgets.min.js
  public_html/layouts/basic/modules/Settings/Widgets/resources/Widgets.min.js.map
  public_html/layouts/basic/modules/Vtiger/resources/ListPreview.min.js
  public_html/layouts/basic/modules/Vtiger/resources/ListPreview.min.js.map
  public_html/layouts/basic/skins/gray/style.css
  public_html/layouts/basic/skins/gray/style.css.map
  public_html/layouts/basic/styles/Main.css
  public_html/layouts/basic/styles/Main.css.map
  public_html/layouts/basic/styles/layout/_Base.scss
  public_html/layouts/resources/Calendar.min.js
  public_html/layouts/resources/Calendar.min.js.map
  public_html/layouts/resources/Fields.min.js
  public_html/layouts/resources/Fields.min.js.map
  public_html/layouts/resources/app.js
  public_html/layouts/resources/app.min.js
  public_html/layouts/resources/app.min.js.map
Labels: ✔ finished

#11495 Suspended test RecordFlowUpdater
  tests/Base/J_RecordFlowUpdater.php
Labels: ⏸ Not Finished

#11501 Added variable return in skip tests
  tests/Base/J_RecordFlowUpdater.php
Labels: ⏸ Not Finished

#11503 Add field to set sender name in SMSAPI
  languages/en-US/Settings/SMSNotifier.json
  modules/SMSNotifier/providers/SMSAPI.php
Labels: ✔ finished

#11511 Add ability to create reference record on quick create
  layouts/basic/modules/Vtiger/Edit/Field/Reference.tpl
  public_html/layouts/basic/modules/Vtiger/resources/Edit.js
Labels: ✔ finished

#11517 Fixed saving field sequence after module change
  public_html/layouts/basic/modules/Settings/LayoutEditor/resources/LayoutEditor.js
Labels: ✔ finished

#11534 Fixed #11428
  layouts/basic/modules/Settings/PDF/Step1.tpl
Labels: ✔ finished

#11535 Add icons calendar event type in Calendar extended
  install/install_schema/scheme.sql
  layouts/basic/modules/Calendar/Edit/Field/ActivityType.tpl
  layouts/basic/modules/Calendar/Extended/EventForm.tpl
  modules/Calendar/ConfigTemplate.php
  modules/Settings/Picklist/models/Module.php
  public_html/layouts/basic/styles/Main.css
  public_html/layouts/basic/styles/Main.css.map
  public_html/layouts/basic/styles/components/_Utilities.scss
Labels: ✔ finished

#11504 Added private rooms to chat
  app/Chat.php
  install/install_schema/scheme.sql
  languages/en-US/_Base.json
  modules/Chat/actions/ChatAjax.php
  modules/Chat/actions/Room.php
  public_html/layouts/basic/modules/Chat/Chat.vue.js
  public_html/layouts/basic/modules/Chat/Chat.vue.js.map
  public_html/layouts/basic/styles/libraries/_Quasar.scss
  public_html/src/css/quasar.css
  public_html/src/css/quasar.styl
  public_html/src/layouts/basic/modules/Chat/components/AddRoom.vue
  public_html/src/layouts/basic/modules/Chat/components/ChatTab.vue
  public_html/src/layouts/basic/modules/Chat/components/History.vue
  public_html/src/layouts/basic/modules/Chat/components/LeftPanel.vue
  public_html/src/layouts/basic/modules/Chat/components/RightPanel.vue
  public_html/src/layouts/basic/modules/Chat/components/SelectModules.vue
  public_html/src/layouts/basic/modules/Chat/components/SelectUsers.vue
  public_html/src/layouts/basic/modules/Chat/components/Unread.vue
  public_html/src/layouts/basic/modules/Chat/components/UpdateWatcher.vue
  public_html/src/layouts/basic/modules/Chat/store/actions.js
  public_html/src/layouts/basic/modules/Chat/store/getters.js
  public_html/src/layouts/basic/modules/Chat/store/mutations.js
  public_html/src/layouts/basic/modules/Chat/store/state.js
  public_html/src/layouts/basic/modules/Chat/utils/utils.js
Labels: ✔ finished

#11537 Updated css files
  public_html/layouts/basic/styles/Main.css
  public_html/layouts/basic/styles/Main.css.map
Labels: ✔ finished

#11538 Omitted The http verification in the module installation and changed translation
  app/Utils/ConfReport.php
  install/languages/en-US/ConfReport.json
  install/languages/pl-PL/ConfReport.json
Labels: ✔ finished

#11544 Small improvements
  modules/Settings/Companies/models/Record.php
Labels: ✔ finished

#11546 Fixed display print button on chart filter
  layouts/basic/modules/Vtiger/dashboards/ChartFilterHeader.tpl
Labels: ✔ finished

#11547 Changed !empty() to isset() in ConfReport
  install/tpl/StepVerifyServerConfiguration.tpl
  layouts/basic/modules/Settings/ConfReport/Index.tpl
Labels: ✔ finished

#11549 changed justification of text from center to left in Widget
  layouts/basic/modules/Vtiger/SummaryWidgetsContent.tpl
Labels: ✔ finished

#11543 Added function check if value is empty.
  app/Utils/ConfReport.php
Labels: ✔ finished

#11435 Improved geocoding
  app/Map/Address.php
  app/Map/Address/Base.php
  app/Map/Address/GoogleGeocode.php
  app/Map/Address/NominatimGeocoder.php
  app/Map/Address/OpenCageGeocoder.php
  app/Map/Address/YetiForceGeocoder.php
  languages/en-US/Settings/ApiAddress.json
  layouts/basic/modules/Settings/ApiAddress/ApiConfigModal.tpl
  layouts/basic/modules/Settings/ApiAddress/Configuration.tpl
  layouts/basic/modules/Settings/ApiAddress/google_map_api.tpl
  layouts/basic/modules/Settings/ApiAddress/opencage_data.tpl
  layouts/basic/modules/Vtiger/BlockHeader.tpl
  public_html/layouts/basic/modules/Settings/ApiAddress/resources/ApiAddress.js
  public_html/layouts/resources/validator/FieldValidator.js
Labels: ✔ finished

#11556 [IT671] Improved Mass addition of documents in the contractor
  public_html/layouts/basic/modules/Vtiger/resources/Vtiger.js
Labels: ✔ finished

#11557 Deleted translation
  app/SystemWarnings/Security/SecurityConf.php
  app/SystemWarnings/Security/ServerHttps.php
  app/SystemWarnings/SystemRequirements/Configuration.php
  languages/en-US/Settings/SystemWarnings.json
Labels: ✔ finished

#11551 Corrected login page CSP errors
  layouts/basic/modules/Users/Header.tpl
  layouts/basic/modules/Users/Login.Default.tpl
  modules/Users/views/Login.php
  public_html/layouts/basic/modules/Users/resources/Login.js
Labels: ✔ finished

#11568 Fixed integer validation
  public_html/layouts/resources/validator/FieldValidator.js
Labels: ✔ finished

#11539 Corrected privileges for leaving rooms, added archiving private rooms
  app/Chat.php
  install/install_schema/scheme.sql
  languages/en-US/_Base.json
  modules/Chat/actions/ChatAjax.php
  modules/Chat/actions/Room.php
  public_html/layouts/basic/modules/Chat/Chat.vue.js
  public_html/layouts/basic/modules/Chat/Chat.vue.js.map
  public_html/src/layouts/basic/modules/Chat/components/AddRoom.vue
  public_html/src/layouts/basic/modules/Chat/components/LeftPanel.vue
  public_html/src/layouts/basic/modules/Chat/components/RightPanel.vue
  public_html/src/layouts/basic/modules/Chat/components/SelectModules.vue
  public_html/src/layouts/basic/modules/Chat/components/SelectUsers.vue
  public_html/src/layouts/basic/modules/Chat/components/UpdateWatcher.vue
  public_html/src/layouts/basic/modules/Chat/store/actions.js
  public_html/src/layouts/basic/modules/Chat/store/getters.js
  public_html/src/layouts/basic/modules/Chat/store/mutations.js
  public_html/src/layouts/basic/modules/Chat/store/state.js
Labels: ✔ finished

#11579 Add check headers in conf report.
  app/Utils/ConfReport.php
  languages/en-US/Settings/ConfReport.json
  layouts/basic/modules/Settings/ConfReport/Index.tpl
Labels: ✔ finished

#11593 Improved chat button and room list
  languages/en-US/_Base.json
  public_html/layouts/basic/modules/Chat/Chat.vue.js
  public_html/layouts/basic/modules/Chat/Chat.vue.js.map
  public_html/layouts/basic/modules/Vtiger/resources/DetailPreview.js
  public_html/src/css/quasar.css
  public_html/src/css/quasar.variables.styl
  public_html/src/layouts/basic/modules/Chat/components/Chat.vue
  public_html/src/layouts/basic/modules/Chat/components/ChatHeader.vue
  public_html/src/layouts/basic/modules/Chat/components/LeftPanel.vue
  public_html/src/layouts/basic/modules/Chat/store/getters.js
  public_html/src/layouts/basic/modules/Chat/store/mutations.js
  public_html/src/layouts/basic/modules/Chat/store/state.js
  public_html/src/layouts/basic/modules/Chat/utils/utils.js
  public_html/src/layouts/basic/modules/Chat/views/Dialog.vue
Labels: ✔ finished

#11599 Fixed manual start workflow
  public_html/layouts/basic/modules/Vtiger/resources/Detail.js
Labels: ✔ finished

#11600 Refactored chat vue files
  public_html/layouts/basic/modules/Chat/Chat.vue.js
  public_html/layouts/basic/modules/Chat/Chat.vue.js.map
  public_html/layouts/resources/app.js
  public_html/layouts/resources/views/KnowledgeBase/KnowledgeBase.vue.js
  public_html/layouts/resources/views/KnowledgeBase/KnowledgeBase.vue.js.map
  public_html/src/components/YfBackdrop.vue
  public_html/src/components/YfDrag.vue
  public_html/src/components/YfIcon.vue
  public_html/src/layouts/basic/modules/Chat/Chat.js
  public_html/src/layouts/basic/modules/Chat/components/ChatContainer.vue
  public_html/src/layouts/basic/modules/Chat/components/ChatFooter.vue
  public_html/src/layouts/basic/modules/Chat/components/ChatHeader.vue
  public_html/src/layouts/basic/modules/Chat/components/ChatLeftPanel.vue
  public_html/src/layouts/basic/modules/Chat/components/ChatMainPanel.vue
  public_html/src/layouts/basic/modules/Chat/components/ChatNotifyButton.vue
  public_html/src/layouts/basic/modules/Chat/components/ChatRightPanel.vue
  public_html/src/layouts/basic/modules/Chat/components/ChatUpdateWatcher.vue
  public_html/src/layouts/basic/modules/Chat/components/LeftPanel.vue
  public_html/src/layouts/basic/modules/Chat/components/Rooms/RoomGlobal.vue
  public_html/src/layouts/basic/modules/Chat/components/Rooms/RoomGroup.vue
  public_html/src/layouts/basic/modules/Chat/components/Rooms/RoomList.vue
  public_html/src/layouts/basic/modules/Chat/components/Rooms/RoomPrivate.vue
  public_html/src/layouts/basic/modules/Chat/components/Rooms/RoomPrivateInput.vue
  public_html/src/layouts/basic/modules/Chat/components/Rooms/RoomRecord.vue
  public_html/src/layouts/basic/modules/Chat/components/Rooms/RoomRecordSelect.vue
  public_html/src/layouts/basic/modules/Chat/components/Rooms/RoomUserSelect.vue
  public_html/src/layouts/basic/modules/Chat/components/Tabs/TabChat.vue
  public_html/src/layouts/basic/modules/Chat/components/Tabs/TabChatInput.vue
  public_html/src/layouts/basic/modules/Chat/components/Tabs/TabHistory.vue
  public_html/src/layouts/basic/modules/Chat/components/Tabs/TabMessages.vue
  public_html/src/layouts/basic/modules/Chat/components/Tabs/TabUnread.vue
  public_html/src/layouts/basic/modules/Chat/views/Dialog.vue
  public_html/src/layouts/basic/modules/Chat/views/RecordRoom.vue
  public_html/src/layouts/resources/views/KnowledgeBase/KnowledgeBase.vue
  public_html/src/layouts/resources/views/KnowledgeBase/components/ArticlePreviewContent.vue
  public_html/src/layouts/resources/views/KnowledgeBase/components/ArticlesList.vue
  public_html/src/layouts/resources/views/KnowledgeBase/components/Carousel.vue
  public_html/src/layouts/resources/views/KnowledgeBase/components/CategoriesList.vue
Labels: ✔ finished

#11602 Improved headers checker
  app/RequestUtil.php
  app/Utils/ConfReport.php
  layouts/basic/modules/Settings/ConfReport/Index.tpl
Labels: ✔ finished

#11603 Improved headers checker
  app/RequestUtil.php
Labels: ✔ finished

#11605 Improved chat
  public_html/layouts/basic/modules/Chat/Chat.vue.js
  public_html/layouts/basic/modules/Chat/Chat.vue.js.map
  public_html/layouts/basic/styles/Main.css
  public_html/layouts/basic/styles/Main.css.map
  public_html/layouts/basic/styles/components/_Utilities.scss
  public_html/layouts/resources/views/KnowledgeBase/KnowledgeBase.vue.js
  public_html/layouts/resources/views/KnowledgeBase/KnowledgeBase.vue.js.map
  public_html/src/components/ButtonGrab.vue
  public_html/src/components/YfDrag.vue
  public_html/src/layouts/basic/modules/Chat/components/ChatFooter.vue
  public_html/src/layouts/basic/modules/Chat/components/ChatHeader.vue
  public_html/src/layouts/basic/modules/Chat/components/Rooms/RoomList.vue
  public_html/src/layouts/basic/modules/Chat/components/Rooms/RoomPrivate.vue
  public_html/src/layouts/basic/modules/Chat/components/Rooms/RoomRecord.vue
  public_html/src/layouts/basic/modules/Chat/components/Tabs/TabChat.vue
  public_html/src/layouts/basic/modules/Chat/components/Tabs/TabHistory.vue
  public_html/src/layouts/basic/modules/Chat/components/Tabs/TabMessages.vue
  public_html/src/layouts/basic/modules/Chat/views/Dialog.vue
  public_html/src/layouts/resources/views/KnowledgeBase/KnowledgeBaseModal.vue
Labels: ✔ finished

#11607 Corrected comments widget buttons and input
  layouts/basic/modules/Vtiger/RecentComments.tpl
Labels: ✔ finished

#11608 Fixed picklist configuration layout
  layouts/basic/modules/Settings/Picklist/PickListValueDetail.tpl
  layouts/basic/modules/Vtiger/BodyHeader.tpl
  public_html/layouts/basic/styles/_Style.scss
Labels: ✔ finished

#11611 Improved registration warnings
  layouts/basic/modules/Settings/Vtiger/SettingsMenuStart.tpl
  public_html/layouts/basic/styles/_Variables.scss
  public_html/layouts/basic/styles/pages/_Edit.scss
Labels: ✔ finished

#11612 Fixed layout bugs
  layouts/basic/modules/Calendar/Extended/EventForm.tpl
  layouts/basic/modules/Leads/ConvertLead.tpl
  layouts/basic/modules/Vtiger/ButtonLink.tpl
  layouts/basic/modules/Vtiger/Modals/Footer.tpl
  layouts/basic/modules/Vtiger/QuickCreate.tpl
  modules/Calendar/models/QuickCreateView.php
  modules/Vtiger/models/QuickCreateView.php
  public_html/layouts/resources/app.js
Labels: ✔ finished

#11617 Added registering wyswig in ajax edit
  public_html/layouts/basic/modules/Vtiger/resources/Detail.js
Labels: ✔ finished

#11618 Improved modules list on CustomView settings
  modules/Settings/CustomView/models/Module.php
Labels: ✔ finished

#11619 Fixed validating conditions in service contracts
  layouts/basic/modules/ServiceContracts/CustomConditions.tpl
  public_html/layouts/basic/modules/ServiceContracts/resources/Detail.js
Labels: ✔ finished

#11620 Added lacking date operators to OPERATORS_WITHOUT_VALUES
  app/Condition.php
Labels: ✔ finished

#11621 Added modifiedby and createdby related variables in TextParser.
  app/TextParser.php
Labels: ✔ finished

#11614 Fixed #11427 calendars' bugs
  layouts/basic/modules/Calendar/Standard/CalendarViewPostProcess.tpl
  layouts/basic/modules/OSSTimeControl/CalendarViewPostProcess.tpl
  layouts/basic/modules/Reservations/CalendarViewPostProcess.tpl
  modules/OSSTimeControl/views/Calendar.php
  modules/Reservations/views/Calendar.php
  public_html/layouts/basic/styles/layout/_Nav.scss
  public_html/layouts/basic/styles/pages/_Calendar.scss
  public_html/layouts/resources/Fields.js
Labels: ✔ finished

#11610 Improved setReferenceFieldValue method
  public_html/layouts/basic/modules/Vtiger/resources/Edit.js
Labels: ✔ finished

#11623 Added variable to test config in developer file
  tests/setup/Developer.txt
Labels: ✔ finished

#11624 Improved chat
  public_html/layouts/basic/modules/Chat/Chat.vue.js
  public_html/layouts/basic/modules/Chat/Chat.vue.js.map
  public_html/layouts/basic/styles/components/_Utilities.scss
  public_html/layouts/resources/views/KnowledgeBase/KnowledgeBase.vue.js
  public_html/layouts/resources/views/KnowledgeBase/KnowledgeBase.vue.js.map
  public_html/src/components/DragResize.vue
  public_html/src/components/YfDrag.vue
  public_html/src/layouts/basic/modules/Chat/components/ChatContainer.vue
  public_html/src/layouts/basic/modules/Chat/components/ChatUpdateWatcher.vue
  public_html/src/layouts/basic/modules/Chat/components/Rooms/RoomList.vue
  public_html/src/layouts/basic/modules/Chat/components/Rooms/RoomPrivate.vue
  public_html/src/layouts/basic/modules/Chat/components/Tabs/TabChat.vue
  public_html/src/layouts/basic/modules/Chat/store/actions.js
  public_html/src/layouts/basic/modules/Chat/store/mutations.js
  public_html/src/layouts/basic/modules/Chat/views/Dialog.vue
  tests/Base/Z_Chat.php
Labels: ✔ finished

#11634 Displaying messages in chat right panel without html
  app/Chat.php
Labels: ✔ finished
