Repository YetiForceCompany/YetiForceCRM, pull requests merged in 2019-07, with the labels that each got.

#10846 Fixed #10835
  languages/en-US/Settings/Workflows.json
  layouts/basic/modules/Settings/Workflows/Step1.tpl
  modules/Settings/Workflows/views/Edit.php
  modules/com_vtiger_workflow/VTWorkflowManager.php
Labels: ✔ finished

#10791 Added translates for Help info
  languages/en-US/Other/HelpInfo.json
Labels: ✔ finished

#10830 Corrected a spacing in setting
  layouts/basic/modules/OSSMailView/index.tpl
  layouts/basic/modules/OSSPasswords/ConfigurePass.tpl
  layouts/basic/modules/Settings/Backup/Index.tpl
  layouts/basic/modules/Settings/BruteForce/Index.tpl
  layouts/basic/modules/Settings/Colors/Index.tpl
  layouts/basic/modules/Settings/Countries/Index.tpl
  layouts/basic/modules/Settings/CronTasks/ListViewContents.tpl
  layouts/basic/modules/Settings/FinancialProcesses/Index.tpl
  layouts/basic/modules/Settings/HideBlocks/EditView.tpl
  layouts/basic/modules/Settings/LangManagement/Index.tpl
  layouts/basic/modules/Settings/Leads/MappingDetail.tpl
  layouts/basic/modules/Settings/Log/Index.tpl
  layouts/basic/modules/Settings/Mail/Autologin.tpl
  layouts/basic/modules/Settings/Mail/DetailView.tpl
  layouts/basic/modules/Settings/Mail/ListViewContents.tpl
  layouts/basic/modules/Settings/MarketingProcesses/Index.tpl
  layouts/basic/modules/Settings/ModTracker/List.tpl
  layouts/basic/modules/Settings/Notifications/Configuration.tpl
  layouts/basic/modules/Settings/OSSMail/Index.tpl
  layouts/basic/modules/Settings/OSSMailScanner/Index.tpl
  layouts/basic/modules/Settings/Password/Encryption.tpl
  layouts/basic/modules/Settings/Picklist/PickListValueDetail.tpl
  layouts/basic/modules/Settings/Search/Index.tpl
  layouts/basic/modules/Settings/SocialMedia/Index.tpl
  layouts/basic/modules/Settings/SupportProcesses/Index.tpl
  layouts/basic/modules/Settings/TimeControlProcesses/Index.tpl
  layouts/basic/modules/Settings/Users/SwitchUsers.tpl
  layouts/basic/modules/Settings/Vtiger/SettingsIndexHeader.tpl
  layouts/basic/modules/Settings/WebserviceUsers/ListViewHeader.tpl
  layouts/basic/modules/Vtiger/DetailViewBlockLink.tpl
  layouts/basic/modules/Vtiger/ListViewActions.tpl
  layouts/basic/modules/Vtiger/ListViewHeader.tpl
  modules/Settings/MailSmtp/models/Record.php
Labels: ✔ finished

#10849 Moved new theme styles to new 'gray' theme
  layouts/basic/modules/Vtiger/DetailViewBlockLink.tpl
  layouts/basic/modules/Vtiger/ListViewActions.tpl
  layouts/basic/modules/Vtiger/ListViewHeader.tpl
  modules/Vtiger/helpers/Util.php
  public_html/layouts/basic/skins/gray/_Variables.scss
  public_html/layouts/basic/skins/gray/components/_Global.scss
  public_html/layouts/basic/skins/gray/layout/_Base.scss
  public_html/layouts/basic/skins/gray/layout/_Header.scss
  public_html/layouts/basic/skins/gray/layout/_Nav.scss
  public_html/layouts/basic/skins/gray/pages/_Dashboard.scss
  public_html/layouts/basic/skins/gray/pages/_Detail.scss
  public_html/layouts/basic/skins/gray/pages/_Edit.scss
  public_html/layouts/basic/skins/gray/style.css
  public_html/layouts/basic/skins/gray/style.css.map
  public_html/layouts/basic/skins/gray/style.scss
  public_html/layouts/basic/skins/twilight/style.css
  public_html/layouts/basic/styles/Main.css
  public_html/layouts/basic/styles/Main.css.map
  public_html/layouts/basic/styles/_Style.scss
  public_html/layouts/basic/styles/_Variables.scss
  public_html/layouts/basic/styles/components/_Global.scss
  public_html/layouts/basic/styles/components/_Utilities.scss
  public_html/layouts/basic/styles/layout/_Base.scss
  public_html/layouts/basic/styles/layout/_Header.scss
  public_html/layouts/basic/styles/layout/_Nav.scss
  public_html/layouts/basic/styles/pages/_Dashboard.scss
  public_html/layouts/basic/styles/pages/_Detail.scss
  public_html/layouts/basic/styles/pages/_Edit.scss
Labels: ✔ finished

#10851 Added minor improved to the fields from workflow tasks
  layouts/basic/modules/Settings/Workflows/Tasks/VTUpdateFieldsTask.tpl
  layouts/basic/modules/Settings/Workflows/Tasks/VTUpdateRelatedFieldTask.tpl
  modules/com_vtiger_workflow/tasks/VTUpdateFieldsTask.php
  modules/com_vtiger_workflow/tasks/VTUpdateRelatedFieldTask.php
Labels: ✔ finished

#10867 Added minor improvements
  include/CRMEntity.php
  modules/Assets/Assets.php
  modules/IStorages/textparsers/ProductsValueTable.php
  modules/OSSMailView/OSSMailView.php
  modules/OSSPasswords/OSSPasswords.php
  modules/OutsourcedProducts/OutsourcedProducts.php
  modules/Products/Products.php
  modules/Services/Services.php
Labels: ✔ finished

#10848 Optimization of communication between Portal2
  api/webservice/Portal/Products/Record.php
Labels: ✔ finished

#10866 Fixed discount amount value
  modules/Vtiger/inventoryfields/Discount.php
Labels: ✔ finished

#10850 Added missing file to git
  public_html/layouts/basic/skins/gray/pages/_Settings.scss
  public_html/layouts/basic/skins/gray/style.css
  public_html/layouts/basic/skins/gray/style.css.map
Labels: ✔ finished

#10845 Improving payments
  install/install_schema/data.sql
  languages/en-US/PaymentsIn.json
  modules/PaymentsIn/models/Module.php
  modules/PaymentsIn/models/PaymentStatus.php
Labels: ✔ finished

#10816 Added operators in DateFiled
  app/Conditions/RecordFields/DateField.php
Labels: 🔧 AmendmentsRequired

#10868 [IT598] - Improving translations in the Settings module
  layouts/basic/modules/Settings/BusinessHours/EditViewActions.tpl
  layouts/basic/modules/Settings/BusinessHours/ListViewContents.tpl
  layouts/basic/modules/Settings/Currency/ListViewContents.tpl
  layouts/basic/modules/Settings/Mail/ListViewContents.tpl
  layouts/basic/modules/Settings/MailSmtp/ListViewContents.tpl
  layouts/basic/modules/Settings/MappedFields/ListViewContents.tpl
  layouts/basic/modules/Settings/PDF/ListViewContents.tpl
  layouts/basic/modules/Settings/Profiles/ListViewContents.tpl
  layouts/basic/modules/Settings/TreesManager/ListViewContents.tpl
  layouts/basic/modules/Settings/Vtiger/ListView/TableHeader.tpl
  layouts/basic/modules/Settings/Vtiger/ListViewContents.tpl
  modules/Settings/AutomaticAssignment/models/Module.php
  modules/Settings/BusinessHours/views/List.php
  modules/Settings/SlaPolicy/models/Module.php
  modules/Settings/Vtiger/models/ListView.php
  modules/Settings/Vtiger/models/Module.php
  modules/Settings/Vtiger/views/List.php
  modules/Settings/WebserviceUsers/models/Module.php
  modules/Settings/Workflows/models/Module.php
Labels: ✔ finished

#9970 [IT545] - CalDAV refactoring the code
  app/Integrations/Dav/Calendar.php
  modules/API/models/CalDAV.php
Labels: 👮‍♂️ VerificationRequired

#10870 [IT601] - Adding a link to the email template
  modules/OSSMailScanner/models/Record.php
Labels: ✔ finished

#10684 Multiemail field issues
  modules/Vtiger/models/ExportToXml.php
  modules/Vtiger/uitypes/MultiEmail.php
  public_html/layouts/basic/styles/Main.css
  public_html/layouts/resources/Fields.js
Labels: 🔧 AmendmentsRequired

#10874 Cleaned code im MultEmail field after #10684
  layouts/basic/modules/Vtiger/Edit/Field/MultiEmailValue.tpl
  public_html/layouts/basic/styles/Main.css
  public_html/layouts/basic/styles/Main.css.map
  public_html/layouts/basic/styles/components/_Global.scss
  public_html/layouts/basic/styles/components/_Utilities.scss
  public_html/layouts/resources/Fields.js
Labels: ✔ finished

#10879 Added pdf action to related list of records
  modules/Vtiger/models/Record.php
Labels: ✔ finished

#9857 Improved Record Converter
  app/RecordConverter.php
  install/install_schema/scheme.sql
  languages/en-US/_Base.json
  layouts/basic/modules/Vtiger/Modals/RecordConverter.tpl
  modules/Vtiger/actions/RecordConverter.php
  modules/Vtiger/models/DetailView.php
  modules/Vtiger/models/ListView.php
  modules/Vtiger/views/Edit.php
  modules/Vtiger/views/RecordConverter.php
  public_html/layouts/basic/modules/Vtiger/resources/RecordConverter.js
Labels: ⏸ Not Finished

#10877 [IT494] - Transfer of the list of requirements to the beginning of the installer
  api/webservice/Portal/Products/Record.php
  app/Utils/ConfReport.php
  install/tpl/StepCompanyDetails.tpl
  install/tpl/StepConfirmConfigurationSettings.tpl
  install/tpl/StepInstall.tpl
  install/tpl/StepLicense.tpl
  install/tpl/StepSystemConfiguration.tpl
  install/tpl/StepVerifyServerConfiguration.tpl
  install/tpl/StepWelcome.tpl
  install/views/Index.php
Labels: ✔ finished

#10872 [IT587] - Setting the maximum length for the MultiSelectCombo field
  install/install_schema/data.sql
  layouts/basic/modules/Vtiger/Edit/Field/Base.tpl
  layouts/basic/modules/Vtiger/Edit/Field/Text.tpl
  modules/Settings/LayoutEditor/actions/Field.php
  modules/Settings/LayoutEditor/models/Module.php
  modules/Settings/Mail/actions/MassDelete.php
  modules/Vtiger/models/Field.php
  modules/Vtiger/uitypes/Base.php
Labels: ✔ finished

#10887 Improving the installer
  install/models/InitSchema.php
  install/tpl/StepCompanyDetails.tpl
  install/tpl/StepVerifyServerConfiguration.tpl
  install/views/Index.php
  public_html/install/tpl/resources/Index.js
Labels: ✔ finished

#10895 Added automatically copy fields in record converter
  app/RecordConverter.php
  install/install_schema/scheme.sql
Labels: ✔ finished

#10896 [IT586] Fixed deleting related records in Campaings
  public_html/layouts/basic/modules/Vtiger/resources/RelatedList.js
Labels: ✔ finished

#10031 [IT549] Automatic status changes, global mechanism
  app/Automatic/RecordFlowUpdater.php
  app/Automatic/Rules.php
  app/Automatic/RulesPicklist.php
  install/install_schema/data.sql
  install/install_schema/scheme.sql
  modules/Project/handlers/ProjectHandler.php
  modules/ProjectMilestone/models/Module.php
  modules/ProjectTask/handlers/ProjectTaskHandler.php
  modules/Vtiger/handlers/RecordFlowUpdater.php
  tests/Base/J_RecordFlowUpdater.php
Labels: ✔ finished

#10899 Fixed layout bugs
  layouts/basic/modules/Vtiger/DetailViewHeader.tpl
  layouts/basic/modules/Vtiger/ListViewPreProcess.tpl
  layouts/basic/modules/Vtiger/WorkflowTrigger.tpl
  public_html/layouts/basic/styles/layout/_Header.scss
Labels: ✔ finished

#10900 Fixed searching in list for related fields for reference field
  app/Conditions/QueryFields/ReferenceField.php
Labels: 🔧 AmendmentsRequired

#10901 Fixed select2 loading bugs
  layouts/basic/modules/Vtiger/DetailViewHeader.tpl
  layouts/basic/modules/Vtiger/ListViewPreProcess.tpl
  public_html/layouts/basic/styles/libraries/_Libraries.scss
  public_html/layouts/basic/styles/libraries/_Quasar.scss
Labels: ✔ finished

#10902 Improving RecordFlowUpdater
  app/Automatic/RecordFlowUpdater.php
  tests/Base/J_RecordFlowUpdater.php
Labels: ✔ finished

#10905 [IT597] Fixed errors after deleted product in detail advanced block
  modules/Vtiger/inventoryfields/Unit.php
  modules/Vtiger/inventoryfields/Value.php
Labels: ✔ finished

#10906 Record Converter fixed counting created records amount
  app/RecordConverter.php
Labels: ⏸ Not Finished

#10907 Record converter fixed process editing
  app/RecordConverter.php
Labels: ✔ finished

#10912 [IT597] Removed invalid code
  modules/Vtiger/inventoryfields/Unit.php
  modules/Vtiger/inventoryfields/Value.php
Labels: ✔ finished

#10909 Fixed calendar popover
  public_html/layouts/basic/styles/pages/_Calendar.scss
  public_html/layouts/resources/app.js
Labels: ✔ finished

#10910 PHP-cs-fixer, sonarcloud, correct comments
  app/Fields/TimePeriod.php
  install/models/Utils.php
  modules/Calendar/models/Module.php
  modules/Documents/models/Module.php
  modules/HolidaysEntitlement/models/Module.php
  modules/PriceBooks/models/Module.php
  modules/Products/models/Module.php
  modules/SMSNotifier/models/Module.php
  modules/Settings/MappedFields/models/Field.php
  modules/Settings/Users/views/Detail.php
  modules/Settings/Vtiger/models/Field.php
  modules/Users/models/Field.php
  modules/Vendors/models/Record.php
  modules/Vtiger/inventoryfields/Basic.php
  modules/Vtiger/models/Field.php
  modules/Vtiger/models/Module.php
  modules/Vtiger/models/Paging.php
  modules/Vtiger/models/Record.php
Labels: ✔ finished

#10922 Fixed breadcrumb hover [IT426]
  public_html/layouts/basic/styles/layout/_Header.scss
Labels: ✔ finished

#10925 [IT603] - Deactivate the private field.
  install/install_schema/data.sql
Labels: ✔ finished

#10924 Added minor fixes
  api/webservice/Portal/Products/Record.php
  layouts/basic/modules/Settings/Workflows/CreateEntity.tpl
Labels: ✔ finished

#10920 [IT600] Corrected a additional variable ProductsControlTable
  modules/IStorages/textparsers/ProductsControlTable.php
Labels: ✔ finished

#10928 php-cs-fixer and improving phpdoc comments
  modules/Vtiger/models/Field.php
  modules/Vtiger/models/RecordStructure.php
Labels: ✔ finished

#10929 [IT600] Corrected a additional variable ProductsTable
  modules/IStorages/textparsers/ProductsTable.php
Labels: ✔ finished

#10930 Improved mass actions in calendar
  install/install_schema/data.sql
  modules/Calendar/models/ListView.php
  modules/Vtiger/actions/QuickExport.php
Labels: ✔ finished

#10897 Rewrote and improved chat with quasar
  app/Chat.php
  app/Controller/View.php
  languages/en-US/_Base.json
  layouts/basic/modules/Vtiger/BodyHeader.tpl
  layouts/basic/modules/Vtiger/Footer.tpl
  modules/Chat/actions/ChatAjax.php
  modules/Chat/actions/Room.php
  modules/Chat/views/Entries.php
  modules/Chat/views/Modal.php
  modules/Vtiger/views/Detail.php
  public_html/layouts/basic/modules/Chat/Chat.vue.js
  public_html/layouts/basic/modules/Chat/Chat.vue.js.map
  public_html/layouts/basic/modules/Chat/resources/Chat.js
  public_html/layouts/basic/modules/Chat/resources/Modal.js
  public_html/layouts/basic/modules/Chat/resources/Modal.min.js
  public_html/layouts/basic/modules/Chat/resources/Modal.min.js.map
  public_html/layouts/basic/modules/Vtiger/resources/Detail.js
  public_html/layouts/basic/modules/Vtiger/resources/Header.js
  public_html/layouts/basic/styles/Main.css
  public_html/layouts/basic/styles/Main.css.map
  public_html/layouts/basic/styles/components/_Buttons.scss
  public_html/layouts/basic/styles/layout/_Base.scss
  public_html/layouts/basic/styles/libraries/_Quasar.scss
  public_html/layouts/resources/Fields.js
  public_html/layouts/resources/views/KnowledgeBase/KnowledgeBase.vue.js
  public_html/layouts/resources/views/KnowledgeBase/KnowledgeBase.vue.js.map
  public_html/src/components/Backdrop.vue
  public_html/src/components/NoResults.vue
  public_html/src/css/quasar.css
  public_html/src/css/quasar.styl
  public_html/src/layouts/basic/modules/Chat/Chat.js
  public_html/src/layouts/basic/modules/Chat/components/Chat.vue
  public_html/src/layouts/basic/modules/Chat/components/ChatFooter.vue
  public_html/src/layouts/basic/modules/Chat/components/ChatHeader.vue
  public_html/src/layouts/basic/modules/Chat/components/ChatTab.vue
  public_html/src/layouts/basic/modules/Chat/components/Dialog.vue
  public_html/src/layouts/basic/modules/Chat/components/History.vue
  public_html/src/layouts/basic/modules/Chat/components/LeftPanel.vue
  public_html/src/layouts/basic/modules/Chat/components/MainPanel.vue
  public_html/src/layouts/basic/modules/Chat/components/MessageInput.vue
  public_html/src/layouts/basic/modules/Chat/components/Messages.vue
  public_html/src/layouts/basic/modules/Chat/components/NotifyBtn.vue
  public_html/src/layouts/basic/modules/Chat/components/RightPanel.vue
  public_html/src/layouts/basic/modules/Chat/components/Unread.vue
  public_html/src/layouts/basic/modules/Chat/store/actions.js
  public_html/src/layouts/basic/modules/Chat/store/getters.js
  public_html/src/layouts/basic/modules/Chat/store/index.js
  public_html/src/layouts/basic/modules/Chat/store/mutations.js
  public_html/src/layouts/basic/modules/Chat/store/state.js
  public_html/src/layouts/basic/modules/Chat/utils/utils.js
  public_html/src/layouts/resources/views/KnowledgeBase/KnowledgeBase.vue
  public_html/src/layouts/resources/views/KnowledgeBase/KnowledgeBaseModal.vue
  public_html/src/layouts/resources/views/KnowledgeBase/components/ArticlePreviewContent.vue
  public_html/src/layouts/resources/views/KnowledgeBase/components/DragResize.vue
  public_html/src/package.json
  public_html/src/rollup.js
  public_html/src/store/index.js
  public_html/src/yarn.lock
  tests/Base/Z_Chat.php
Labels: ✔ finished

#10935 Updated compiled js/css files
  public_html/install/tpl/resources/Index.min.js
  public_html/install/tpl/resources/Index.min.js.map
  public_html/layouts/basic/modules/Chat/resources/Chat.min.js
  public_html/layouts/basic/modules/Chat/resources/Chat.min.js.map
  public_html/layouts/basic/modules/ServiceContracts/resources/Detail.min.js
  public_html/layouts/basic/modules/ServiceContracts/resources/Detail.min.js.map
  public_html/layouts/basic/modules/Settings/LayoutEditor/resources/LayoutEditor.min.js
  public_html/layouts/basic/modules/Settings/LayoutEditor/resources/LayoutEditor.min.js.map
  public_html/layouts/basic/modules/Settings/SLAPolicy/resources/Edit.min.js
  public_html/layouts/basic/modules/Settings/SLAPolicy/resources/Edit.min.js.map
  public_html/layouts/basic/modules/Settings/WebserviceApps/resources/WebserviceApps.min.js
  public_html/layouts/basic/modules/Settings/WebserviceApps/resources/WebserviceApps.min.js.map
  public_html/layouts/basic/modules/Settings/Workflows/resources/AdvanceFilter.min.js
  public_html/layouts/basic/modules/Settings/Workflows/resources/AdvanceFilter.min.js.map
  public_html/layouts/basic/modules/Users/resources/List.min.js
  public_html/layouts/basic/modules/Users/resources/List.min.js.map
  public_html/layouts/basic/modules/Vtiger/resources/ConditionBuilder.min.js
  public_html/layouts/basic/modules/Vtiger/resources/ConditionBuilder.min.js.map
  public_html/layouts/basic/modules/Vtiger/resources/DashBoard.min.js
  public_html/layouts/basic/modules/Vtiger/resources/DashBoard.min.js.map
  public_html/layouts/basic/modules/Vtiger/resources/Detail.min.js
  public_html/layouts/basic/modules/Vtiger/resources/Detail.min.js.map
  public_html/layouts/basic/modules/Vtiger/resources/Edit.min.js
  public_html/layouts/basic/modules/Vtiger/resources/Edit.min.js.map
  public_html/layouts/basic/modules/Vtiger/resources/Header.min.js
  public_html/layouts/basic/modules/Vtiger/resources/Header.min.js.map
  public_html/layouts/basic/modules/Vtiger/resources/Inventory.min.js
  public_html/layouts/basic/modules/Vtiger/resources/Inventory.min.js.map
  public_html/layouts/basic/modules/Vtiger/resources/List.min.js
  public_html/layouts/basic/modules/Vtiger/resources/List.min.js.map
  public_html/layouts/basic/modules/Vtiger/resources/RecordConverter.min.js
  public_html/layouts/basic/modules/Vtiger/resources/RecordConverter.min.js.map
  public_html/layouts/basic/modules/Vtiger/resources/RelatedList.min.js
  public_html/layouts/basic/modules/Vtiger/resources/RelatedList.min.js.map
  public_html/layouts/basic/modules/Vtiger/resources/dashboards/Widget.min.js
  public_html/layouts/basic/modules/Vtiger/resources/dashboards/Widget.min.js.map
  public_html/layouts/basic/styles/Main.css
  public_html/layouts/basic/styles/Main.css.map
  public_html/layouts/resources/Connector.min.js
  public_html/layouts/resources/Connector.min.js.map
  public_html/layouts/resources/Fields.min.js
  public_html/layouts/resources/Fields.min.js.map
  public_html/layouts/resources/app.min.js
  public_html/layouts/resources/app.min.js.map
  public_html/layouts/resources/validator/FieldValidator.min.js
  public_html/layouts/resources/validator/FieldValidator.min.js.map
Labels: ✔ finished

#10948 Improved mass action in PriceBooks
  public_html/layouts/basic/modules/PriceBooks/resources/RelatedList.js
Labels: ✔ finished

#10953 [IT593] - Removing the duplicated field on contact
  install/install_schema/data.sql
  install/install_schema/scheme.sql
Labels: ✔ finished

#10952 Fixed Notice: Undefined variable
  modules/Vtiger/inventoryfields/Value.php
Labels: ✔ finished

#10951 Improving tests
  tests/Base/J_RecordFlowUpdater.php
Labels: ✔ finished

#10946 [IT600] Corrected a additional variable List [Time Control]
  modules/OSSTimeControl/textparsers/List.php
Labels: ✔ finished

#10936 [IT600] Corrected a additional variable DetailedList [Time Control]
  modules/OSSTimeControl/textparsers/DetailedList.php
Labels: ✔ finished

#10933 [IT600] Corrected a additional variable ProductsValueTable
  modules/IStorages/textparsers/ProductsValueTable.php
Labels: ✔ finished

#10911 IT599 Improved filter conditions
  app/Conditions/QueryFields/MultiDomainField.php
  languages/en-US/_Base.json
  layouts/basic/modules/Settings/Workflows/AdvanceFilterCondition.tpl
  layouts/basic/modules/Vtiger/ConditionBuilder/Smtp.tpl
  modules/Settings/Workflows/views/Edit.php
  modules/Vtiger/helpers/AdvancedFilter.php
  modules/Vtiger/uitypes/MultiDomain.php
  modules/Vtiger/uitypes/Smtp.php
  modules/Vtiger/views/ConditionBuilder.php
Labels: ✔ finished

#10932 [IT600] Corrected a additional variable ProductsTableHierarchy
  modules/IStorages/textparsers/ProductsTableHierarchy.php
Labels: ✔ finished

#10949 Shop module
  app/YetiForce/Shop.php
  app/YetiForce/Shop/AbstractBaseProduct.php
  app/YetiForce/Shop/Product/Donations.php
  app/YetiForce/Shop/Product/PremiumModules.php
  app/YetiForce/Shop/Product/PremiumSupport.php
  install/install_schema/data.sql
  languages/en-US/Settings/YetiForce.json
  layouts/basic/modules/Settings/YetiForce/Shop.tpl
  layouts/basic/modules/Settings/YetiForce/Shop/Product.tpl
Labels: ✔ finished

#10959 Shop module - adding a missing file
  modules/Settings/YetiForce/views/Shop.php
Labels: ✔ finished

#10962 Removed convert faq button in help desk
  languages/en-US/HelpDesk.json
  modules/HelpDesk/models/DetailView.php
  modules/HelpDesk/models/Record.php
Labels: ✔ finished

#10963 Improving the store
  app/YetiForce/Shop.php
  app/YetiForce/Shop/AbstractBaseProduct.php
  languages/en-US/Settings/YetiForce.json
  languages/en-US/Settings/_Base.json
  layouts/basic/modules/Settings/YetiForce/Shop.tpl
  layouts/basic/modules/Settings/YetiForce/Shop/Product.tpl
  public_html/modules/Settings/YetiForce/DisableFooter.png
  public_html/modules/Settings/YetiForce/Donations.png
  public_html/modules/Settings/YetiForce/PremiumModules.png
  public_html/modules/Settings/YetiForce/PremiumSupport.png
Labels: ▶ in progress

#10950 [IT594] Fixed adding new records and pagination in hide blocks module
  layouts/basic/modules/Settings/HideBlocks/ListViewHeader.tpl
  public_html/layouts/basic/modules/Settings/HideBlocks/resources/Conditions.js
Labels: ✔ finished

#10980 #10811 Fixed getting links after disabled MailScanner module
  modules/OSSMailScanner/models/Module.php
Labels: ✔ finished

#10994 Improving the view of the store
  app/YetiForce/Shop/AbstractBaseProduct.php
  languages/en-US/Settings/YetiForce.json
  layouts/basic/modules/Settings/YetiForce/Shop/Product.tpl
Labels: ✔ finished

#10965 Improved and refactored Chat
  app/Chat.php
  app/Utils/Completions.php
  languages/en-US/_Base.json
  layouts/basic/modules/Chat/Modal.tpl
  layouts/basic/modules/Chat/ModalFooter.tpl
  layouts/basic/modules/Chat/ModalHeader.tpl
  layouts/basic/modules/Chat/Unread.tpl
  modules/Chat/actions/ChatAjax.php
  public_html/layouts/basic/modules/Chat/Chat.vue.js
  public_html/layouts/basic/modules/Chat/Chat.vue.js.map
  public_html/layouts/basic/modules/Chat/resources/Chat.js
  public_html/layouts/resources/views/KnowledgeBase/KnowledgeBase.vue.js
  public_html/layouts/resources/views/KnowledgeBase/KnowledgeBase.vue.js.map
  public_html/src/components/DragResize.vue
  public_html/src/layouts/basic/modules/Chat/Chat.js
  public_html/src/layouts/basic/modules/Chat/components/Chat.vue
  public_html/src/layouts/basic/modules/Chat/components/ChatFooter.vue
  public_html/src/layouts/basic/modules/Chat/components/ChatHeader.vue
  public_html/src/layouts/basic/modules/Chat/components/ChatTab.vue
  public_html/src/layouts/basic/modules/Chat/components/Dialog.vue
  public_html/src/layouts/basic/modules/Chat/components/History.vue
  public_html/src/layouts/basic/modules/Chat/components/MessageInput.vue
  public_html/src/layouts/basic/modules/Chat/components/NotifyBtn.vue
  public_html/src/layouts/basic/modules/Chat/store/actions.js
  public_html/src/layouts/basic/modules/Chat/store/getters.js
  public_html/src/layouts/basic/modules/Chat/store/mutations.js
  public_html/src/layouts/basic/modules/Chat/store/state.js
  public_html/src/layouts/resources/views/KnowledgeBase/KnowledgeBaseModal.vue
  public_html/src/layouts/resources/views/KnowledgeBase/components/ArticlePreview.vue
  tests/Base/Z_Chat.php
Labels: ✔ finished

#10996 Update tests/setup/Api.txt file
  tests/setup/Api.txt
Labels: ✔ finished

#10995 Removed table vtiger_seticketsrel
  install/install_schema/data.sql
  install/install_schema/scheme.sql
  vtlib/Vtiger/Functions.php
Labels: ✔ finished

#10993 Restore search_fields_name values in Users module
  modules/Users/Users.php
Labels: ✔ finished

#10992 [IT624] Improved saving create entity task in workflows
  layouts/basic/modules/Settings/Workflows/CreateEntity.tpl
  public_html/layouts/basic/modules/Settings/Workflows/resources/Edit3.js
Labels: ✔ finished

#10976 #10127 Fixed conditions for currencyInventory fields
  modules/Vtiger/helpers/AdvancedFilter.php
Labels: ✔ finished

#10975 Added columns in list views
  install/install_schema/data.sql
Labels: ✔ finished

#10961 Fixed mass sms modal window
  layouts/basic/modules/Vtiger/SendSMSForm.tpl
Labels: ✔ finished

#10957 Improved getting project milestone record list
  public_html/layouts/basic/modules/ProjectTask/resources/Edit.js
Labels: ✔ finished

#11001 Fixed #10754
  include/CRMEntity.php
  include/utils/VTCacheUtils.php
  modules/Users/Users.php
  modules/Vtiger/models/Field.php
  vtlib/Vtiger/Deprecated.php
Labels: ✔ finished

#11003 Deleted columns modifiedby, modifiedtime from vtiger_tab
  install/install_schema/data.sql
  install/install_schema/scheme.sql
  vtlib/Vtiger/ModuleBasic.php
Labels: ✔ finished

#10956 [IT623] Added summary view in Service Contracts module
  install/install_schema/data.sql
  install/install_schema/scheme.sql
Labels: ✔ finished

#11012 Added minor improvements in bar actions on mail preview (YetiForceCom…
  languages/en-US/OSSMail.json
  layouts/basic/modules/OSSMail/MailActionBar.tpl
Labels: ✔ finished

#11004 Fixed and improved chat
  app/Chat.php
  public_html/layouts/basic/modules/Chat/Chat.vue.js
  public_html/layouts/basic/modules/Chat/Chat.vue.js.map
  public_html/layouts/resources/views/KnowledgeBase/KnowledgeBase.vue.js
  public_html/layouts/resources/views/KnowledgeBase/KnowledgeBase.vue.js.map
  public_html/src/components/BtnGrab.vue
  public_html/src/layouts/basic/modules/Chat/components/ChatHeader.vue
  public_html/src/layouts/basic/modules/Chat/store/actions.js
  public_html/src/layouts/basic/modules/Chat/store/getters.js
  public_html/src/layouts/resources/views/KnowledgeBase/KnowledgeBaseModal.vue
  tests/Base/Z_Chat.php
Labels: 🔧 AmendmentsRequired

#11021 Improved settings' dashboard
  layouts/basic/modules/Settings/Vtiger/DashBoard/PremiumZone.tpl
  layouts/basic/modules/Settings/Vtiger/DashBoard/SettingsShortCut.tpl
  layouts/basic/modules/Settings/Vtiger/DashBoard/SettingsShortCutsContainer.tpl
  layouts/basic/modules/Settings/Vtiger/DashBoard/SystemMonitoring.tpl
  layouts/basic/modules/Settings/Vtiger/Index.tpl
  layouts/basic/modules/Settings/YetiForce/Shop/SmallProduct.tpl
  modules/Settings/Vtiger/views/Index.php
  modules/Settings/Vtiger/views/IndexAjax.php
  public_html/layouts/basic/modules/Settings/Vtiger/resources/Index.js
  public_html/layouts/basic/skins/gray/components/_Global.scss
  public_html/layouts/basic/skins/gray/pages/_Dashboard.scss
  public_html/layouts/basic/skins/gray/style.css
  public_html/layouts/basic/skins/gray/style.css.map
  public_html/layouts/basic/styles/Main.css
  public_html/layouts/basic/styles/Main.css.map
  public_html/layouts/basic/styles/Main.scss
  public_html/layouts/basic/styles/_Style.scss
  public_html/layouts/basic/styles/components/_Global.scss
  public_html/layouts/basic/styles/components/_Utilities.scss
  public_html/layouts/basic/styles/pages/_Dashboard.scss
Labels: ✔ finished

#11019 Fixed getting query operators for date uitype
  modules/Vtiger/uitypes/Date.php
Labels: ✔ finished

#11008 Fixed adding comments
  layouts/basic/modules/Vtiger/Comment.tpl
  public_html/layouts/basic/modules/Vtiger/resources/Detail.js
Labels: ✔ finished

#11014 Improved read conditions from filters (#10788)
  app/CustomView.php
  layouts/basic/modules/Vtiger/ConditionBuilderRow.tpl
  modules/Vtiger/models/Field.php
Labels: ✔ finished

#11024 Added lacking files to git
  layouts/basic/modules/Settings/Vtiger/DashBoard/WidgetDescription.tpl
  layouts/basic/modules/Settings/Vtiger/DashBoard/WidgetTitle.tpl
Labels: ✔ finished

#11023 Improve the SystemWarnings module
  install/install_schema/data.sql
  layouts/basic/modules/Settings/Logs/Index.tpl
  layouts/basic/modules/Settings/Logs/SystemWarnings.tpl
  layouts/basic/modules/Settings/Logs/SystemWarningsList.tpl
  modules/Settings/Logs/views/SystemWarnings.php
  public_html/layouts/basic/modules/Settings/Logs/resources/Index.js
  public_html/layouts/basic/modules/Settings/Vtiger/resources/Index.js
Labels: ✔ finished

#11026 Added the autocomplete time control name
  app_data/moduleHierarchy.php
Labels: ✔ finished

#11025 Improve comments
  public_html/layouts/basic/modules/Vtiger/resources/Detail.js
Labels: ✔ finished

#11015 [IT600] Corrected a additional variable ProductsTableRelatedModule
  app/TextParser/ProductsTableRelatedModule.php
Labels: ✔ finished

#11009 [IT600] Corrected a additional variable ProductsTableLongVTwoLang
  app/TextParser/ProductsTableLongVTwoLang.php
Labels: ✔ finished

#11005 [IT600] Corrected a additional variable ProductsTableImages
  app/TextParser/ProductsTableImages.php
Labels: ✔ finished

#10998 [IT600] Corrected a additional variable ProductsTableShortVersion
  app/TextParser/ProductsTableShortVersion.php
Labels: ✔ finished

#10997 [IT600] Corrected a additional variable ProductsTableLongVersion
  app/TextParser/ProductsTableLongVersion.php
Labels: ✔ finished

#10981 [IT600] Corrected a additional variable ProductsTableCorrectingBefore
  app/TextParser/ProductsTableCorrectingBefore.php
Labels: ✔ finished

#10966 [IT600] Corrected a additional variable ProductsTable
  app/TextParser/ProductsTable.php
Labels: ✔ finished

#10960 [IT600] Corrected a additional variable OverdueDeadlines
  app/TextParser/OverdueDeadlines.php
Labels: ✔ finished

#11028 Improved settings' dashboard
  .gitignore
  layouts/basic/modules/Settings/Vtiger/DashBoard/SettingsShortCut.tpl
  layouts/basic/modules/Settings/Vtiger/DashBoard/SystemMonitoring.tpl
  layouts/basic/modules/Settings/Vtiger/ReAlignSettingsShortCut.tpl
  layouts/basic/modules/Settings/YetiForce/Shop/Product.tpl
  layouts/basic/modules/Settings/YetiForce/Shop/SmallProduct.tpl
  public_html/layouts/basic/modules/Settings/Vtiger/resources/Index.js
Labels: ✔ finished

#11030 Corrected multi select in record import (step 3)
  layouts/basic/modules/Import/Import_Step3.tpl
Labels: ✔ finished

#11029 Corrected Notice saving the mapping template during import
  modules/Import/views/Main.php
Labels: ✔ finished

#11027 Removed unnecessary functions
  modules/Settings/Groups/models/Member.php
  modules/Settings/SharingAccess/models/Rule.php
  modules/Settings/SharingAccess/models/RuleMember.php
Labels: ✔ finished

#11038 Improved settings' dashboard
  languages/en-US/Settings/_Base.json
  layouts/basic/modules/Settings/Vtiger/DashBoard/PartnerZone.tpl
  layouts/basic/modules/Settings/Vtiger/DashBoard/SettingsShortCut.tpl
  layouts/basic/modules/Settings/Vtiger/DashBoard/SettingsShortCutsContainer.tpl
  layouts/basic/modules/Settings/Vtiger/DashBoard/SystemMonitoring.tpl
  layouts/basic/modules/Settings/Vtiger/Index.tpl
  layouts/basic/modules/Settings/YetiForce/Shop/SmallProduct.tpl
  modules/Settings/Vtiger/views/Index.php
  public_html/layouts/basic/modules/Settings/Vtiger/resources/Index.js
  public_html/layouts/basic/styles/Main.css
  public_html/layouts/basic/styles/Main.css.map
  public_html/layouts/basic/styles/_Variables.scss
  public_html/layouts/basic/styles/components/_Utilities.scss
  public_html/src/css/quasar.css
Labels: ✔ finished

#11039 Added information in the ConfReport
  app/Utils/ConfReport.php
Labels: ✔ finished

#11042 Improved ExceptionError.tpl styles and js
  layouts/basic/modules/Vtiger/ExceptionError.tpl
  public_html/layouts/basic/styles/Main.css
  public_html/layouts/basic/styles/Main.css.map
  public_html/layouts/basic/styles/layout/_Base.scss
Labels: ✔ finished

#11043 Improved shop and dashboard
  layouts/basic/modules/Settings/Vtiger/DashBoard/SystemMonitoring.tpl
  layouts/basic/modules/Settings/Vtiger/Index.tpl
  layouts/basic/modules/Settings/YetiForce/Shop.tpl
  modules/Settings/YetiForce/views/Shop.php
Labels: ✔ finished

#11044 Added translation in setting summary
  languages/en-US/Settings/YetiForce.json
  languages/en-US/Settings/_Base.json
Labels: ✔ finished

#11045 Added labels for translation
  languages/en-US/Settings/_Base.json
Labels: ✔ finished

#11047 Added translation in FInvoice
  languages/en-US/FInvoice.json
  languages/en-US/SSingleOrders.json
Labels: ✔ finished

#11050 Corrected module import
  vtlib/Vtiger/PackageImport.php
Labels: ✔ finished

#11051 Corrected notice Undefined variable in Unit.php
  modules/Vtiger/inventoryfields/Unit.php
Labels: ✔ finished

#11055 Fixed #11046
  install/install_schema/scheme.sql
Labels: ✔ finished

#11054 Added preview modal and buy modal to the shop
  app/Controller/Modal.php
  app/YetiForce/Shop.php
  app/YetiForce/Shop/AbstractBaseProduct.php
  languages/en-US/Settings/YetiForce.json
  layouts/basic/modules/Settings/YetiForce/BuyModal.tpl
  layouts/basic/modules/Settings/YetiForce/ProductModal.tpl
  layouts/basic/modules/Settings/YetiForce/Shop.tpl
  layouts/basic/modules/Settings/YetiForce/Shop/Product.tpl
  layouts/basic/modules/Vtiger/Modals/Footer.tpl
  modules/Settings/YetiForce/views/BuyModal.php
  modules/Settings/YetiForce/views/ProductModal.php
  modules/Settings/YetiForce/views/Shop.php
  public_html/layouts/basic/modules/Settings/YetiForce/resources/Shop.js
Labels: ✔ finished

#11040 Calculate the time of execution in the hierarchy
  install/install_schema/data.sql
  install/install_schema/scheme.sql
  modules/OSSTimeControl/models/Record.php
  modules/OSSTimeControl/models/TimeCounting.php
  modules/Vtiger/models/Field.php
  modules/com_vtiger_workflow/tasks/VTUpdateWorkTime.php
Labels: ✔ finished

#11056 Improved dashboard and shop
  languages/en-US/Settings/YetiForce.json
  layouts/basic/modules/Settings/Vtiger/Index.tpl
  layouts/basic/modules/Settings/YetiForce/BuyModal.tpl
  layouts/basic/modules/Settings/YetiForce/ProductModal.tpl
  layouts/basic/modules/Settings/YetiForce/Shop/Product.tpl
Labels: ✔ finished

#11058 Clean database
  install/install_schema/data.sql
  install/install_schema/scheme.sql
Labels: ✔ finished

#11061 Improved settings' dashboard
  layouts/basic/modules/Settings/Vtiger/DashBoard/SettingsShortCut.tpl
  layouts/basic/modules/Settings/Vtiger/DashBoard/SettingsShortCutsContainer.tpl
  layouts/basic/modules/Settings/Vtiger/Index.tpl
  layouts/basic/modules/Settings/YetiForce/BuyModal.tpl
  layouts/basic/modules/Settings/YetiForce/ProductModal.tpl
  layouts/basic/modules/Settings/YetiForce/Shop/Product.tpl
  layouts/basic/modules/Settings/YetiForce/Shop/SmallProduct.tpl
  modules/Settings/Vtiger/views/Index.php
  modules/Settings/YetiForce/views/ProductModal.php
  public_html/layouts/basic/modules/Settings/Vtiger/resources/Index.js
  public_html/layouts/basic/modules/Settings/YetiForce/resources/Shop.js
  public_html/layouts/basic/styles/Main.css
  public_html/layouts/basic/styles/Main.css.map
  public_html/layouts/basic/styles/components/_Utilities.scss
Labels: ✔ finished

#11063 Improved opcache
  app/Cache.php
Labels: ▶ in progress

#11049 Added tickets closing validation
  languages/en-US/HelpDesk.json
  modules/HelpDesk/ConfigTemplate.php
  modules/HelpDesk/actions/CheckValidateToClose.php
  modules/HelpDesk/models/Record.php
  modules/HelpDesk/views/Detail.php
  modules/HelpDesk/views/Edit.php
  public_html/layouts/basic/modules/HelpDesk/resources/Detail.js
  public_html/layouts/basic/modules/HelpDesk/resources/Edit.js
Labels: ✔ finished

#11065 Clear opcache
  app/UserPrivilegesFile.php
Labels: ✔ finished

#11070 Added minor improvements
  app/RecordStatus.php
  install/install_schema/data.sql
  install/install_schema/scheme.sql
  modules/ModComments/ModComments.php
Labels: ✔ finished

#11066 Added translation and corrected displaying the value
  app/Utils/ConfReport.php
  languages/en-US/Settings/ConfReport.json
  layouts/basic/modules/Settings/ConfReport/Index.tpl
Labels: ✔ finished

#11068 Added payment data to company details
  install/install_schema/data.sql
  install/install_schema/scheme.sql
  languages/en-US/Settings/Companies.json
  layouts/basic/modules/Settings/Companies/Form.tpl
  modules/Settings/Companies/models/Module.php
  modules/Settings/Companies/models/Record.php
Labels: ✔ finished

#11071 Corrected url validation and company form
  layouts/basic/modules/Settings/Companies/Form.tpl
  layouts/basic/modules/Vtiger/Edit/Field/Url.tpl
Labels: ✔ finished

#11072 Added occurrence parameter html
  layouts/basic/modules/Settings/ConfReport/Index.tpl
Labels: ✔ finished

#11073 Fixed save price in pricebook
  public_html/layouts/basic/modules/PriceBooks/resources/RelatedList.js
Labels: ✔ finished

#11078 Improved test and cleaning of opcache
  app/PrivilegeAdvanced.php
  app/UserPrivilegesFile.php
  modules/Settings/ModuleManager/models/Module.php
  tests/Settings/ModuleManager.php
Labels: ▶ in progress

#11079 Added minor fixes in advanced blocks
  api/webservice/Portal/Record.php
  layouts/basic/modules/Vtiger/Edit/InventorySummary.tpl
  layouts/basic/modules/Vtiger/inventoryfields/EditViewDiscount.tpl
  modules/Vtiger/inventoryfields/Discount.php
  modules/Vtiger/inventoryfields/Tax.php
  modules/Vtiger/inventoryfields/TaxPercent.php
  modules/Vtiger/models/Module.php
  modules/Vtiger/models/Record.php
Labels: ✔ finished

#11075 Corrected buy form and company details translations
  languages/en-US/Settings/Companies.json
  layouts/basic/modules/Settings/Companies/DetailView.tpl
  layouts/basic/modules/Settings/Companies/EditView.tpl
  layouts/basic/modules/Settings/Companies/Form.tpl
  layouts/basic/modules/Settings/YetiForce/BuyModal.tpl
  modules/Settings/Companies/models/Module.php
  modules/Settings/YetiForce/views/BuyModal.php
  public_html/layouts/basic/modules/Settings/YetiForce/resources/Shop.js
Labels: ✔ finished

#11083 Improved special function "TableCurrencySummary"
  app/TextParser/TableCurrencySummary.php
Labels: ✔ finished

#11081 Improved company form and shop products on dashboard
  app/Controller/Modal.php
  languages/en-US/Settings/YetiForce.json
  layouts/basic/modules/Settings/Companies/Form.tpl
  layouts/basic/modules/Settings/YetiForce/BuyModal.tpl
  layouts/basic/modules/Settings/YetiForce/ProductModal.tpl
  layouts/basic/modules/Settings/YetiForce/Shop/SmallProduct.tpl
  layouts/basic/modules/Vtiger/Modals/Footer.tpl
  modules/Settings/Companies/models/Module.php
  modules/Settings/YetiForce/views/BuyModal.php
  public_html/layouts/basic/styles/Main.css
  public_html/layouts/basic/styles/Main.css.map
  public_html/layouts/basic/styles/Main.scss
  public_html/layouts/basic/styles/_Variables.scss
  public_html/layouts/basic/styles/libraries/_Bootstrap.scss
  public_html/layouts/basic/styles/pages/Settings/_Dashboard.scss
  public_html/layouts/basic/styles/pages/Settings/_Store.scss
  public_html/src/css/quasar.css
  public_html/src/css/quasar.variables.styl
Labels: ✔ finished

#11082 "DisableBranding" product modification
  app/Pdf/YetiForcePDF.php
  config/Components/ConfigTemplates.php
  install/install_schema/data.sql
  layouts/basic/modules/Vtiger/Footer.tpl
  modules/Vtiger/actions/PDF.php
Labels: ▶ in progress

#11085 Footer's name
  config/Components/ConfigTemplates.php
  config/ConfigTemplates.php
  layouts/basic/modules/Vtiger/BodyHeader.tpl
  layouts/basic/modules/Vtiger/Footer.tpl
  layouts/basic/modules/Vtiger/Header.tpl
Labels: ✔ finished

#11086 Improved settings' dashboard
  languages/en-US/Settings/_Base.json
  layouts/basic/modules/FCorectingInvoice/Detail/FullContents.tpl
  layouts/basic/modules/FCorectingInvoice/Edit/Inventory.tpl
  layouts/basic/modules/Settings/Vtiger/DashBoard/PartnerZone.tpl
  layouts/basic/modules/Settings/Vtiger/DashBoard/PremiumZone.tpl
  layouts/basic/modules/Settings/Vtiger/Index.tpl
  layouts/basic/modules/Vtiger/Detail/BlockView.tpl
  layouts/basic/modules/Vtiger/Detail/Widget/BlockView.tpl
  layouts/basic/modules/Vtiger/DetailViewBlockLink.tpl
  public_html/layouts/basic/styles/Main.css
  public_html/layouts/basic/styles/Main.css.map
  public_html/layouts/basic/styles/Main.scss
  public_html/layouts/basic/styles/components/_Global.scss
  public_html/layouts/basic/styles/components/_Utilities.scss
  public_html/layouts/basic/styles/libraries/_Bootstrap.scss
  public_html/layouts/basic/styles/pages/Settings/_Shop.scss
Labels: ✔ finished

#11087 Validate branding
  app/Utils/ConfReport.php
  app/YetiForce/Shop/Product/DisableBranding.php
  layouts/basic/modules/Vtiger/Footer.tpl
Labels: ✔ finished

#11096 Improved settings' dashboard
  layouts/basic/modules/CustomView/EditView.tpl
  layouts/basic/modules/Settings/Vtiger/DashBoard/SettingsShortCut.tpl
  layouts/basic/modules/Settings/Vtiger/DashBoard/SettingsShortCutsContainer.tpl
  layouts/basic/modules/Settings/Vtiger/DashBoard/SystemMonitoring.tpl
  layouts/basic/modules/Settings/Vtiger/Index.tpl
  layouts/basic/modules/Settings/WebserviceApps/CreateApp.tpl
  public_html/layouts/basic/modules/Settings/Vtiger/resources/Index.js
  public_html/layouts/basic/skins/gray/pages/_Dashboard.scss
  public_html/layouts/basic/styles/Main.css
  public_html/layouts/basic/styles/Main.css.map
  public_html/layouts/basic/styles/components/_Global.scss
  public_html/layouts/basic/styles/components/_Utilities.scss
  public_html/layouts/basic/styles/libraries/_Bootstrap.scss
  public_html/layouts/basic/styles/pages/Settings/_Dashboard.scss
Labels: ✔ finished

#11099 Improving IMAP server validation
  app/Validator.php
  modules/OSSMail/ConfigTemplate.php
  tests/App/Validator.php
Labels: ✔ finished

#11100 Added product search and improved product to renew styles
  languages/en-US/Settings/_Base.json
  layouts/basic/modules/Settings/Vtiger/DashBoard/PartnerZone.tpl
  layouts/basic/modules/Settings/Vtiger/DashBoard/PremiumZone.tpl
  layouts/basic/modules/Settings/Vtiger/Index.tpl
  layouts/basic/modules/Settings/YetiForce/Shop/Product.tpl
  layouts/basic/modules/Settings/YetiForce/Shop/SmallProduct.tpl
  layouts/basic/modules/Vtiger/QuickCreate.tpl
  modules/Vtiger/models/QuickCreateView.php
  public_html/layouts/basic/modules/Settings/Vtiger/resources/Index.js
  public_html/layouts/basic/modules/Settings/YetiForce/resources/Shop.js
Labels: ✔ finished

#11101 Fixed #11092
  public_html/layouts/basic/modules/Vtiger/resources/Header.js
  public_html/layouts/basic/styles/Main.css
  public_html/layouts/basic/styles/Main.css.map
  public_html/layouts/basic/styles/components/_Global.scss
Labels: ✔ finished

#11105 Fixed calculate margin [IT634]
  public_html/layouts/basic/modules/Vtiger/resources/Inventory.js
Labels: ✔ finished

#11106 Added icons to settings' dashboard
  layouts/basic/modules/Settings/Vtiger/Index.tpl
  layouts/basic/modules/Settings/YetiForce/Shop.tpl
  public_html/layouts/basic/styles/Main.css
  public_html/layouts/basic/styles/Main.css.map
  public_html/layouts/basic/styles/components/_Global.scss
  public_html/layouts/basic/styles/pages/Settings/_Shop.scss
Labels: ✔ finished

#11107 Fixed ExceptionError colors
  layouts/basic/modules/Vtiger/ExceptionError.tpl
Labels: ✔ finished

#11109 Moved alerts from footer to header
  layouts/basic/modules/Vtiger/BodyHeader.tpl
  layouts/basic/modules/Vtiger/Footer.tpl
Labels: ✔ finished

#11112 Fixed c-panel and modals after changing global styles
  layouts/basic/modules/OpenStreetMap/MapModal.tpl
  layouts/basic/modules/Settings/Github/AddIssueModal.tpl
  layouts/basic/modules/Vtiger/Edit/Field/Recurrence.tpl
  layouts/basic/modules/Vtiger/EditViewBlocks.tpl
Labels: ✔ finished

#11110 [IT636] Removed the request incorrect
  public_html/layouts/basic/modules/Settings/LayoutEditor/resources/LayoutEditor.js
Labels: ✔ finished

#11127 Added popovers and new icons to the chat
  languages/en-US/_Base.json
  public_html/layouts/basic/modules/Chat/Chat.vue.js
  public_html/layouts/basic/modules/Chat/Chat.vue.js.map
  public_html/src/components/Icon.vue
  public_html/src/layouts/basic/modules/Chat/Chat.js
  public_html/src/layouts/basic/modules/Chat/components/ChatFooter.vue
  public_html/src/layouts/basic/modules/Chat/components/ChatHeader.vue
  public_html/src/layouts/basic/modules/Chat/components/Dialog.vue
  public_html/src/layouts/basic/modules/Chat/components/History.vue
  public_html/src/layouts/basic/modules/Chat/components/LeftPanel.vue
  public_html/src/layouts/basic/modules/Chat/components/MessageInput.vue
  public_html/src/layouts/basic/modules/Chat/components/NotifyBtn.vue
  public_html/src/layouts/basic/modules/Chat/components/RightPanel.vue
  public_html/src/layouts/basic/modules/Chat/utils/utils.js
Labels: ✔ finished

#11124 New icons in the module list
  app/YetiForce/Shop.php
  layouts/basic/modules/Settings/ModuleManager/ImportUserModuleStep2.tpl
  layouts/basic/modules/Settings/ModuleManager/ListContents.tpl
  modules/Settings/ModuleManager/models/Module.php
  modules/Settings/ModuleManager/views/List.php
  modules/Settings/ModuleManager/views/ModuleImport.php
  tests/Settings/ModuleManager.php
  vtlib/Vtiger/Functions.php
  vtlib/Vtiger/Module.php
  vtlib/Vtiger/ModuleBasic.php
  vtlib/Vtiger/PackageExport.php
  vtlib/Vtiger/PackageImport.php
Labels: 🔧 AmendmentsRequired

#11128 Added disable to button
  layouts/basic/modules/Settings/ModuleManager/ImportUserModuleStep2.tpl
  public_html/layouts/basic/modules/Settings/ModuleManager/resources/ModuleImport.js
Labels: ✔ finished

#11134 Improved chat panels
  languages/en-US/_Base.json
  public_html/layouts/basic/modules/Chat/Chat.vue.js
  public_html/layouts/basic/modules/Chat/Chat.vue.js.map
  public_html/layouts/resources/views/KnowledgeBase/KnowledgeBase.vue.js
  public_html/layouts/resources/views/KnowledgeBase/KnowledgeBase.vue.js.map
  public_html/src/components/DragResize.vue
  public_html/src/layouts/basic/modules/Chat/components/ChatHeader.vue
  public_html/src/layouts/basic/modules/Chat/components/LeftPanel.vue
  public_html/src/layouts/basic/modules/Chat/components/MessageInput.vue
  public_html/src/layouts/basic/modules/Chat/components/RightPanel.vue
  public_html/src/package.json
  public_html/src/yarn.lock
Labels: ✔ finished

#11139 Fixed dragging/resizing outside the window
  public_html/layouts/basic/modules/Chat/Chat.vue.js
  public_html/layouts/basic/modules/Chat/Chat.vue.js.map
  public_html/layouts/resources/views/KnowledgeBase/KnowledgeBase.vue.js
  public_html/layouts/resources/views/KnowledgeBase/KnowledgeBase.vue.js.map
  public_html/src/components/DragResize.vue
  public_html/src/layouts/basic/modules/Chat/store/state.js
Labels: ✔ finished

#11143 Added minor fixes
  api/webservice/Portal/Record.php
  modules/Vtiger/models/PDF.php
  modules/Vtiger/models/Record.php
Labels: ✔ finished

#11138 Addition of translations
  languages/en-US/Settings/WebserviceApps.json
  layouts/basic/modules/Settings/WebserviceApps/CreateApp.tpl
  layouts/basic/modules/Settings/WebserviceApps/Index.tpl
Labels: ✔ finished

#11140 [IT630] Fixed deposit creation has been improved quickly
  install/install_schema/data.sql
  layouts/basic/modules/Vtiger/Edit/Field/Currency.tpl
  modules/Vtiger/uitypes/Currency.php
Labels: ✔ finished
