Repository YetiForceCompany/YetiForceCRM, pull requests merged in 2019-04, with the labels that each got.

#10088 💫 Improved routes
  app/Controller/WebUI.php
  public_html/src/modules/Base/modules/Home/Home.vue
  public_html/src/modules/Base/modules/ModuleExample/ModuleExample.vue
  public_html/src/modules/Base/router/routes.js
  public_html/src/modules/Core/router/routes.js
  public_html/src/router/index.js
  public_html/src/router/routes.js
  public_html/src/statics/modules.js
Labels: ✔ finished

#10051 Add fix for create zip from mass download files
  modules/Documents/models/Record.php
Labels: ✔ finished

#9900 Conversion PearDatabase to yii [IT529]
  vtlib/Vtiger/PackageExport.php
  vtlib/Vtiger/PackageImport.php
  vtlib/Vtiger/PackageUpdate.php
  vtlib/Vtiger/Utils.php
Labels: ✔ finished

#10011 Improved link to create record from widgets
  layouts/basic/modules/Vtiger/Detail/Widget/Basic.tpl
  modules/Vtiger/widgets/RelatedModule.php
Labels: ✔ finished

#10081 Add trigger after search in autocomplete
  public_html/layouts/basic/modules/Vtiger/resources/Edit.js
Labels: 🔧 AmendmentsRequired

#10083 💫 vue source maps
  .gitignore
  package-lock.json
  package.json
  public_html/App.vue.min.js
  public_html/ModuleLoader.min.js
  public_html/ModuleLoader.server.js
  public_html/gulp/gulp-import-aliases.js
  public_html/gulp/gulp-import-min.js
  public_html/gulp/gulp-terser.js
  public_html/gulp/gulp-vue-es-compiler.js
  public_html/gulpfile.js
  public_html/main.min.js
  public_html/package-lock.json
  public_html/package.json
  public_html/src/App.vue
  public_html/src/main.js
  public_html/src/modules/Base/modules/Home/router/routes.js
  public_html/src/modules/Core/modules/Hooks/Hooks.vue
  storage/Installed/Installed.vue
  storage/Installed/pages/Installed.vue
  storage/Installed/router/routes.js
Labels: ✔ finished

#10094 Web services - Language selection
  api/webservice/Core/BaseAction.php
Labels: ✔ finished

#10100 Fixed #10075
  modules/Vtiger/models/Export.php
Labels: ✔ finished

#10118 💫 moved User module Url to User module
  public_html/src/modules/Core/modules/Url/store/getters.js
  public_html/src/modules/Core/modules/Url/store/state.js
  public_html/src/modules/Core/modules/Users/Users.vue
Labels: ✔ finished

#10129 💫 dynamically load script into script tag
  public_html/package-lock.json
  public_html/package.json
  public_html/src/App.vue
  public_html/src/main.js
Labels: ✔ finished

#10130 Added minor improvements in workflow
  cron/modules/com_vtiger_workflow/com_vtiger_workflow.php
  modules/Vtiger/helpers/AdvancedFilter.php
  modules/com_vtiger_workflow/WorkFlowScheduler.php
Labels: ✔ finished

#10121 Fixed bug in related product widget
  layouts/basic/modules/Vtiger/Detail/Widget/ProductsServicesBasic.tpl
  modules/Products/models/SummaryWidget.php
  modules/Products/views/Widget.php
Labels: ✔ finished

#10023 #9953 fix for double editor instance
  public_html/layouts/basic/modules/Settings/LayoutEditor/resources/LayoutEditor.js
Labels: ✔ finished

#10120 Field information has been improved - Returning the tree structure.
  api/webservice/Portal/BaseModule/Fields.php
  app/Fields/Tree.php
  modules/Vtiger/models/Field.php
Labels: ✔ finished

#10096 Fixed problem with validation engine on date fields
  layouts/basic/modules/Calendar/Edit/Field/Date.tpl
  layouts/basic/modules/Settings/Workflows/Step1.tpl
  layouts/basic/modules/Vtiger/ConditionBuilder/Date.tpl
  layouts/basic/modules/Vtiger/Edit/Field/Date.tpl
  layouts/basic/modules/Vtiger/Edit/Field/Recurrence.tpl
  layouts/basic/modules/Vtiger/List/Field/Date.tpl
  public_html/layouts/resources/Field.js
Labels: ✔ finished

#10085 IT557 add fix for validation url fields
  layouts/basic/modules/Vtiger/Edit/Field/Url.tpl
Labels: ✔ finished

#10082 Fixed getting users in the same role
  app/Fields/Owner.php
Labels: ✔ finished

#10063 #10055 add truncate option to texparser related and record lists
  app/TextParser.php
Labels: ✔ finished

#10089 Add improvment to get contact lists from WebserviceUsers
  modules/Vtiger/views/RecordsList.php
Labels: ✔ finished

#10019 Fixed visibility of scrollbar after refresh list with records
  public_html/layouts/basic/modules/Vtiger/resources/List.js
Labels: ✔ finished, 🔧 AmendmentsRequired

#10138 💫 Added websocket client service
  .gitignore
  public_html/src/App.vue
  public_html/src/modules/Core/modules/Env/store/state.js
  public_html/src/services/AppConnector.js
  public_html/src/services/WebSocket.js
Labels: ✔ finished

#10139 💫 menu - left, right-top, right-bottom actions
  public_html/src/modules/Core/components/TreeEditor.vue
  public_html/src/modules/Settings/modules/Menu/pages/Index.vue
  public_html/src/utilities/Objects.js
Labels: ✔ finished

#10142 💫 Improved client websocket actions
  public_html/src/App.vue
  public_html/src/modules/Base/modules/ModuleExample/pages/ModuleExample.vue
  public_html/src/modules/Core/modules/Env/store/state.js
  public_html/src/modules/Core/modules/Users/store/actions.js
  public_html/src/services/AppConnector.js
  public_html/src/services/WebSocket.js
Labels: ✔ finished

#10106 Addition of the getApiDisplayValue method
  api/webservice/Core/Modules/Vtiger/uitypes/Base.php
  api/webservice/Core/Modules/Vtiger/uitypes/Image.php
  api/webservice/Core/Modules/Vtiger/uitypes/MultiImage.php
  api/webservice/Portal/BaseModule/RecordsList.php
  modules/Vtiger/models/Field.php
  modules/Vtiger/uitypes/Base.php
  modules/Vtiger/uitypes/MultiImage.php
Labels: ✔ finished

#10143 Change generate buttons on pdf
  layouts/basic/modules/Vtiger/ExportPDF.tpl
Labels: ✔ finished

#10150 Fixed copy address from lead Vendors and Contacts
  public_html/layouts/basic/modules/Vtiger/resources/Edit.js
Labels: ✔ finished

#10152 💫 working on menu
  public_html/src/css/app.css
  public_html/src/css/quasar.variables.styl
  public_html/src/modules/Core/components/PopupProxyLayout.vue
  public_html/src/modules/Core/components/TreeEditor.vue
  public_html/src/modules/Core/modules/Menu/Menu.vue
  public_html/src/modules/Core/modules/Menu/store/actions.js
  public_html/src/modules/Core/modules/Menu/store/getters.js
  public_html/src/modules/Core/modules/Menu/store/state.js
  public_html/src/modules/Core/modules/Url/store/state.js
  public_html/src/modules/Settings/modules/Menu/components/Module.vue
  public_html/src/modules/Settings/modules/Menu/pages/Index.vue
  public_html/src/statics/modules.js
  public_html/src/store/actions.js
  public_html/src/store/getters.js
  public_html/src/store/mutations.js
Labels: ✔ finished

#9975 [IT548] - Fixed modal window appearance
  layouts/basic/modules/Settings/YetiForce/DownloadLanguageModal.tpl
  modules/Settings/YetiForce/views/DownloadLanguageModal.php
Labels: ✔ finished

#10146 Added storage into webservice users
  install/install_schema/scheme.sql
  languages/en-US/Settings/WebserviceUsers.json
  modules/Settings/WebserviceUsers/actions/SaveAjax.php
  modules/Settings/WebserviceUsers/models/Record.php
Labels: ✔ finished

#10154 Load more records in widgets improvement
  public_html/layouts/basic/modules/Vtiger/resources/Detail.js
Labels: ✔ finished

#10147 Changed generate mapping modal
  layouts/basic/modules/Vtiger/GenerateModal.tpl
  public_html/layouts/basic/modules/Vtiger/resources/GenerateModal.js
Labels: ✔ finished

#10158 Addes default module in global search engine
  install/install_schema/data.sql
  install/install_schema/scheme.sql
  languages/en-US/HelpInfo.json
  languages/en-US/Users.json
  layouts/basic/modules/Vtiger/BodyHeader.tpl
Labels: ✔ finished

#10157 💫 Added notification module, and improved websocket actions
  public_html/src/modules/Base/modules/ModuleExample/pages/ModuleExample.vue
  public_html/src/modules/Core/modules/Notification/Notification.vue
  public_html/src/modules/Core/modules/Notification/store/actions.js
  public_html/src/modules/Core/modules/Notification/store/getters.js
  public_html/src/modules/Core/modules/Notification/store/index.js
  public_html/src/modules/Core/modules/Notification/store/mutations.js
  public_html/src/modules/Core/modules/Notification/store/state.js
  public_html/src/services/AppConnector.js
  public_html/src/services/WebSocket.js
Labels: ✔ finished

#10156 💫 menu icon selector
  public_html/gulp/gulp-save-mdi-icons.js
  public_html/gulpfile.js
  public_html/package-lock.json
  public_html/package.json
  public_html/src/css/app.css
  public_html/src/css/app.styl
  public_html/src/modules/Core/components/PopupProxyLayout.vue
  public_html/src/modules/Core/components/TreeEditor.vue
  public_html/src/modules/Core/modules/Icons/Icons.vue
  public_html/src/modules/Core/modules/Icons/assets/Icons.js
  public_html/src/modules/Core/modules/Icons/components/IconSelector.vue
  public_html/src/modules/Core/modules/Icons/store/getters.js
  public_html/src/modules/Core/modules/Icons/store/index.js
  public_html/src/modules/Core/modules/Icons/store/mutations.js
  public_html/src/modules/Core/modules/Icons/store/state.js
  public_html/src/modules/Settings/modules/Menu/components/Shortcut.vue
  public_html/src/modules/Settings/modules/Menu/pages/Index.vue
  public_html/src/statics/modules.js
  public_html/src/store/actions.js
  public_html/src/store/getters.js
  public_html/src/store/mutations.js
  public_html/src/utilities/Objects.js
Labels: ✔ finished

#10155 Improved permissions for Api (Portal)
  api/webservice/Core/BaseAction.php
  api/webservice/Core/Module.php
  api/webservice/Portal/BaseAction/Methods.php
  api/webservice/Portal/BaseModule/Hierarchy.php
  api/webservice/Portal/BaseModule/RecordsList.php
  api/webservice/Portal/Privilege.php
  api/webservice/Portal/PrivilegeQuery.php
  app/Privilege.php
  app/PrivilegeQuery.php
  app/User.php
  modules/OSSMailView/models/Record.php
  modules/Settings/WebserviceUsers/models/Record.php
Labels: ✔ finished

#10167 💫 Changed 'webSocket' to 'webSocketUrl' in vuex Env
  public_html/src/App.vue
  public_html/src/modules/Core/modules/Env/store/state.js
  public_html/src/modules/Core/modules/Users/store/actions.js
  public_html/src/services/WebSocket.js
Labels: ✔ finished

#10168 💫 icon selector improvements
  public_html/src/modules/Core/modules/Icons/components/IconSelector.vue
  public_html/src/statics/modules.js
  public_html/src/store/actions.js
  public_html/src/store/getters.js
  public_html/src/store/mutations.js
Labels: ✔ finished

#10008 Deleted function getSecurityConf()
  app/Utils/ConfReport.php
  modules/Settings/ConfReport/models/Module.php
  tests/Settings/ConfReport.php
Labels: 👮‍♂️ VerificationRequired

#10173 Added menu for webservice apps
  api/webservice/Portal/BaseAction/Menu.php
  install/install_schema/data.sql
  install/install_schema/scheme.sql
  layouts/basic/modules/Settings/Menu/Index.tpl
  modules/Settings/Menu/actions/SaveAjax.php
  modules/Settings/Menu/models/Module.php
  modules/Settings/Menu/models/Record.php
  modules/Settings/Menu/views/Index.php
  public_html/layouts/basic/modules/Settings/Menu/resources/Menu.js
Labels: ✔ finished

#10178 YetiForcePDF update v0.1.22
  composer.json
Labels: ✔ finished

#10179 vscode history files ignored
  .gitignore
Labels: ✔ finished

#10180 Added encode value when system can not translate
  app/Language.php
Labels: ✔ finished

#10181 pdf layout column scheme initial
  install/install_schema/data.sql
  install/install_schema/scheme.sql
  languages/en-US/Settings/PDF.json
  layouts/basic/modules/Vtiger/ExportPDF.tpl
  modules/Settings/PDF/models/Module.php
  modules/Settings/PDF/models/Record.php
  modules/Vtiger/views/PDF.php
Labels: ✔ finished

#10165 Changed mandatory fields in user
  install/install_schema/data.sql
  layouts/basic/modules/Users/Edit/Field/Picklist.tpl
  modules/Users/models/Field.php
Labels: ✔ finished

#10192 vscode javascript linter, intellisense improvement
  .editorconfig
  jsconfig.json
  public_html/layouts/resources/app.js
Labels: ✔ finished

#10197 💫 Corrected web socket error handling
  public_html/src/App.vue
  public_html/src/modules/Core/modules/Debug/router/routes.js
  public_html/src/modules/Core/modules/Env/store/getters.js
  public_html/src/modules/Core/modules/Env/store/mutations.js
  public_html/src/modules/Core/modules/Env/store/state.js
  public_html/src/modules/Core/modules/Notification/store/actions.js
  public_html/src/modules/Core/modules/Users/store/actions.js
  public_html/src/pages/errors/404.vue
  public_html/src/router/routes.js
  public_html/src/services/WebSocket.js
  public_html/src/store/index.js
Labels: ✔ finished

#10195 exclude history files from js, basic eslint config
  .eslintrc
  jsconfig.json
Labels: ✔ finished

#10098 Added inventory info via API
  api/webservice/Portal/BaseModule/Fields.php
  api/webservice/Portal/BaseModule/Record.php
Labels: ✔ finished

#10163 Changed detail view widget layout in modules
  layouts/basic/modules/Vtiger/Detail/Widget/BlockView.tpl
  modules/Vtiger/views/Detail.php
  modules/Vtiger/widgets/DetailView.php
Labels: ✔ finished

#10190 Improvements on tree field
  layouts/basic/modules/Vtiger/Edit/Field/Tree.tpl
  public_html/layouts/basic/modules/Settings/LayoutEditor/resources/LayoutEditor.js
  public_html/layouts/basic/modules/Vtiger/resources/Edit.js
  public_html/layouts/resources/Fields.js
Labels: ✔ finished

#10196 Changed presence value for crmactivity field [+DB dump]
  install/install_schema/data.sql
  modules/Calendar/cron/SetCrmActivity.php
  modules/Calendar/models/Record.php
Labels: ✔ finished

#10204 💫 Improved error handling
  app/Layout/Env.php
  public_html/src/App.vue
  public_html/src/ModuleLoader.js
  public_html/src/i18n/index.js
  public_html/src/main.js
  public_html/src/modules/Core/modules/Users/Users.vue
  public_html/src/modules/Core/modules/Users/layouts/Login.vue
  public_html/src/pages/errors/Exception.vue
  public_html/src/router/routes.js
  public_html/src/services/Base.js
Labels: ✔ finished

#10215 Fixed add charts to dashboard
  public_html/layouts/basic/modules/Settings/WidgetsManagement/resources/WidgetsManagement.js
Labels: ✔ finished

#10231 Fixed #10164
  app/Fields/File.php
Labels: ✔ finished

#10203 Added related fields (SSalesProcesses, Project) to FInvoice module.
  install/install_schema/data.sql
  install/install_schema/scheme.sql
  languages/en-US/FInvoice.json
Labels: ✔ finished

#10189 gantt-elastic update v0.13.9
  modules/Project/models/Gantt.php
  modules/Project/views/Detail.php
  modules/Project/views/Gantt.php
  package.json
  public_html/layouts/basic/modules/Project/resources/Gantt.js
Labels: ✔ finished

#10193 Changing the currency format for the API
  api/webservice/Core/Modules/Vtiger/uitypes/Base.php
  api/webservice/Portal/BaseModule/RecordsList.php
  app/QueryGenerator.php
Labels: ✔ finished

#10198 Added dashboard to portal
  api/webservice/Core/Module.php
  api/webservice/Portal/BaseModule/Dashboard.php
  api/webservice/Portal/Dashboard.php
  include/fields/CurrencyField.php
  layouts/basic/modules/Settings/WidgetsManagement/Configuration.tpl
  modules/Settings/Menu/models/Record.php
  modules/Settings/WidgetsManagement/models/Module.php
  modules/Settings/WidgetsManagement/views/Configuration.php
  public_html/layouts/basic/modules/Settings/WidgetsManagement/resources/WidgetsManagement.js
Labels: ✔ finished

#10200 pdf dynamic inventory columns
  app/Pdf/YetiForcePDF.php
  app/TextParser.php
  app/TextParser/DynamicInventoryColumnsTable.php
  install/install_schema/scheme.sql
  languages/en-US/Other/TextParser.json
  languages/en-US/Settings/PDF.json
  layouts/basic/modules/Vtiger/ExportPDF.tpl
  modules/Settings/PDF/models/Module.php
  modules/Settings/PDF/models/Record.php
  modules/Vtiger/actions/PDF.php
  modules/Vtiger/models/PDF.php
  modules/Vtiger/views/PDF.php
  public_html/layouts/basic/modules/Vtiger/resources/PDF.js
Labels: ✔ finished

#10234 Added improvement on multiple file download
  modules/Documents/actions/CheckFileIntegrity.php
  modules/Vtiger/models/RelationListView.php
  public_html/layouts/basic/modules/Vtiger/resources/RelatedList.js
Labels: ✔ finished

#10220 Added new field in inventory - Tax in percent
  languages/en-US/_Base.json
  layouts/basic/modules/Vtiger/Edit/InventorySummary.tpl
  layouts/basic/modules/Vtiger/inventoryfields/EditViewTaxPercent.tpl
  modules/Vtiger/inventoryfields/Tax.php
  modules/Vtiger/inventoryfields/TaxPercent.php
  modules/Vtiger/models/Inventory.php
  public_html/layouts/basic/modules/Vtiger/resources/Inventory.js
Labels: ✔ finished

#10238 inventory columns as static value
  app/Pdf/InventoryColumns.php
  app/Pdf/YetiForcePDF.php
  app/TextParser.php
  app/TextParser/DynamicInventoryColumnsTable.php
  layouts/basic/modules/Vtiger/ExportPDF.tpl
  modules/Vtiger/actions/PDF.php
  modules/Vtiger/models/PDF.php
  modules/Vtiger/views/PDF.php
  public_html/layouts/basic/modules/Vtiger/resources/PDF.js
Labels: 🔧 AmendmentsRequired

#9958 IT544 fix and improvement recurseDelete method
  vtlib/Vtiger/Functions.php
Labels: ✔ finished, 👮‍♂️ VerificationRequired

#10247 dynamic inventory columns profile permissions
  app/Pdf/InventoryColumns.php
  install/install_schema/data.sql
  languages/en-US/Settings/PDF.json
  languages/en-US/_Base.json
  layouts/basic/modules/Vtiger/ExportPDF.tpl
  modules/Vtiger/actions/PDF.php
  modules/Vtiger/views/PDF.php
Labels: ✔ finished

#10245 YetiForcePDF update v0.1.23
  composer.json
Labels: ✔ finished

#10257 Added minor improvements for API
  api/webservice/Core/BaseAction.php
  api/webservice/Portal/Dashboard.php
Labels: ✔ finished

#10258 Fixed pnotify alert bug
  public_html/layouts/resources/app.js
Labels: ✔ finished

#10251 Fixed division by zero
  vtlib/Vtiger/Functions.php
Labels: ✔ finished

#10250 json files formatting editorconfig settings
  .editorconfig
Labels: ✔ finished

#10259 YetiForcePDF update v0.1.24
  composer.json
Labels: ✔ finished

#10261 Fixed date/time field quick editing
  public_html/layouts/basic/modules/Vtiger/resources/Detail.js
Labels: ✔ finished

#10263 Fixed html2canvas bug
  modules/Vtiger/views/Basic.php
  public_html/layouts/basic/modules/Vtiger/resources/dashboards/Widget.js
Labels: ✔ finished

#10264 Added information about account
  api/webservice/Portal/Users/Login.php
Labels: ✔ finished

#10248 Fixed problem with double notification [IT563]
  layouts/basic/modules/Settings/OSSMailScanner/logs.tpl
  public_html/layouts/basic/modules/Settings/OSSMailScanner/resources/Index.js
Labels: ✔ finished

#10166 Add css class names to textparser
  app/TextParser.php
  app/TextParser/OverdueDeadlines.php
  app/TextParser/ProductsTable.php
  app/TextParser/ProductsTableCorrectingBefore.php
  app/TextParser/ProductsTableImages.php
  app/TextParser/ProductsTableLongVTwoLang.php
  app/TextParser/ProductsTableLongVersion.php
  app/TextParser/ProductsTableNew.php
  app/TextParser/ProductsTableRelatedModule.php
  app/TextParser/ProductsTableShortVersion.php
  app/TextParser/TableCorrectTaxSummary.php
  app/TextParser/TableCurrencySTwoLang.php
  app/TextParser/TableCurrencySummary.php
  app/TextParser/TableDiscountSTwoLang.php
  app/TextParser/TableDiscountSummary.php
  app/TextParser/TableTaxSTwoLang.php
  app/TextParser/TableTaxSummary.php
Labels: ✔ finished

#10262 Prohibited saving field with name 'data'
  layouts/basic/modules/Settings/LayoutEditor/CreateFieldModal.tpl
  public_html/layouts/resources/Connector.js
  public_html/layouts/resources/validator/FieldValidator.js
Labels: ✔ finished

#10268 Fixed #10266, inventory column scheme save bugfix
  app/Pdf/InventoryColumns.php
  modules/Vtiger/views/PDF.php
Labels: ✔ finished

#10277 YetiForcePDF update v0.1.25
  composer.json
Labels: ✔ finished

#10275 Fixed date field z-index
  public_html/layouts/basic/styles/Main.css
  public_html/layouts/basic/styles/Main.css.map
  public_html/layouts/basic/styles/_Style.scss
Labels: ✔ finished

#10274 Add fix for TextParser and test of it
  app/TextParser.php
  tests/App/TextParser.php
Labels: ✔ finished

#10273 Fixed validation search_params
  app/Condition.php
Labels: ✔ finished

#10272 Fixed create PDF
  app/Pdf/InventoryColumns.php
  app/TextParser/DynamicInventoryColumnsTable.php
  layouts/basic/modules/Vtiger/Detail/InventoryView.tpl
  layouts/basic/modules/Vtiger/ExportPDF.tpl
  modules/Vtiger/views/PDF.php
Labels: ✔ finished

#10271 Changed json & php file save method
  app/Json.php
  app/Language.php
  app/PrivilegeFile.php
  app/Utils.php
  app/YetiForce/Register.php
  modules/OSSMail/models/AddressBook.php
  modules/Settings/Menu/models/Record.php
  modules/Settings/RecordAllocation/models/Module.php
  modules/Settings/Users/models/Module.php
  modules/Vtiger/models/Watchdog.php
Labels: ✔ finished

#10267 Improved expired password druring force password change on user
  modules/Users/models/Record.php
Labels: ✔ finished

#10252 Fixed [IT564], fixed icon in modal window, fixed statistics fields, +…
  modules/Settings/LangManagement/models/Module.php
  modules/Settings/YetiForce/views/DownloadLanguageModal.php
  public_html/layouts/basic/modules/Settings/LangManagement/resources/LangManagement.js
Labels: ✔ finished

#10297 gantt - estimated_work_time undefined index bugfix
  modules/Project/models/Gantt.php
Labels: ✔ finished
