Repository YetiForceCompany/YetiForceCRM, pull requests merged in 2020-09, with the labels that each got.

#13432 fixed #13401
  install/install_schema/data.sql
Labels: ✔ finished

#13433 Fixed #13318
  modules/Notification/models/Record.php
Labels: ✔ finished

#13418 Corrected row height
  public_html/layouts/basic/styles/libraries/_Libraries.scss
Labels: ✔ finished

#13447 Fixed #13075
  public_html/layouts/basic/styles/pages/_Dashboard.scss
Labels: ✔ finished

#13446 Fixed #13326
  modules/Vtiger/models/MiniList.php
Labels: ✔ finished

#13472 Added translation for database information
  languages/en-US/Settings/ConfReport.json
  layouts/basic/modules/Settings/ConfReport/DbInfo.tpl
Labels: ✔ finished

#13474 Fixed #13176
  layouts/basic/modules/Vtiger/Edit/DefaultField/Date.tpl
Labels: ✔ finished

#13488 Fixed problem with related product/service list on SQuotes
  modules/Products/models/ListView.php
  public_html/layouts/basic/modules/SQuotes/resources/Edit.js
Labels: ✔ finished

#13492 Fixed problem with mass edit on new bootstrap v4.5
  layouts/basic/modules/Vtiger/MassEditForm.tpl
Labels: ✔ finished

#13495 Added external connection profiling
  app/Extension/PwnedPassword/YetiForce.php
  app/Fields/File.php
  app/Installer/Languages.php
  app/Integrations/Pbx/Mixpbx.php
  app/Integrations/Pbx/VtigerAsteriskConnector.php
  app/Map/Address/GoogleGeocode.php
  app/Map/Address/NominatimGeocoder.php
  app/Map/Address/OpenCageGeocoder.php
  app/Map/Address/YetiForceGeocoder.php
  app/Map/Coordinates/Nominatim.php
  app/Map/Coordinates/YetiForce.php
  app/Map/Routing/YetiForce.php
  app/Map/Routing/Yours.php
  app/Security/Dependency.php
  app/Utils/ConfReport.php
  app/YetiForce/Register.php
  app/YetiForce/Updater.php
  app/YetiForce/Watchdog.php
  modules/OpenStreetMap/files/TileLayer.php
  modules/Settings/CurrencyUpdate/bankmodels/NBP.php
  modules/Settings/ModuleManager/models/Library.php
Labels: 🔧 AmendmentsRequired

#13499 Changed structure of profiling
  app/Integrations/Magento/Connector/Token.php
  app/Mailer.php
Labels: ✔ finished

#13504 Fixed #12707
  install/install_schema/data.sql
  modules/Settings/ModuleManager/models/Module.php
Labels: ✔ finished

#13498 Improved sequence improve
  layouts/basic/modules/Vtiger/Modals/Header.tpl
  public_html/layouts/basic/modules/Vtiger/resources/Vtiger.js
Labels: ✔ finished

#13481 Corrected view mail action bar
  layouts/basic/modules/OSSMail/MailActionBar.tpl
  layouts/basic/modules/OSSMail/MailActionBarRow.tpl
Labels: ✔ finished

#13483 Fixed problem with show more record in month view
  public_html/layouts/basic/styles/pages/_Calendar.scss
Labels: ✔ finished

#13519 Improved showing mail modal in mail preview
  public_html/layouts/basic/modules/Vtiger/resources/Detail.js
Labels: ✔ finished

#13530 Fix open double window while generate PDF and send by mail
  public_html/layouts/basic/modules/Vtiger/resources/PDF.js
Labels: ✔ finished

#13531 Added type in function showNotify
  layouts/basic/modules/OSSMailView/index.tpl
  public_html/layouts/basic/modules/Calendar/resources/Detail.js
  public_html/layouts/basic/modules/Calendar/resources/Edit.js
  public_html/layouts/basic/modules/Calendar/resources/Extended/CalendarView.js
  public_html/layouts/basic/modules/Contacts/resources/Detail.js
  public_html/layouts/basic/modules/Contacts/resources/Edit.js
  public_html/layouts/basic/modules/CustomView/resources/CustomView.js
  public_html/layouts/basic/modules/Documents/resources/List.js
  public_html/layouts/basic/modules/Leads/resources/Detail.js
  public_html/layouts/basic/modules/Rss/resources/List.js
  public_html/layouts/basic/modules/Settings/AdminAccess/resources/Edit.js
  public_html/layouts/basic/modules/Settings/BruteForce/resources/Index.js
  public_html/layouts/basic/modules/Settings/LayoutEditor/resources/LayoutEditor.js
  public_html/layouts/basic/modules/Settings/Magento/resources/Edit.js
  public_html/layouts/basic/modules/Settings/Mail/resources/List.js
  public_html/layouts/basic/modules/Settings/OSSMail/resources/Index.js
  public_html/layouts/basic/modules/Settings/OSSMailScanner/resources/Index.js
  public_html/layouts/basic/modules/Settings/SMSNotifier/resources/Edit.js
  public_html/layouts/basic/modules/Settings/TreesManager/resources/List.js
  public_html/layouts/basic/modules/Settings/Vtiger/resources/EditModal.js
  public_html/layouts/basic/modules/Settings/Vtiger/resources/List.js
  public_html/layouts/basic/modules/Settings/WebserviceApps/resources/WebserviceApps.js
  public_html/layouts/basic/modules/Settings/WebserviceUsers/resources/Edit.js
  public_html/layouts/basic/modules/Settings/Workflows/resources/List.js
  public_html/layouts/basic/modules/Users/resources/Detail.js
  public_html/layouts/basic/modules/Users/resources/List.js
  public_html/layouts/basic/modules/Users/resources/VisitPurpose.js
  public_html/layouts/basic/modules/Vtiger/resources/Detail.js
  public_html/layouts/basic/modules/Vtiger/resources/Edit.js
  public_html/layouts/basic/modules/Vtiger/resources/List.js
  public_html/layouts/basic/modules/Vtiger/resources/MergeRecords.js
  public_html/layouts/basic/modules/Vtiger/resources/RecordUnlock.js
  public_html/layouts/basic/modules/Vtiger/resources/RecordsList.js
  public_html/layouts/basic/modules/Vtiger/resources/RelatedList.js
  public_html/layouts/resources/Calendar.js
  public_html/layouts/resources/Fields.js
  public_html/layouts/resources/app.js
  public_html/layouts/resources/fields/MultiImage.js
  public_html/src/layouts/basic/modules/Chat/components/ChatButtonNotify.vue
  public_html/src/layouts/basic/modules/Chat/components/Tabs/TabChatInput.vue
Labels: ✔ finished

#13533 Fixed bug: deleting wrong elements when processindicator hide
  public_html/layouts/resources/ProgressIndicator.js
Labels: ✔ finished

#13534 Removed unnecessary overhang
  public_html/layouts/basic/modules/Calendar/resources/Edit.js
  public_html/layouts/basic/modules/Calendar/resources/Extended/CalendarView.js
  public_html/layouts/basic/modules/Contacts/resources/Detail.js
  public_html/layouts/basic/modules/Contacts/resources/Edit.js
Labels: ✔ finished

#13532 Added Search engine to RBL mail and added widow modal
  layouts/basic/modules/Settings/MailRbl/DetailModal.tpl
  layouts/basic/modules/Settings/MailRbl/Index.tpl
  modules/Settings/MailRbl/actions/GetData.php
  public_html/layouts/basic/modules/Settings/MailRbl/resources/Index.js
Labels: ✔ finished

#13542 Corrected view the search engine RBL
  layouts/basic/modules/Settings/MailRbl/Index.tpl
  modules/Settings/MailRbl/views/Index.php
Labels: ✔ finished

#13547 Added Search engine to RBL Black and White List and corrected button action
  layouts/basic/modules/Settings/MailRbl/Index.tpl
  layouts/basic/modules/Settings/MailRbl/SearchFormList.tpl
  modules/Settings/MailRbl/actions/GetData.php
  public_html/layouts/basic/modules/Settings/MailRbl/resources/Index.js
  public_html/layouts/basic/styles/components/_Utilities.scss
Labels: ✔ finished

#13548 Add list import modal in MailRbl settings.
  languages/en-US/Settings/MailRbl.json
  layouts/basic/modules/Settings/MailRbl/Index.tpl
  layouts/basic/modules/Settings/MailRbl/UploadListModal.tpl
  modules/Settings/MailRbl/actions/UploadList.php
  modules/Settings/MailRbl/views/UploadListModal.php
  public_html/layouts/basic/modules/Settings/MailRbl/resources/UploadListModal.js
Labels: ✔ finished

#13557 Fixed query problem with Alphabet Sort
  app/Conditions/QueryFields/AccountNameField.php
  app/Conditions/RecordFields/BaseField.php
Labels: ✔ finished

#13254 Add possibility to count tax from brutto value.
  layouts/basic/modules/Vtiger/Detail/InventorySummary.tpl
  layouts/basic/modules/Vtiger/inventoryfields/EditViewTaxCountMode.tpl
  modules/Vtiger/inventoryfields/Discount.php
  modules/Vtiger/inventoryfields/GrossPrice.php
  modules/Vtiger/inventoryfields/NetPrice.php
  modules/Vtiger/inventoryfields/Tax.php
  modules/Vtiger/inventoryfields/TaxCountMode.php
  modules/Vtiger/inventoryfields/TotalPrice.php
  public_html/layouts/basic/modules/Vtiger/resources/Inventory.js
Labels: 👮‍♂️ VerificationRequired

#13565 Fixed problem with alphabet search on modal windows
  layouts/basic/modules/Vtiger/Modals/RecordsList.tpl
  modules/Vtiger/views/RecordsList.php
  public_html/layouts/basic/modules/Vtiger/resources/ListSearch.js
Labels: ✔ finished

#13568 Fixed #13500
  public_html/layouts/basic/modules/Vtiger/resources/Vtiger.js
Labels: ✔ finished

#13570 Fixed #12740
  app/Utils/Completions.php
Labels: ✔ finished

#13573 Fixed problem with ERR_CACHE_MISS on last step, while upload workflow
  layouts/basic/modules/Settings/Workflows/Step3.tpl
Labels: ✔ finished

#13574 Corrected view rbl action
  layouts/basic/modules/Settings/MailRbl/Index.tpl
  public_html/layouts/basic/styles/components/_Utilities.scss
Labels: ✔ finished

#13575 Fixed #12681
  modules/KnowledgeBase/actions/KnowledgeBaseAjax.php
Labels: ✔ finished

#13571 Fixed #12860
  layouts/basic/modules/Contacts/DetailViewHeaderTitle.tpl
  layouts/basic/modules/Users/ListViewContents.tpl
  layouts/basic/modules/Vtiger/BodyLeft.tpl
  public_html/layouts/basic/styles/_Style.scss
  public_html/layouts/basic/styles/pages/_Detail.scss
Labels: ✔ finished
