Repository YetiForceCompany/YetiForceCRM, pull requests merged in 2020-04, with the labels that each got.

#12770 Corrected view the panel in the Correction invoice module edition
  layouts/basic/modules/FCorectingInvoice/Detail/FullContents.tpl
  layouts/basic/modules/FCorectingInvoice/Edit/Inventory.tpl
Labels: ✔ finished

#12825 fixed #12820
  modules/Vtiger/models/Record.php
Labels: ✔ finished

#12816 fixed #11782
  app/Validator.php
  config/ConfigTemplates.php
  install/tpl/StepSystemConfiguration.tpl
  public_html/install/tpl/resources/Index.js
Labels: ✔ finished

#12842 Fixed #12740
  app/Utils/Completions.php
Labels: ✔ finished

#12848 Moved shop and deleted from summary
  install/install_schema/data.sql
  install/install_schema/scheme.sql
  languages/en-US/Settings/_Base.json
  languages/en-US/_Base.json
  layouts/basic/modules/Settings/Vtiger/Index.tpl
  layouts/basic/modules/Settings/YetiForce/Shop.tpl
Labels: ⏸ Not Finished

#12850 Removed unnecessary translations
  languages/en-US/FCorectingInvoice.json
  languages/en-US/FInvoice.json
  languages/en-US/FInvoiceCost.json
  languages/en-US/FInvoiceProforma.json
  languages/en-US/Other/PDF.json
  languages/en-US/SSingleOrders.json
Labels: ✔ finished

#12845 Corrected add new block
  modules/Settings/LayoutEditor/actions/Block.php
  public_html/layouts/basic/modules/Settings/LayoutEditor/resources/LayoutEditor.js
Labels: ✔ finished

#12810 Corrected verification in mass edit
  public_html/layouts/basic/modules/Vtiger/resources/List.js
Labels: ✔ finished

#12856 Changed position the information icon
  layouts/basic/modules/Settings/YetiForce/Shop.tpl
Labels: ✔ finished

#12857 Reduced padding in task list cron
  languages/en-US/Settings/CronTasks.json
  layouts/basic/modules/Settings/CronTasks/ListViewContents.tpl
Labels: ✔ finished

#12859 Added margin in button Edit in configuration smtp
  layouts/basic/modules/Settings/MailSmtp/DetailView.tpl
Labels: ✔ finished

#12861 Fix for currency and taxmode inventory fields
  modules/Vtiger/inventoryfields/Currency.php
Labels: ✔ finished

#12863 Changed link for setting
  app/Controller/View/Page.php
Labels: ✔ finished

#12899 Remodeled the user module
  install/install_schema/data.sql
  install/install_schema/scheme.sql
Labels: ✔ finished

#12896 Added description for fields in user module
  languages/en-US/Other/HelpInfo.json
Labels: ✔ finished

#12905 Corrected event selection in calendar extend
  public_html/layouts/basic/modules/Calendar/resources/Extended/CalendarView.js
Labels: ✔ finished

#12891 Fixed #12849
  modules/Vtiger/uitypes/Multipicklist.php
Labels: ✔ finished

#12908 Update package json
  package.json
  package_dev.json
Labels: ✔ finished

#12890 Fixed #12867
  app/TextParser/ProductsTableNew.php
Labels: ✔ finished

#12901 Add new menu user options
  app/Controller/View/Page.php
  languages/en-US/Users.json
  layouts/basic/modules/Vtiger/BodyHeader.tpl
  layouts/basic/modules/Vtiger/UserQuickMenu.tpl
  public_html/layouts/basic/styles/layout/_Header.scss
  public_html/layouts/basic/styles/layout/_Nav.scss
Labels: ⏸ Not Finished, 🔧 AmendmentsRequired

#12865 changed class names from long to short
  layouts/basic/modules/ModTracker/dashboards/UpdatesContents.tpl
  layouts/basic/modules/Settings/Companies/EditView.tpl
  layouts/basic/modules/Settings/Companies/Form.tpl
  layouts/basic/modules/Settings/Dav/Keys.tpl
  layouts/basic/modules/Settings/Help/Index.tpl
  layouts/basic/modules/Settings/Magento/ListViewHeader.tpl
  layouts/basic/modules/Settings/Map/Config.tpl
  layouts/basic/modules/Settings/Password/Encryption.tpl
  layouts/basic/modules/Settings/Profiles/EditView.tpl
  layouts/basic/modules/Settings/Vtiger/DashBoard/SettingsShortCut.tpl
  layouts/basic/modules/Settings/Vtiger/DashBoard/SystemMonitoring.tpl
  layouts/basic/modules/Settings/Vtiger/DashBoard/WidgetTitle.tpl
  layouts/basic/modules/Settings/Vtiger/IconsModal.tpl
  layouts/basic/modules/Settings/Vtiger/Index.tpl
  layouts/basic/modules/Settings/YetiForce/RegistrationOnlineModal.tpl
  layouts/basic/modules/Users/Modals/PasswordModal.tpl
  layouts/basic/modules/Vtiger/Comment.tpl
  layouts/basic/modules/Vtiger/Detail/Widget/BlockView.tpl
  layouts/basic/modules/Vtiger/ExceptionError.tpl
  layouts/basic/modules/Vtiger/RelatedActivities.tpl
  layouts/basic/modules/Vtiger/dashboards/MiniListContents.tpl
  public_html/layouts/basic/modules/MailIntegration/resources/outlookMessageCompose.js
  public_html/layouts/basic/modules/Vtiger/resources/dashboards/Widget.js
  public_html/layouts/basic/styles/components/_Utilities.scss
  public_html/layouts/resources/Fields.js
  public_html/src/layouts/basic/modules/Chat/components/Tabs/TabChatInput.vue
Labels: ✔ finished

#12910 Fixed problem with long content error message
  app/Layout.php
  layouts/basic/modules/Settings/Mail/ListViewContents.tpl
  modules/Settings/Mail/models/Record.php
Labels: ✔ finished

#12913 Fixed #12897
  install/install_schema/data.sql
  install/install_schema/scheme.sql
Labels: ✔ finished

#12912 Changed status update for cron task
  app/Cron.php
  modules/OSSMailScanner/OSSMailScanner.php
  modules/OSSMailScanner/models/Record.php
  modules/Vtiger/crons/BatchProcesses.php
  tests/Base/G_Cron.php
Labels: ✔ finished

#12895 Changed fields translation in user module
  languages/en-US/Users.json
Labels: ✔ finished

#12907 Corrected event selection in calendar extend
  public_html/layouts/basic/modules/Calendar/resources/Edit.js
  public_html/layouts/basic/modules/Calendar/resources/Extended/CalendarView.js
Labels: ✔ finished

#12814 Fixed #12787
  layouts/basic/modules/Vtiger/Detail/Widget/Basic.tpl
  public_html/layouts/basic/modules/Vtiger/resources/Detail.js
Labels: ✔ finished

#12923 Changed description translation for users module
  languages/en-US/Other/HelpInfo.json
  languages/en-US/Users.json
Labels: ✔ finished

#12924 Corrected translation
  languages/en-US/Other/HelpInfo.json
Labels: ✔ finished

#12927 Update Currency and Country list
  install/install_schema/data.sql
  install/install_schema/scheme.sql
Labels: ✔ finished

#12926 Improvements: create module and field
  modules/Settings/LayoutEditor/models/Module.php
  modules/Settings/ModuleManager/models/Module.php
Labels: ✔ finished

#12931 Validate if table exist before save
  modules/Settings/ModuleManager/models/Module.php
Labels: ✔ finished

#12933 Update lib_roundcube version
  config/version.php
Labels: ✔ finished

#12937 Improvement db importer
  app/Db/Importer.php
  app/Db/Importers/Base.php
Labels: ✔ finished
