Repository YetiForceCompany/YetiForceCRM, pull requests merged in 2020-10, with the labels that each got.

#13577 Fixed warning
  modules/OSSTimeControl/actions/GetTCInfo.php
  public_html/layouts/basic/modules/OSSTimeControl/resources/Edit.js
Labels: ✔ finished

#13578 Corrected view RBL
  layouts/basic/modules/Settings/MailRbl/DetailHeaderModal.tpl
  layouts/basic/modules/Settings/MailRbl/DetailModal.tpl
  layouts/basic/modules/Settings/MailRbl/Index.tpl
  public_html/layouts/basic/modules/Settings/MailRbl/resources/Index.js
  public_html/layouts/basic/styles/components/_Utilities.scss
Labels: ✔ finished

#13586 Remove portal module
  install/install_schema/data.sql
  install/install_schema/scheme.sql
  languages/en-US/Portal.json
  layouts/basic/modules/Portal/DetailView.tpl
  layouts/basic/modules/Portal/EditView.tpl
  layouts/basic/modules/Portal/ListViewContents.tpl
  layouts/basic/modules/Portal/ListViewHeader.tpl
  modules/Portal/actions/DeleteAjax.php
  modules/Portal/actions/MassDelete.php
  modules/Portal/actions/SaveAjax.php
  modules/Portal/models/ListView.php
  modules/Portal/models/Module.php
  modules/Portal/views/Detail.php
  modules/Portal/views/EditAjax.php
  modules/Portal/views/List.php
  modules/Portal/views/Pagination.php
  public_html/layouts/basic/modules/Portal/resources/Detail.js
  public_html/layouts/basic/modules/Portal/resources/Detail.min.js
  public_html/layouts/basic/modules/Portal/resources/Detail.min.js.map
  public_html/layouts/basic/modules/Portal/resources/List.js
  public_html/layouts/basic/modules/Portal/resources/List.min.js
  public_html/layouts/basic/modules/Portal/resources/List.min.js.map
  user_privileges/menu_0.php
  user_privileges/tabdata.php
Labels: ✔ finished

#13602 Added checking of ip addresses in the blacklist
  app/SystemWarnings/Security/GetBlackListIp.php
  app/SystemWarnings/SystemRequirements/DiskUsage.php
  languages/en-US/Settings/SystemWarnings.json
Labels: ✔ finished

#13603 Do not put CSP HEADERS, when CSP is disabled in config
  app/Headers.php
Labels: 👮‍♂️ VerificationRequired

#13605 Changed The query order in RBL
  modules/Settings/MailRbl/actions/GetData.php
Labels: ✔ finished

#13604 Moved styles for action buttons RBL and changed class name
  layouts/basic/modules/Settings/MailRbl/Index.tpl
  public_html/layouts/basic/modules/Settings/MailRbl/resources/Index.js
  public_html/layouts/basic/styles/components/_Utilities.scss
  public_html/layouts/basic/styles/layout/_Base.scss
Labels: ✔ finished

#13606 Fixed closing problem pnofify when modal is opened
  public_html/layouts/basic/styles/libraries/_Libraries.scss
Labels: ✔ finished

#13609 Corrected verify address IP in system warnings
  app/SystemWarnings/Security/GetBlackListIp.php
Labels: ✔ finished

#13584 Improvements comments layout and button
  layouts/basic/modules/Vtiger/Comment.tpl
  layouts/basic/modules/Vtiger/RecentComments.tpl
  modules/ModComments/models/Record.php
  public_html/layouts/basic/styles/libraries/_Quasar.scss
Labels: ✔ finished

#13613 Renamed file name GetBlackListIp.php to CheckServerIpInBlackList.php and changed translation
  app/SystemWarnings/Security/CheckServerIpInBlackList.php
  languages/en-US/Settings/SystemWarnings.json
Labels: ✔ finished

#13611 Added "To" value in email widget
  layouts/basic/modules/OSSMailView/widgets.tpl
  public_html/layouts/basic/styles/_Style.scss
Labels: ✔ finished

#13616 Changed The appearance of the email widget
  layouts/basic/modules/OSSMailView/widgets.tpl
  public_html/layouts/basic/styles/_Style.scss
  public_html/layouts/basic/styles/components/_Utilities.scss
Labels: ✔ finished

#13618 Changed The appearance of the email widget
  layouts/basic/modules/OSSMailView/MailsPreview.tpl
  layouts/basic/modules/OSSMailView/widgets.tpl
  public_html/layouts/basic/styles/_Style.scss
Labels: ✔ finished

#13620 Changed The appearance of the email widget
  layouts/basic/modules/OSSMailView/MailsPreview.tpl
  layouts/basic/modules/OSSMailView/widgets.tpl
  public_html/layouts/basic/modules/Vtiger/resources/Detail.js
  public_html/layouts/basic/styles/_Style.scss
  public_html/layouts/basic/styles/components/_Utilities.scss
Labels: ✔ finished

#13621 Changed The appearance of the email widget
  layouts/basic/modules/OSSMailView/MailsPreview.tpl
  layouts/basic/modules/OSSMailView/widgets.tpl
Labels: ✔ finished

#13622 Added url to href in widget email
  layouts/basic/modules/OSSMailView/MailsPreview.tpl
  layouts/basic/modules/OSSMailView/widgets.tpl
  public_html/layouts/basic/modules/Vtiger/resources/Detail.js
Labels: ✔ finished

#13623 Fixed display of the mail list in the modal with no filters
  public_html/layouts/basic/modules/Vtiger/resources/Detail.js
Labels: ✔ finished

#13624 Removed unnecessary styles
  public_html/layouts/basic/styles/_Style.scss
Labels: ✔ finished

#13663 Added button to documentation
  layouts/basic/modules/Settings/CronTasks/ListViewHeader.tpl
  layouts/basic/modules/Settings/OSSMailScanner/Index.tpl
Labels: ✔ finished

#13649 Improved textparser
  app/TextParser/ProductsTableRelatedModule.php
Labels: ✔ finished

#13666 Corrected progress belt in language download model
  layouts/basic/modules/Settings/YetiForce/DownloadLanguageModal.tpl
  public_html/layouts/basic/styles/components/_Utilities.scss
Labels: ✔ finished

#13665 Added translation
  languages/en-US/Other/TextParser.json
Labels: ✔ finished

#13673 Removed rounding of the logo and Corrected icons in timeline
  layouts/basic/modules/Vtiger/BodyLeft.tpl
  layouts/basic/modules/Vtiger/RecentActivitiesTimeLine.tpl
  public_html/layouts/basic/styles/pages/_Detail.scss
Labels: ✔ finished

#13680 Changed function array_merge to array_merge_recursive
  app/YetiForce/Register.php
  modules/OpenStreetMap/files/TileLayer.php
Labels: ✔ finished

#13662 Corrected the email widget and view the email preview
  languages/en-US/_Base.json
  layouts/basic/modules/Assets/dashboards/ExpiringSoldProducts.tpl
  layouts/basic/modules/OSSMailView/MailsPreview.tpl
  layouts/basic/modules/OSSMailView/preview.tpl
  layouts/basic/modules/OSSMailView/widgets.tpl
  modules/OSSMailView/views/Preview.php
Labels: ✔ finished

#13683 Fixed notifications
  layouts/basic/modules/Calendar/EditViewActions.tpl
  layouts/basic/modules/OSSPasswords/EditViewActions.tpl
  layouts/basic/modules/Settings/LayoutEditor/NewCustomBlock.tpl
  layouts/basic/modules/Vtiger/EditViewActions.tpl
  modules/FInvoice/dashboards/SummationByUser.php
  modules/OSSMail/models/Record.php
  modules/OSSTimeControl/dashboards/TimeControl.php
Labels: ✔ finished

#13693 DB update: Add fields payments_sum
  install/install_schema/data.sql
  install/install_schema/scheme.sql
Labels: ✔ finished

#13681 Corrected responsiveness the email widget for mobile
  layouts/basic/modules/OSSMailView/widgets.tpl
Labels: ⏸ Not Finished

#13682 Fixed mail widget
  layouts/basic/modules/Vtiger/dashboards/MailsListContents.tpl
  modules/Vtiger/dashboards/MailsList.php
Labels: ✔ finished

#13699 Added Profiling for the imap function
  app/Mailer.php
  modules/OSSMail/models/Record.php
  modules/OSSMailScanner/models/Record.php
Labels: ✔ finished

#13701 DB UPDATE: Field improvements on FInvoice proforma
  install/install_schema/data.sql
  install/install_schema/scheme.sql
Labels: 🔧 AmendmentsRequired

#13704 Improved copying data from related module
  layouts/basic/modules/Vtiger/BlockHeader.tpl
  public_html/layouts/basic/modules/Vtiger/resources/Edit.js
Labels: ✔ finished

#13705 Fixed problem with double notification while deleting PDF template
  public_html/layouts/basic/modules/Settings/PDF/resources/List.js
Labels: ✔ finished

#13585 Fixed #10112
  layouts/basic/modules/Settings/Vtiger/AdvanceFilterCondition.tpl
  layouts/basic/modules/Settings/Workflows/AdvanceFilterCondition.tpl
  layouts/basic/modules/Settings/Workflows/Tasks/VTUpdateFieldsTask.tpl
  layouts/basic/modules/Vtiger/AdvanceFilterCondition.tpl
Labels: ✔ finished

#13525 Clear previous address field data when copied value is empty.
  public_html/layouts/basic/modules/Vtiger/resources/Edit.js
Labels: ✔ finished

#13537 Add special functionality to give special additional parameters in widget (for example sorting by selected field).
  layouts/basic/modules/Vtiger/Detail/Widget/Activities.tpl
  modules/Vtiger/models/RelationListView.php
  modules/Vtiger/widgets/Activities.php
  public_html/layouts/basic/modules/Vtiger/resources/Detail.js
Labels: ✔ finished

#13337 Improved modtracker
  languages/en-US/ModTracker.json
  layouts/basic/modules/Vtiger/RecentActivitiesTimeLine.tpl
  layouts/basic/modules/Vtiger/dashboards/HistoryContents.tpl
Labels: ✔ finished

#13572 Fixed password detail view, improved modTracker when showing hidden data
  install/install_schema/data.sql
  install/install_schema/scheme.sql
  languages/en-US/ModTracker.json
  layouts/basic/modules/Vtiger/RecentActivitiesTimeLine.tpl
  modules/ModTracker/ModTracker.php
  modules/ModTracker/handlers/ModTrackerHandler.php
  modules/ModTracker/models/Record.php
  modules/OSSPasswords/actions/GetPass.php
Labels: ✔ finished

#13707 Add "Go to full form" button on quickEdit
  layouts/basic/modules/Vtiger/Modals/QuickEditHeader.tpl
  modules/Vtiger/views/QuickEditModal.php
  public_html/layouts/resources/app.js
Labels: ✔ finished
