Repository YetiForceCompany/YetiForceCRM, pull requests merged in 2020-05, with the labels that each got.

#12997 Added comments relation
  layouts/basic/modules/Vtiger/Detail/Widget/BasicComments.tpl
  modules/Vtiger/views/Detail.php
Labels: ✔ finished

#12801 Added Gus record collector
  app/RecordCollectors/Gus.php
  app/RecordCollectors/helper/GusClient.php
  install/install_schema/data.sql
  install/install_schema/scheme.sql
  languages/en-US/Settings/Profiles.json
  languages/en-US/_Base.json
  layouts/basic/modules/Vtiger/EditViewActions.tpl
  layouts/basic/modules/Vtiger/Modals/RecordCollector.tpl
  layouts/basic/modules/Vtiger/Modals/RecordCollectorSearch.tpl
  modules/Vtiger/views/RecordCollector.php
  public_html/layouts/basic/modules/Vtiger/resources/Edit.js
Labels: ✔ finished

#13004 Addded possibility of retrieve default phone value
  config/Components/ConfigTemplates.php
  languages/en-US/Settings/Countries.json
  layouts/basic/modules/Settings/Countries/Index.tpl
  layouts/basic/modules/Vtiger/Edit/Field/Phone.tpl
  modules/Settings/Countries/actions/SaveAjax.php
  public_html/layouts/basic/modules/Settings/Countries/resources/Index.js
Labels: ✔ finished

#13003 Improved getting filterFields from request
  modules/Vtiger/views/RecordsList.php
Labels: ✔ finished

#12911 Improved menu, fixed problem with scroll
  app/Controller/View/Page.php
  config/ConfigTemplates.php
  config/Performance.php
  languages/en-US/Users.json
  layouts/basic/modules/Users/Modals/LoginHistoryModal.tpl
  layouts/basic/modules/Vtiger/BodyHeader.tpl
  layouts/basic/modules/Vtiger/UserQuickMenu.tpl
  modules/Users/actions/Logout.php
  modules/Users/models/Module.php
  modules/Users/views/LoginHistory.php
  public_html/layouts/basic/styles/layout/_Header.scss
Labels: ⏸ Not Finished

#12858 Add posibility to have split edit view on non-inventory modules.
  config/ConfigTemplates.php
  config/Performance.php
  layouts/basic/modules/Vtiger/EditViewBlocks.tpl
  modules/Vtiger/views/Edit.php
Labels: ✔ finished

#12864 Add information about editing fields in admin panel. Allow to edit fields in Calendar
  languages/en-US/Settings/LayoutEditor.json
  layouts/basic/modules/Settings/LayoutEditor/Index.tpl
  modules/Settings/LayoutEditor/models/Field.php
  modules/Settings/LayoutEditor/models/Module.php
Labels: ✔ finished

#12739 fixed #12731
  layouts/basic/modules/Vtiger/Detail/Widget/Activities.tpl
  layouts/basic/modules/Vtiger/Detail/Widget/Basic.tpl
  layouts/basic/modules/Vtiger/Detail/Widget/BasicComments.tpl
  layouts/basic/modules/Vtiger/Detail/Widget/DetailView.tpl
  layouts/basic/modules/Vtiger/Detail/Widget/EmailList.tpl
  layouts/basic/modules/Vtiger/Detail/Widget/FastEdit.tpl
  layouts/basic/modules/Vtiger/Detail/Widget/GeneralInfo.tpl
  layouts/basic/modules/Vtiger/Detail/Widget/HistoryRelation.tpl
  layouts/basic/modules/Vtiger/Detail/Widget/ProductsServicesBasic.tpl
  layouts/basic/modules/Vtiger/Detail/Widget/SummaryCategory.tpl
  layouts/basic/modules/Vtiger/Detail/Widget/Updates.tpl
  layouts/basic/modules/Vtiger/Detail/Widget/WYSIWYG.tpl
  public_html/layouts/basic/styles/_Mixins.scss
  public_html/layouts/basic/styles/components/_Global.scss
Labels: ✔ finished

#12426 Add user login history in reports
  app/TextParser/UserLoginHistory.php
  app/User.php
  languages/en-US/Other/Reports.json
  languages/en-US/Other/TextParser.json
  languages/en-US/_Base.json
  modules/Users/models/Module.php
Labels: ✔ finished

#12041 Improved multifilter widget.
  languages/en-US/_Base.json
  layouts/basic/modules/Settings/WidgetsManagement/Configuration.tpl
  layouts/basic/modules/Settings/WidgetsManagement/WidgetConfig.tpl
  layouts/basic/modules/Vtiger/dashboards/DashBoardContents.tpl
  layouts/basic/modules/Vtiger/dashboards/MiniListContents.tpl
  layouts/basic/modules/Vtiger/dashboards/MiniListWizard.tpl
  layouts/basic/modules/Vtiger/dashboards/MultifilterContents.tpl
  modules/Settings/WidgetsManagement/actions/SaveAjax.php
  modules/Settings/WidgetsManagement/models/Module.php
  modules/Settings/WidgetsManagement/views/Configuration.php
  modules/Vtiger/dashboards/MiniList.php
  modules/Vtiger/dashboards/Multifilter.php
  public_html/layouts/basic/modules/Settings/WidgetsManagement/resources/WidgetsManagement.js
  public_html/layouts/basic/modules/Vtiger/resources/DashBoard.js
  public_html/layouts/basic/modules/Vtiger/resources/dashboards/Widget.js
Labels: ✔ finished

#12805 Change tree view from select to modal on listview
  app/Condition.php
  app/Conditions/QueryFields/CategoryMultipicklistField.php
  app/Conditions/QueryFields/MultipicklistField.php
  app/Conditions/QueryFields/TreeField.php
  app/QueryGenerator.php
  languages/en-US/_Base.json
  layouts/basic/modules/Settings/Workflows/AdvanceFilterCondition.tpl
  layouts/basic/modules/Vtiger/ConditionBuilder/Tree.tpl
  layouts/basic/modules/Vtiger/List/Field/Tree.tpl
  layouts/basic/modules/Vtiger/ListViewContents.tpl
  layouts/basic/modules/Vtiger/Modals/RecordsList.tpl
  layouts/basic/modules/Vtiger/RelatedListContents.tpl
  layouts/basic/modules/Vtiger/dashboards/WidgetHeader.tpl
  modules/PriceBooks/views/Detail.php
  modules/Vtiger/helpers/AdvancedFilter.php
  modules/Vtiger/uitypes/CategoryMultipicklist.php
  modules/Vtiger/uitypes/Tree.php
  modules/Vtiger/views/List.php
  modules/Vtiger/views/RecordsList.php
  modules/com_vtiger_workflow/VTJsonCondition.php
  public_html/layouts/basic/modules/CustomView/resources/CustomView.js
  public_html/layouts/basic/modules/Settings/Workflows/resources/AdvanceFilter.js
  public_html/layouts/basic/modules/Vtiger/resources/AdvanceFilter.js
  public_html/layouts/basic/modules/Vtiger/resources/DashBoard.js
  public_html/layouts/basic/modules/Vtiger/resources/Edit.js
  public_html/layouts/basic/modules/Vtiger/resources/ListSearch.js
  public_html/layouts/basic/modules/Vtiger/resources/dashboards/Widget.js
  public_html/layouts/resources/Fields.js
Labels: ✔ finished, 👮‍♂️ VerificationRequired

#13026 Added functionality of label coloring
  app/Colors.php
  app/Components/ColorPickerModal.php
  app/Controller/View/Base.php
  install/install_schema/data.sql
  install/install_schema/scheme.sql
  languages/en-US/Settings/Colors.json
  layouts/basic/modules/OSSPasswords/Detail/BlockView.tpl
  layouts/basic/modules/OSSPasswords/EditViewBlocks.tpl
  layouts/basic/modules/Settings/Colors/Index.tpl
  layouts/basic/modules/Settings/Colors/TabFieldColors.tpl
  layouts/basic/modules/Settings/Colors/TabPicklistValuesColors.tpl
  layouts/basic/modules/Vtiger/Detail/BlockView.tpl
  layouts/basic/modules/Vtiger/EditViewBlocks.tpl
  layouts/basic/modules/Vtiger/QuickCreate.tpl
  modules/Settings/Colors/actions/SaveAjax.php
  modules/Settings/Colors/views/IndexAjax.php
  public_html/layouts/basic/modules/Settings/Colors/resources/Index.js
  vtlib/Vtiger/FieldBasic.php
Labels: ✔ finished

#13031 The category input view has been unified
  public_html/layouts/basic/styles/pages/_Dashboard.scss
  public_html/layouts/basic/styles/pages/_List.scss
Labels: ✔ finished

#13036 The category input view has been unified
  public_html/layouts/basic/styles/pages/_Dashboard.scss
Labels: ✔ finished

#13049 Corrected view left panel Tree - Product module
  layouts/basic/modules/Vtiger/TreeRecordsPostProcess.tpl
  layouts/basic/modules/Vtiger/TreeRecordsPreProcess.tpl
  public_html/layouts/basic/styles/components/_Global.scss
Labels: ✔ finished

#13051 Corrected view in module Correction invoices
  layouts/basic/modules/FCorectingInvoice/Edit/Inventory.tpl
Labels: ✔ finished

#13058 corrected display of values depending on the maximum number of characters
  public_html/layouts/basic/styles/components/_Utilities.scss
Labels: ✔ finished

#13096 Improved the update of records from related modules (workflow task)
  modules/com_vtiger_workflow/tasks/VTUpdateRelatedFieldTask.php
Labels: ✔ finished
