Repository YetiForceCompany/YetiForceCRM, pull requests merged in 2021-02, with the labels that each got.

#14107 Deleted setting module Hide block
  install/install_schema/data.sql
  install/install_schema/scheme.sql
  languages/en-US/Settings/HideBlocks.json
  layouts/basic/modules/KnowledgeBase/DetailViewBlockView.tpl
  layouts/basic/modules/OSSMailView/DetailViewBlockView.tpl
  layouts/basic/modules/OSSPasswords/EditViewBlocks.tpl
  layouts/basic/modules/Settings/HideBlocks/Conditions.tpl
  layouts/basic/modules/Settings/HideBlocks/EditView.tpl
  layouts/basic/modules/Settings/HideBlocks/ListViewHeader.tpl
  layouts/basic/modules/Vtiger/Detail/BlocksView.tpl
  layouts/basic/modules/Vtiger/Detail/Widget/BlockView.tpl
  layouts/basic/modules/Vtiger/EditViewBlocks.tpl
  modules/Settings/HideBlocks/actions/DeleteAjax.php
  modules/Settings/HideBlocks/actions/Save.php
  modules/Settings/HideBlocks/models/ListView.php
  modules/Settings/HideBlocks/models/Module.php
  modules/Settings/HideBlocks/models/Record.php
  modules/Settings/HideBlocks/views/Conditions.php
  modules/Settings/HideBlocks/views/Edit.php
  modules/Settings/HideBlocks/views/List.php
  modules/Vtiger/models/Block.php
  public_html/layouts/basic/modules/Settings/HideBlocks/resources/AdvanceFilter.js
  public_html/layouts/basic/modules/Settings/HideBlocks/resources/AdvanceFilter.min.js
  public_html/layouts/basic/modules/Settings/HideBlocks/resources/AdvanceFilter.min.js.map
  public_html/layouts/basic/modules/Settings/HideBlocks/resources/Conditions.js
  public_html/layouts/basic/modules/Settings/HideBlocks/resources/Conditions.min.js
  public_html/layouts/basic/modules/Settings/HideBlocks/resources/Conditions.min.js.map
Labels: ✔ finished

#14136 Changed button action place in users module
  languages/en-US/Users.json
  languages/en-US/_Base.json
  layouts/basic/modules/Users/ListViewContents.tpl
  modules/Users/models/Record.php
  public_html/layouts/basic/modules/Users/resources/Detail.js
  public_html/layouts/basic/modules/Users/resources/List.js
Labels: ✔ finished

#14114 Corrected Anonymization in change history
  layouts/basic/modules/Vtiger/RecentActivities.tpl
Labels: ⏸ Not Finished

#14063 Changed class name
  public_html/layouts/basic/modules/Settings/Vtiger/resources/Index.js
  public_html/layouts/basic/modules/Vtiger/resources/AdvanceFilter.js
  public_html/layouts/resources/Field.js
Labels: ✔ finished

#14145 Changed label in translation
  public_html/layouts/basic/modules/Users/resources/List.js
Labels: ✔ finished

#14043 #13927
  modules/Vtiger/models/Export.php
  modules/Vtiger/views/Export.php
Labels: ✔ finished

#14030 Improved display value if picklist is set as label
  layouts/basic/modules/OSSPasswords/RelatedListContents.tpl
  layouts/basic/modules/Vtiger/RelatedListContents.tpl
Labels: ✔ finished

#13840 Added new tabs for handler events
  app/EventHandler.php
  languages/en-US/Settings/EventHandler.json
  layouts/basic/modules/Settings/EventHandler/Index.tpl
Labels: ⏸ Not Finished

#14146 Corrected error in discount and tax in inventory module
  layouts/basic/modules/Vtiger/Edit/Inventory.tpl
Labels: ✔ finished

#14042 Set Correct validator Engine for inventory Fields
  layouts/basic/modules/Vtiger/inventoryfields/EditViewDouble.tpl
  layouts/basic/modules/Vtiger/inventoryfields/EditViewInteger.tpl
  layouts/basic/modules/Vtiger/inventoryfields/EditViewQuantity.tpl
  layouts/basic/modules/Vtiger/inventoryfields/EditViewUnitPrice.tpl
Labels: 👮‍♂️ VerificationRequired

#14153 Added configuration proxy
  install/install_schema/data.sql
  install/install_schema/scheme.sql
  languages/en-US/Settings/Proxy.json
  layouts/basic/modules/Settings/Proxy/Index.tpl
  modules/Settings/Proxy/actions/SaveConfigForm.php
  modules/Settings/Proxy/models/ConfigForm.php
  modules/Settings/Proxy/views/Index.php
Labels: ✔ finished

#14162 Added field to enable/disable purpose of visit
  languages/en-US/Settings/AdminAccess.json
  layouts/basic/modules/Settings/AdminAccess/HistoryAdminsVisitPurpose.tpl
  modules/Settings/AdminAccess/actions/SaveConfigForm.php
  modules/Settings/AdminAccess/models/Module.php
  modules/Settings/AdminAccess/views/Index.php
  public_html/layouts/basic/modules/Settings/AdminAccess/resources/Index.js
Labels: ✔ finished

#14166 Changed columns in module Approvals Register
  install/install_schema/data.sql
Labels: ✔ finished

#14164 Corrected Panels expansion in all views
  public_html/layouts/basic/modules/Vtiger/resources/Detail.js
  public_html/layouts/resources/app.js
Labels: ✔ finished

#14132 Corrected icons path in tree
  modules/Settings/TreesManager/models/Record.php
Labels: 👮‍♂️ VerificationRequired

#13738 [FIX] FE: MultiEmail field consent click - YFBL0154
  layouts/basic/modules/Vtiger/Edit/Field/MultiEmail.tpl
  layouts/basic/modules/Vtiger/Edit/Field/MultiEmailValue.tpl
  public_html/layouts/resources/Fields.js
Labels: 👮‍♂️ VerificationRequired

#14177 Corrected field multi email
  layouts/basic/modules/Vtiger/Edit/Field/MultiEmail.tpl
  layouts/basic/modules/Vtiger/Edit/Field/MultiEmailValue.tpl
  public_html/layouts/resources/Fields.js
Labels: ⏸ Not Finished

#14185 Corrected multi email field
  layouts/basic/modules/Vtiger/Edit/Field/MultiEmail.tpl
  layouts/basic/modules/Vtiger/Edit/Field/MultiEmailValue.tpl
  public_html/layouts/basic/styles/components/_Utilities.scss
  public_html/layouts/resources/validator/FieldValidator.js
Labels: ✔ finished

#14186 Added record collector to profile
  install/install_schema/data.sql
  modules/Settings/ModuleManager/models/Module.php
Labels: ✔ finished

#14176 Added translation
  languages/en-US/Settings/LayoutEditor.json
Labels: ✔ finished

#14174 Added function encodeHtml()
  layouts/basic/modules/Calendar/Edit/Field/Date.tpl
  layouts/basic/modules/Calendar/Edit/Field/Time.tpl
  layouts/basic/modules/Documents/MoveDocuments.tpl
  layouts/basic/modules/OSSPasswords/Edit/Field/Base.tpl
  layouts/basic/modules/PriceBooks/Edit/Field/Boolean.tpl
  layouts/basic/modules/Settings/Inventory/Index.tpl
  layouts/basic/modules/Settings/LayoutEditor/CreateFieldModal.tpl
  layouts/basic/modules/Settings/LayoutEditor/Index.tpl
  layouts/basic/modules/Settings/Picklist/AssignValueToRole.tpl
  layouts/basic/modules/Settings/Picklist/CreateView.tpl
  layouts/basic/modules/Settings/Picklist/EditView.tpl
  layouts/basic/modules/Settings/SharingAccess/Index.tpl
  layouts/basic/modules/Settings/Vtiger/AdvanceFilterCondition.tpl
  layouts/basic/modules/Settings/WidgetsManagement/Configuration.tpl
  layouts/basic/modules/Settings/Workflows/AdvanceFilterCondition.tpl
  layouts/basic/modules/Users/Edit/Field/Password.tpl
  layouts/basic/modules/Vtiger/Detail/Widget/Basic.tpl
  layouts/basic/modules/Vtiger/Detail/Widget/FastEdit.tpl
  layouts/basic/modules/Vtiger/Edit/Field/Boolean.tpl
  layouts/basic/modules/Vtiger/Edit/Field/Currency.tpl
  layouts/basic/modules/Vtiger/Edit/Field/Date.tpl
  layouts/basic/modules/Vtiger/Edit/Field/DateTime.tpl
  layouts/basic/modules/Vtiger/Edit/Field/DocumentsFileUpload.tpl
  layouts/basic/modules/Vtiger/Edit/Field/Double.tpl
  layouts/basic/modules/Vtiger/Edit/Field/Email.tpl
  layouts/basic/modules/Vtiger/Edit/Field/Image.tpl
  layouts/basic/modules/Vtiger/Edit/Field/MeetingUrl.tpl
  layouts/basic/modules/Vtiger/Edit/Field/Modules.tpl
  layouts/basic/modules/Vtiger/Edit/Field/MultiDomain.tpl
  layouts/basic/modules/Vtiger/Edit/Field/MultiImage.tpl
  layouts/basic/modules/Vtiger/Edit/Field/MultiListFields.tpl
  layouts/basic/modules/Vtiger/Edit/Field/MultiPicklist.tpl
  layouts/basic/modules/Vtiger/Edit/Field/Number.tpl
  layouts/basic/modules/Vtiger/Edit/Field/Owner.tpl
  layouts/basic/modules/Vtiger/Edit/Field/Password.tpl
  layouts/basic/modules/Vtiger/Edit/Field/Percentage.tpl
  layouts/basic/modules/Vtiger/Edit/Field/Phone.tpl
  layouts/basic/modules/Vtiger/Edit/Field/Picklist.tpl
  layouts/basic/modules/Vtiger/Edit/Field/Recurrence.tpl
  layouts/basic/modules/Vtiger/Edit/Field/ReferenceSubProcess.tpl
  layouts/basic/modules/Vtiger/Edit/Field/Taxes.tpl
  layouts/basic/modules/Vtiger/Edit/Field/Text.tpl
  layouts/basic/modules/Vtiger/Edit/Field/Time.tpl
  layouts/basic/modules/Vtiger/Edit/Field/Twitter.tpl
  layouts/basic/modules/Vtiger/Edit/Field/Url.tpl
  layouts/basic/modules/Vtiger/inventoryfields/EditViewComment.tpl
Labels: ✔ finished

#13736 [IMPROVEMENT] FE / BE: lineitem comments - YFBL0118
  languages/en-US/Settings/LayoutEditor.json
  layouts/basic/modules/Settings/LayoutEditor/inventoryTypes/Comment.tpl
  layouts/basic/modules/Vtiger/inventoryfields/DetailViewName.tpl
  layouts/basic/modules/Vtiger/inventoryfields/EditViewComment.tpl
  modules/Vtiger/inventoryfields/Comment.php
Labels: 👮‍♂️ VerificationRequired

#14187 Deleted escape in EditViewComment.tpl
  layouts/basic/modules/Vtiger/inventoryfields/EditViewComment.tpl
Labels: ✔ finished

#14188 Corrected height if footer non active
  app/Controller/View/Page.php
  layouts/basic/modules/Vtiger/Footer.tpl
  layouts/basic/modules/Vtiger/PageHeader.tpl
  public_html/layouts/basic/styles/_Style.scss
  public_html/layouts/basic/styles/components/_Global.scss
  public_html/layouts/basic/styles/layout/_Base.scss
  public_html/layouts/basic/styles/pages/_Edit.scss
Labels: ✔ finished

#14211 Standardized the email templates
  install/install_schema/data.sql
Labels: ✔ finished

#14222 Fixed deletion of records in system settings modules
  modules/Settings/AdvancedPermission/actions/DeleteAjax.php
  modules/Settings/AdvancedPermission/models/Record.php
  modules/Settings/AutomaticAssignment/actions/DeleteAjax.php
  modules/Settings/BusinessHours/actions/DeleteAjax.php
  modules/Settings/BusinessHours/models/Record.php
  modules/Settings/Companies/actions/DeleteAjax.php
  modules/Settings/Companies/models/Record.php
  modules/Settings/Mail/actions/DeleteAjax.php
  modules/Settings/Mail/models/Record.php
  modules/Settings/MailSmtp/actions/DeleteAjax.php
  modules/Settings/MailSmtp/models/Record.php
  modules/Settings/PBX/actions/DeleteAjax.php
  modules/Settings/SMSNotifier/actions/DeleteAjax.php
  public_html/layouts/basic/modules/Settings/Companies/resources/Detail.js
  public_html/layouts/basic/modules/Settings/Mail/resources/Detail.js
  public_html/layouts/basic/modules/Settings/MailSmtp/resources/Detail.js
Labels: ✔ finished

#14225 Corrected convert lead in list preview
  layouts/basic/modules/Leads/ConvertLead.tpl
Labels: ✔ finished

#14229 Added new column to view in mail smtp module
  layouts/basic/modules/Settings/MailSmtp/ListViewContents.tpl
  modules/Settings/MailSmtp/models/Module.php
Labels: ✔ finished

#14230 Corrected user img in users list
  layouts/basic/modules/Users/ListViewContents.tpl
  public_html/layouts/basic/styles/components/_Global.scss
Labels: ✔ finished

#14248 Improved selecting picklist values if widget is cached after page refresh
  layouts/basic/modules/Vtiger/dashboards/MiniList.tpl
  modules/Vtiger/dashboards/MiniList.php
Labels: ✔ finished

#14285 Fixed #14228
  app/Layout.php
  layouts/basic/modules/KnowledgeBase/DetailViewBlockView.tpl
  layouts/basic/modules/OSSPasswords/Detail/BlockView.tpl
  layouts/basic/modules/Vtiger/Detail/BlockView.tpl
  layouts/basic/modules/Vtiger/Detail/Widget/BlockView.tpl
  layouts/basic/modules/Vtiger/Detail/Widget/GeneralInfo.tpl
  modules/Vtiger/uitypes/MeetingUrl.php
  public_html/layouts/basic/modules/Vtiger/resources/Detail.js
  public_html/layouts/basic/styles/userPreferences/_RowHeight.scss
Labels: ✔ finished

#14251 Fixed #14182
  modules/OSSTimeControl/models/Calendar.php
  modules/Reservations/models/Calendar.php
Labels: ✔ finished
