Repository YetiForceCompany/YetiForceCRM, pull requests merged in 2022-07, with the labels that each got.

#16231 UKVatPayerStatusVerification improvement
  app/RecordCollectors/UKVatPayerStatusVerification.php
Labels: ✔ finished, php

#16232 Add search by company name to UKCompaniesHouse.php
  app/RecordCollectors/UKCompaniesHouse.php
  languages/en-US/Other/RecordCollector.json
Labels: ✔ finished

#16233 Change taxNumber to ncr
  app/RecordCollectors/PLNationalCourtRegister.php
Labels: ✔ finished

#16237 Parsing data for UKCompaniesHouse for searching by name [in progress]
  app/RecordCollectors/UKCompaniesHouse.php
Labels: php

#16238 Added record collector task to workflows.
  app/RecordCollector.php
  app/RecordCollectors/Base.php
  install/install_schema/data.sql
  install/install_schema/scheme.sql
  layouts/basic/modules/Settings/Workflows/Tasks/RecordCollector.tpl
  modules/com_vtiger_workflow/tasks/RecordCollector.php
  public_html/layouts/basic/modules/Settings/Workflows/resources/Edit3.js
Labels: ⏸ Not Finished

#16240 Added image preview in tiles view
  languages/en-US/_Base.json
  layouts/basic/modules/Vtiger/Modals/ImagePreview.tpl
  layouts/basic/modules/Vtiger/TilesContents.tpl
  modules/Vtiger/uitypes/MultiImage.php
  modules/Vtiger/views/ImagePreview.php
  public_html/layouts/basic/modules/Vtiger/resources/Tiles.js
Labels: ✔ finished

#16251 Change data display order in RecordCollectors.
  app/RecordCollectors/Gus.php
  app/RecordCollectors/PLCeidg.php
  app/RecordCollectors/PLNationalCourtRegister.php
  app/RecordCollectors/UKCompaniesHouse.php
  app/RecordCollectors/USAEdgarRegistryFromSec.php
Labels: ✔ finished

#16252 Add OrbIntelligence.php to Record Collectors. v1
  app/RecordCollectors/OrbIntelligence.php
  languages/en-US/Other/RecordCollector.json
Labels: ✔ finished

#16256 Add ApiGovFrance.php to Record Collectors.
  app/RecordCollectors/FREnterpriseGouv.php
  languages/en-US/Other/RecordCollector.json
Labels: ✔ finished

#16262 Add BRACnpj.php to Record Collectors
  app/RecordCollectors/BRReceitaCnpj.php
  languages/en-US/Other/RecordCollector.json
Labels: ✔ finished

#16264 Improved the advanced block view in related modules.
  layouts/basic/modules/Vtiger/RelatedListContents.tpl
Labels: ✔ finished

#16265 Narrowed search by empty values to entity modules
  layouts/basic/modules/Vtiger/List/Field/Base.tpl
Labels: ✔ finished

#16248 Improved image preview in tiles view
  modules/Vtiger/uitypes/MultiImage.php
  public_html/layouts/basic/modules/Vtiger/resources/Tiles.js
Labels: ✔ finished

#16203 Standardized the tables with the list of records.
  app/TextParser.php
  app/TextParser/RecordsList.php
  languages/en-US/Other/TextParser.json
Labels: ✔ finished

#16267 add NOEnhetsregisteret.php to Record Collectors.
  app/RecordCollectors/NOEnhetsregisteret.php
  languages/en-US/Other/RecordCollector.json
Labels: ✔ finished, php

#16277 Secure RecordCollectors.
  app/RecordCollector.php
  layouts/basic/modules/Vtiger/EditViewActions.tpl
  layouts/basic/modules/Vtiger/QuickCreate.tpl
Labels: ✔ finished, php

#16290 ISO Codes.
  app/RecordCollectors/VatifyEu.php
Labels: ✔ finished

#16291 Improved the quick calendar creation view.
  layouts/basic/modules/Calendar/Calendar/EventForm.tpl
Labels: ✔ finished

#16303 Improved month view in quick calendar creation
  public_html/layouts/basic/modules/Vtiger/resources/CalendarView.js
  public_html/layouts/basic/styles/components/_Utilities.scss
Labels: ✔ finished

#16304 Added information about the loss of the right to quickly edit a given dictionary in the kanban configuration
  languages/en-US/Settings/Kanban.json
  layouts/basic/modules/Settings/Kanban/Fields.tpl
Labels: ✔ finished

#16306 Added verification if the given user has rights for the Announcements module.
  modules/Announcements/models/Module.php
Labels: ✔ finished

#16308 Added translation.
  languages/en-US/Settings/Watchdog.json
Labels: ✔ finished
