Repository YetiForceCompany/YetiForceCRM, pull requests merged in 2022-05, with the labels that each got.

#16004 CSS improvments
  public_html/layouts/basic/styles/components/_Utilities.scss
  public_html/layouts/basic/styles/layout/_Header.scss
  public_html/layouts/basic/styles/pages/_List.scss
Labels: ✔ finished

#16026 Added action for TileView
  install/install_schema/data.sql
Labels: ✔ finished

#16031 EditField.tpl remove information icon & add space
  layouts/basic/modules/Settings/LayoutEditor/EditField.tpl
Labels: ✔ finished, php

#16028 Added possibiliy of sorting tasks and actions in workflows
  languages/en-US/Settings/Workflows.json
  layouts/basic/modules/Settings/Workflows/ListViewHeader.tpl
  layouts/basic/modules/Settings/Workflows/SortActionsModal.tpl
  layouts/basic/modules/Settings/Workflows/TasksList.tpl
  modules/Settings/Workflows/actions/SaveAjax.php
  modules/Settings/Workflows/actions/TaskAjax.php
  modules/Settings/Workflows/models/Module.php
  modules/Settings/Workflows/models/Record.php
  modules/Settings/Workflows/models/TaskRecord.php
  modules/Settings/Workflows/views/SortActionsModal.php
  modules/com_vtiger_workflow/VTTaskManager.php
  modules/com_vtiger_workflow/VTWorkflowManager.php
  public_html/layouts/basic/modules/Settings/Workflows/resources/Edit3.js
  public_html/layouts/basic/modules/Settings/Workflows/resources/List.js
Labels: ✔ finished

#16008 Corrected calendar widget
  layouts/basic/modules/Vtiger/dashboards/Calendar.tpl
  modules/Calendar/actions/Calendar.php
  public_html/layouts/basic/modules/Vtiger/resources/dashboards/Widget.js
Labels: ✔ finished

#16038 Corrected view the Tiles
  layouts/basic/modules/Vtiger/TilesContents.tpl
  modules/Vtiger/uitypes/MultiImage.php
  public_html/layouts/basic/styles/pages/_Tiles.scss
Labels: ✔ finished

#16042 Adjusted the line width for the image field according to user settings.
  layouts/basic/modules/Vtiger/Edit/Field/MultiImage.tpl
  public_html/layouts/basic/styles/components/_Global.scss
Labels: ✔ finished

#16041 Improved deleting of records in tiles view
  public_html/layouts/basic/modules/Vtiger/resources/Tiles.js
  public_html/layouts/resources/app.js
Labels: ✔ finished

#16046 add Performance to System Tools
  languages/en-US/Settings/ConfigEditor.json
  layouts/basic/modules/Settings/ConfigEditor/ConfigTemplate.tpl
  layouts/basic/modules/Settings/ConfigEditor/Detail.tpl
  modules/Settings/ConfigEditor/models/Module.php
  modules/Settings/ConfigEditor/views/Detail.php
Labels: 🔧 AmendmentsRequired, php

#16043 add sending SMS to BaseButton panel
  languages/en-US/_Base.json
  modules/SMSNotifier/models/Module.php
  modules/Vtiger/models/DetailView.php
  modules/Vtiger/models/ListView.php
  modules/Vtiger/models/RelationListView.php
  public_html/layouts/basic/modules/Vtiger/resources/Detail.js
Labels: ✔ finished, php, javascript

#16056 Fix filter for related records
  modules/Vtiger/models/RelationListView.php
Labels: ✔ finished, php

#16058 Change cvId to viewId
  layouts/basic/modules/Vtiger/RelatedList.tpl
Labels: ✔ finished, php

#16060 Add password validator
  layouts/basic/modules/Vtiger/Edit/Field/Password.tpl
Labels: ✔ finished, javascript

#16064 PHP 8.1 & nullable value secure in filters
  app/TextParser.php
  modules/Vtiger/uitypes/AccountName.php
  modules/Vtiger/uitypes/Base.php
  modules/Vtiger/uitypes/Email.php
  modules/Vtiger/uitypes/Phone.php
Labels: ✔ finished, php

#16065 PHP 8.1 & nullable value secure for filters
  modules/Vtiger/uitypes/Country.php
  modules/Vtiger/uitypes/CurrencyList.php
Labels: ✔ finished, php

#16066 Moved modal with system information.
  app/Controller/Components/View/YetiForceDetailModal.php
  layouts/basic/components/YetiForceDetailModal.tpl
  layouts/basic/modules/Settings/ModuleManager/BodyHeader.tpl
  layouts/basic/modules/Vtiger/BodyHeader.tpl
  layouts/basic/modules/Vtiger/Footer.tpl
  public_html/layouts/resources/app.js
Labels: ✔ finished

#16068 Improved modal with system information
  app/Controller/Components/View/YetiForceDetailModal.php
  languages/en-US/_Base.json
  layouts/basic/components/YetiForceDetailModal.tpl
  layouts/basic/modules/Settings/ModuleManager/BodyHeader.tpl
  layouts/basic/modules/Vtiger/BodyHeader.tpl
  layouts/basic/modules/Vtiger/Footer.tpl
  public_html/layouts/resources/app.js
Labels: ✔ finished

#16069 PHP 8.1 & fixing display if no logo (nullable value secure)
  modules/Settings/Companies/models/Record.php
Labels: php

#16070 Changed the order in which the knowledge base is displayed
  public_html/layouts/basic/styles/libraries/_Quasar.scss
Labels: ✔ finished

#16072 Fixed the translation of the chart modal window title from the filter
  modules/Vtiger/views/ChartFilter.php
Labels: ✔ finished

#16073 Deleted file _DashBoard
  languages/en-US/Dashboard.json
  languages/en-US/_DashBoard.json
  layouts/basic/modules/Settings/WidgetsManagement/WidgetConfig.tpl
  layouts/basic/modules/Settings/WidgetsManagement/WidgetListModal.tpl
  layouts/basic/modules/Vtiger/dashboards/DashBoardButtons.tpl
  layouts/basic/modules/Vtiger/dashboards/DashBoardContents.tpl
  layouts/basic/modules/Vtiger/dashboards/DashBoardWidgetsList.tpl
  layouts/basic/modules/Vtiger/dashboards/WidgetHeaderTitle.tpl
  modules/Settings/WidgetsManagement/views/EditWidget.php
  modules/Vtiger/views/ChartFilter.php
Labels: ✔ finished

#16084 Add MaxLength validator to Performance in System Tools
  modules/Settings/ConfigEditor/actions/SaveAjax.php
  modules/Settings/ConfigEditor/models/Module.php
Labels: ✔ finished, php

#16094 Fixed saving widget position.
  modules/Vtiger/models/Widget.php
Labels: ✔ finished, php

#16095 PHP 8.1 & Notifications widget nullable value secure.
  layouts/basic/modules/Notification/NotificationsItem.tpl
Labels: ✔ finished, php

#16096 Fixed 500 error in SaveAjax.php for RecordAllocation
  modules/Settings/RecordAllocation/actions/SaveAjax.php
Labels: ✔ finished, php

#16098 Improvments for WCAG in ListContents.tpl
  layouts/basic/modules/Settings/ModuleManager/ListContents.tpl
Labels: ✔ finished, php

#16097 Improvments for WCAG in AddPanel.tpl
  layouts/basic/modules/Settings/RecordAllocation/AddPanel.tpl
Labels: ✔ finished, php

#16099 Added label column into vtiger_cvcolumnlist
  install/install_schema/data.sql
  install/install_schema/scheme.sql
Labels: ✔ finished

#16100 Revert changes
  public_html/layouts/basic/modules/Settings/LayoutEditor/resources/LayoutEditor.js
Labels: ✔ finished

#16106 Add generate & validate pass to WebservicePremium
  layouts/basic/modules/Vtiger/Edit/Field/Password.tpl
  modules/Settings/WebserviceUsers/actions/Password.php
  modules/Settings/WebserviceUsers/services/WebservicePremium.php
  public_html/layouts/resources/Fields.js
Labels: ✔ finished, php, javascript

#16107 Add new fields to relatedRecordsList template for PDF
  app/TextParser.php
Labels: php

#16108 Fixed "handler not found" error in Occurrences view.
  modules/Vtiger/models/RelationListView.php
Labels: ✔ finished, php

#16116 Add Length validation to comment_rel field
  layouts/basic/modules/Vtiger/Modals/ChangeRelationData.tpl
  modules/Occurrences/relations/GetRelatedMembers.php
  public_html/layouts/basic/modules/Vtiger/resources/ChangeRelationData.js
  public_html/layouts/basic/skins/gray/style.css
Labels: ✔ finished, php, javascript

#16119 Fixed queue popupReference error
  modules/Vtiger/uitypes/ChangesJson.php
Labels: ✔ finished, php
