Repository YetiForceCompany/YetiForceCRM, pull requests merged in 2022-06, with the labels that each got.

#16126 Web Content Accessibility Guidelines improvments
  languages/en-US/_Base.json
  layouts/basic/modules/Vtiger/ButtonLink.tpl
  layouts/basic/modules/Vtiger/ListViewContents.tpl
  layouts/basic/modules/Vtiger/ListViewHeader.tpl
  layouts/basic/modules/Vtiger/Pagination.tpl
Labels: ✔ finished, php

#16128 Actions menu in ButtonViewLinks.tpl improvements.
  layouts/basic/modules/Vtiger/ButtonViewLinks.tpl
Labels: ✔ finished, php

#16130 PHP 8.1 & nullable value secure for Cache
  modules/Vtiger/models/Record.php
  modules/Vtiger/uitypes/MailScannerActions.php
Labels: ✔ finished, php

#16131 Hidden non-active user in UserSwitch menu
  modules/Users/models/Module.php
Labels: ✔ finished, php

#16134 Add aria-label to YetiForce Shop button.
  layouts/basic/modules/Settings/ModuleManager/BodyHeader.tpl
  layouts/basic/modules/Vtiger/BodyHeader.tpl
Labels: ✔ finished

#16129 Added third option in picklist relations
  languages/en-US/Settings/PickListDependency.json
  layouts/basic/modules/Settings/PickListDependency/DependencyGraph.tpl
  layouts/basic/modules/Settings/PickListDependency/DependentFieldSettings.tpl
  layouts/basic/modules/Settings/PickListDependency/DependentFields.tpl
  layouts/basic/modules/Settings/PickListDependency/DependentTable.tpl
  layouts/basic/modules/Settings/PickListDependency/EditView.tpl
  layouts/basic/modules/Vtiger/Detail/Widget/BlockView.tpl
  modules/PickList/DependentPickListUtils.php
  modules/Settings/PickListDependency/actions/DeleteAjax.php
  modules/Settings/PickListDependency/actions/Index.php
  modules/Settings/PickListDependency/actions/SaveAjax.php
  modules/Settings/PickListDependency/models/ListView.php
  modules/Settings/PickListDependency/models/Module.php
  modules/Settings/PickListDependency/models/Record.php
  modules/Settings/PickListDependency/views/DependentFields.php
  modules/Settings/PickListDependency/views/Edit.php
  modules/Settings/PickListDependency/views/IndexAjax.php
  modules/Settings/PickListDependency/views/List.php
  modules/Settings/Vtiger/views/List.php
  modules/Vtiger/models/Module.php
  public_html/layouts/basic/modules/Settings/FieldsDependency/resources/Edit.js
  public_html/layouts/basic/modules/Settings/PickListDependency/resources/PickListDependency.js
Labels: ⏸ Not Finished

#16139 Added database for picklist dependencies
  install/install_schema/data.sql
  install/install_schema/scheme.sql
Labels: ✔ finished

#16142 WCAG in Calendar
  layouts/basic/modules/Calendar/Calendar/CalendarView.tpl
  layouts/basic/modules/Calendar/InviteEmail.tpl
  layouts/basic/modules/Vtiger/Calendar/PostProcess.tpl
  layouts/basic/modules/Vtiger/Edit/Field/MeetingUrl.tpl
Labels: ✔ finished

#16140 WCAG Base view.
  layouts/basic/modules/Vtiger/EditViewActions.tpl
  layouts/basic/modules/Vtiger/List/Field/Base.tpl
Labels: ✔ finished

#16144 Added A quick edit button to the related widget in the Summary view and list with summary.
  layouts/basic/modules/Vtiger/SummaryWidgetsContent.tpl
Labels: ✔ finished

#16146 Fixed meeting url params.
  modules/OSSMail/models/Module.php
Labels: ✔ finished

#16148 Add description to Gus and Vies.
  app/RecordCollectors/Gus.php
  app/RecordCollectors/Vies.php
  languages/en-US/Other/RecordCollector.json
Labels: ✔ finished, php

#16147 Add integration with Ministry Finance (check VAT status)[SOAP]
  app/RecordCollectors/PlVatPayerStatusVerification.php
  languages/en-US/Other/RecordCollector.json
Labels: ✔ finished, php

#16154 Add printing to modal of RecordCollector
  layouts/basic/modules/Vtiger/Modals/RecordCollector.tpl
  layouts/basic/modules/Vtiger/Modals/RecordCollectorSearch.tpl
  modules/Vtiger/views/RecordCollector.php
  public_html/layouts/resources/app.js
Labels: ✔ finished, php, javascript

#16159 fiexed #15488
  modules/Vtiger/uitypes/Tree.php
Labels: ✔ finished

#16155 add Date to print page.
  app/RecordCollectors/Vies.php
  languages/en-US/Other/RecordCollector.json
  layouts/basic/modules/Vtiger/Modals/Header.tpl
  layouts/basic/modules/Vtiger/Modals/RecordCollector.tpl
  public_html/layouts/resources/app.js
Labels: php, javascript

#16161 Change method to checkVatApprox
  app/RecordCollectors/Vies.php
Labels: ✔ finished

#16164 Add translate to Vies.php
  app/RecordCollectors/Vies.php
  languages/en-US/Other/RecordCollector.json
Labels: ✔ finished

#16168 Improved getting sla diff time
  app/Utils/ServiceContracts.php
Labels: ✔ finished

#16187 [PicklistDependency] Improved getting operators for field
  modules/Settings/PickListDependency/views/ConditionBuilder.php
Labels: ✔ finished

#16179 Add NCR to RecordCollectors
  app/RecordCollectors/PolandNationalCourtRegister.php
  languages/en-US/Other/RecordCollector.json
Labels: ✔ finished, php

#16191 Add new fields to additional options.
  app/RecordCollectors/PolandNationalCourtRegister.php
Labels: ✔ finished

#16198 Polish National Court Register code improvment.
  app/RecordCollectors/PolandNationalCourtRegister.php
Labels: ✔ finished, php

#16211 Add mapping fields to PLNationalCourtRegister
  app/RecordCollectors/PLNationalCourtRegister.php
  app/RecordCollectors/UKCompaniesHouse.php
  layouts/basic/modules/Vtiger/Modals/RecordCollectorSearch.tpl
Labels: ✔ finished

#16213 Add Country to FillFields
  app/RecordCollectors/PLNationalCourtRegister.php
Labels: ✔ finished

#16212 Rename views for RecordCollectors Settings
  layouts/basic/modules/Settings/RecordCollector/List.tpl
  modules/Settings/RecordCollector/models/Module.php
  modules/Settings/RecordCollector/views/List.php
  public_html/layouts/basic/modules/Settings/RecordCollector/resources/List.js
Labels: ✔ finished

#16214 Add documentation URL to RecordCollectors list
  app/RecordCollectors/Gus.php
  app/RecordCollectors/PLNationalCourtRegister.php
  app/RecordCollectors/PLVatPayerStatusVerification.php
  app/RecordCollectors/UKCompaniesHouse.php
  app/RecordCollectors/Vies.php
  languages/en-US/Settings/RecordCollector.json
  layouts/basic/modules/Settings/RecordCollector/List.tpl
  modules/Settings/RecordCollector/actions/SaveAjax.php
Labels: ✔ finished

#16210 Improved of Create Entity action in Workflows
  languages/en-US/Settings/Workflows.json
  layouts/basic/modules/Settings/Workflows/CreateEntity.tpl
  layouts/basic/modules/Settings/Workflows/Tasks/VTCreateEntityTask.tpl
  modules/Settings/Workflows/models/Record.php
  modules/Settings/Workflows/views/EditTask.php
  modules/com_vtiger_workflow/tasks/VTCreateEntityTask.php
  public_html/layouts/basic/modules/Settings/Workflows/resources/Edit3.js
Labels: ✔ finished

#16217 Added an active class to the filter in the menu.
  layouts/basic/modules/Vtiger/menu/CustomFilter.tpl
Labels: ✔ finished

#16218 Add modal to RecordCollectors Settings
  app/RecordCollectors/UKCompaniesHouse.php
  languages/en-US/Settings/RecordCollector.json
  layouts/basic/modules/Settings/RecordCollector/ConfigModal.tpl
  layouts/basic/modules/Settings/RecordCollector/List.tpl
  modules/Settings/RecordCollector/actions/SaveConfig.php
  modules/Settings/RecordCollector/views/CollectorConfigModal.php
  modules/Settings/RecordCollector/views/ConfigModal.php
  public_html/layouts/basic/modules/Settings/RecordCollector/resources/List.js
Labels: ✔ finished, php, javascript

#16162 Added modal synchronizer to Wapro integration
  app/Integrations/Wapro.php
  layouts/basic/modules/Settings/Wapro/ListView/SynchronizerModal.tpl
  modules/Settings/Wapro/models/Record.php
  modules/Settings/Wapro/views/UploadListSynchronizerModal.php
Labels: ⏸ Not Finished

#16222 Add hidding config button
  languages/en-US/Settings/RecordCollector.json
  public_html/layouts/basic/modules/Settings/RecordCollector/resources/List.js
Labels: ✔ finished, javascript

#16223 Record Collectors Panel Cofing minor changes
  languages/en-US/Other/RecordCollector.json
  languages/en-US/Settings/RecordCollector.json
  layouts/basic/modules/Settings/RecordCollector/List.tpl
  public_html/layouts/basic/modules/Settings/RecordCollector/resources/List.js
Labels: ✔ finished, javascript
