Repository YetiForceCompany/YetiForceCRM, pull requests merged in 2022-03, with the labels that each got.

#15781 Improved import records - finding duplicates
  public_html/layouts/basic/modules/Import/resources/Import.js
Labels: ✔ finished

#15785 Improved getting sla policy for module
  app/Utils/ServiceContracts.php
Labels: ✔ finished

#15787 Fixed the search for the tree field for the related module
  layouts/basic/modules/Vtiger/ConditionBuilder/Tree.tpl
  layouts/basic/modules/Vtiger/Edit/Field/Tree.tpl
  layouts/basic/modules/Vtiger/List/Field/Tree.tpl
  public_html/layouts/basic/modules/Vtiger/resources/AdvanceFilter.js
  public_html/layouts/resources/Fields.js
Labels: ✔ finished

#15788 Corrected removal of the policy sla in the Service Contracts module.
  app/Utils/ServiceContracts.php
  layouts/basic/modules/ServiceContracts/CustomConditions.tpl
  layouts/basic/modules/ServiceContracts/SlaPolicy.tpl
  modules/ServiceContracts/actions/PolicyDeleteAjax.php
  public_html/layouts/basic/modules/ServiceContracts/resources/Detail.js
Labels: 🔧 AmendmentsRequired

#15796 Added amount summary for corection pdf
  app/TextParser/CorectionAmountSummary.php
  languages/en-US/Other/PDF.json
  languages/en-US/Other/TextParser.json
Labels: 🔧 AmendmentsRequired

#15798 [15766] Improved export shared owner data in quick export
  app/Export/ExportRecords.php
Labels: ✔ finished

#15822 Changed the appearance of the "Latest e-mails" widget.
  layouts/basic/modules/Vtiger/dashboards/MailsListContents.tpl
  modules/OSSMail/models/Record.php
Labels: ✔ finished

#15808 Improved calendar right panel - select all
  install/install_schema/data.sql
  install/install_schema/scheme.sql
  languages/en-US/Calendar.json
  languages/en-US/OSSTimeControl.json
  languages/en-US/Occurrences.json
  languages/en-US/Reservations.json
  languages/en-US/Users.json
  languages/en-US/_Base.json
  layouts/basic/modules/Reservations/Calendar/RightPanel.tpl
  layouts/basic/modules/Vtiger/Calendar/PostProcess.tpl
  layouts/basic/modules/Vtiger/Calendar/RightPanel.tpl
  layouts/basic/modules/Vtiger/Filters/ActivityTypes.tpl
  layouts/basic/modules/Vtiger/Filters/Groups.tpl
  layouts/basic/modules/Vtiger/Filters/Users.tpl
  modules/Calendar/models/Calendar.php
  modules/Calendar/views/RightPanelExtended.php
  modules/OSSTimeControl/models/Calendar.php
  modules/OSSTimeControl/views/RightPanel.php
  modules/Occurrences/models/Calendar.php
  modules/Occurrences/views/RightPanel.php
  modules/Reservations/models/Calendar.php
  modules/Reservations/views/RightPanel.php
  modules/Vtiger/models/Calendar.php
  modules/Vtiger/models/RightPanel.php
  public_html/layouts/basic/modules/Calendar/resources/Extended/CalendarView.js
  public_html/layouts/basic/modules/Vtiger/resources/CalendarView.js
  public_html/layouts/resources/Calendar.js
  public_html/layouts/resources/YearView.js
Labels: ✔ finished

#15831 Customized additional variables
  app/Pdf/Drivers/Chromium.php
  app/Pdf/Drivers/YetiForcePDF.php
  app/TextParser/ProductsTableCorrectingBefore.php
  app/TextParser/ProductsTableShortVersion.php
  app/TextParser/TableDiscountSummary.php
  app/TextParser/TableTaxSummary.php
Labels: ✔ finished

#12827 Blocked the additional telephone field in Edit fields
  modules/Settings/LayoutEditor/views/Index.php
Labels: 👮‍♂️ VerificationRequired, ✔ finished

#15837 Fixed #14435
  public_html/layouts/basic/styles/libraries/_FullCalendar.scss
Labels: 🔧 AmendmentsRequired

#15832 [Select all calendar] Improved unselect all users
  public_html/layouts/resources/Calendar.js
Labels: ✔ finished

#15839 Addded posibility to select showners in workflow notification task
  languages/en-US/Settings/Workflows.json
  layouts/basic/modules/Settings/Workflows/Tasks/VTWatchdog.tpl
  modules/com_vtiger_workflow/tasks/VTWatchdog.php
Labels: ✔ finished
