Repository YetiForceCompany/YetiForceCRM, pull requests merged in 2023-08, with the labels that each got.

#17232 Fix: Repair debug mode in console. Compatibility with extends class
  app/Debug/DebugBar/TraceablePDOStatement.php
Labels: 🐛 bug, ✔ finished

#17242 Update Import.json
  languages/en-US/Import.json
Labels: ✔ finished

#17233 Creation of dynamic property in Documents/models/Record.php
  modules/Documents/models/Record.php
Labels: ✔ finished

#17149 Fixed getting duplicates in list view
  app/QueryGenerator.php
Labels: ✔ finished

#17239 Removed strftime function - no support since php 8.1
  modules/com_vtiger_workflow/expression_engine/VTExpressionEvaluater.php
Labels: ✔ finished

#17234 Creation of dynamic property in VTTask.php
  modules/com_vtiger_workflow/VTTask.php
Labels: ✔ finished

#17220 Creation of dynamic property in Module.php, Record.php, Basic.php
  modules/Vtiger/models/Module.php
  modules/Vtiger/models/Record.php
  modules/Vtiger/widgets/Basic.php
Labels: ✔ finished

#17249 Fixed calendar titles
  public_html/layouts/resources/Calendar.js
Labels: ✔ finished

#17240 Creation of dynamic property in TreeCategoryModal.php
  modules/Vtiger/models/TreeCategoryModal.php
  modules/Vtiger/views/BasicModal.php
  modules/Vtiger/views/TreeCategoryModal.php
Labels: ✔ finished

#17245 Support php 8.2.0
  layouts/basic/modules/Vtiger/RelatedTreeContent.tpl
  layouts/basic/modules/Vtiger/SummaryWidgetsContent.tpl
  modules/Reservations/uitypes/Time.php
Labels: ⏸ Not Finished

#17204 Added possibility of changing column length for existing fields
  languages/en-US/Settings/LayoutEditor.json
  layouts/basic/modules/Settings/LayoutEditor/EditField.tpl
  modules/Settings/LayoutEditor/actions/Field.php
  modules/Vtiger/models/Field.php
  modules/Vtiger/uitypes/Base.php
  modules/Vtiger/uitypes/Double.php
  modules/Vtiger/uitypes/Integer.php
  modules/Vtiger/uitypes/String.php
  public_html/layouts/basic/modules/Settings/LayoutEditor/resources/LayoutEditor.js
Labels: ✔ finished

#17133 Added possibility of selecting all records in record list in relation…
  layouts/basic/modules/Vtiger/Modals/RecordsList.tpl
  modules/Vtiger/actions/RelationAjax.php
  public_html/layouts/basic/modules/MailIntegration/resources/Iframe.js
  public_html/layouts/basic/modules/Vtiger/resources/Detail.js
  public_html/layouts/basic/modules/Vtiger/resources/Edit.js
  public_html/layouts/basic/modules/Vtiger/resources/RecordsList.js
  public_html/layouts/basic/modules/Vtiger/resources/RelatedList.js
Labels: ✔ finished

#17250 Support php 8.2.0
  app/RecordCollectors/Base.php
  include/fields/CurrencyField.php
  modules/Calendar/views/ActivityStateModal.php
  modules/HelpDesk/actions/CheckValidateToClose.php
  modules/Settings/AdminAccess/models/Module.php
  modules/Settings/ApiAddress/views/ApiConfigModal.php
  modules/Settings/Leads/models/Mapping.php
  modules/Settings/MailRbl/views/ConfigModal.php
  modules/Settings/MailRbl/views/UploadListModal.php
  modules/Settings/PickListDependency/models/Record.php
  modules/Settings/Profiles/models/Record.php
  modules/Settings/Roles/models/Record.php
  modules/Settings/SMSNotifier/models/Record.php
  modules/Settings/Vtiger/models/MenuItem.php
  modules/Settings/Vtiger/models/Module.php
  modules/Settings/Vtiger/views/Pagination.php
  modules/Settings/WebserviceUsers/services/ManageConsents.php
  modules/Settings/WebserviceUsers/services/WebserviceStandard.php
  modules/Settings/WidgetsManagement/views/EditWidget.php
  modules/Settings/YetiForce/views/ProductModal.php
  modules/Users/uitypes/MultiDependField.php
  modules/Vtiger/inventoryfields/Basic.php
  modules/Vtiger/models/ChartFilter.php
  modules/Vtiger/models/DashBoard.php
  modules/Vtiger/models/PDF.php
  modules/Vtiger/models/Watchdog.php
  modules/Vtiger/uitypes/Base.php
  public_html/layouts/basic/modules/Settings/PickListDependency/resources/Edit.js
Labels: ✔ finished

#17254 Removed space for filename field value
  layouts/basic/modules/Vtiger/Edit/Field/DocumentsFileUpload.tpl
Labels: ✔ finished

#17260 Fixed #17253
  modules/Accounts/dashboards/NewAccounts.php
Labels: ✔ finished

#17261 Fixed #17252
  modules/Vtiger/models/ChartFilter.php
Labels: ✔ finished

#17262 Improved the display of new contractors in the widget.
  modules/Accounts/dashboards/NewAccounts.php
Labels: ✔ finished
